import {verifyStripeSignature} from '../../_shared/payment-provider.js';
function clean(value,max=500){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function notifyEngineer(env,booking,now){if(!booking.operatorId||booking.engineerPaymentNotifiedAt||!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)return{};const operator=await env.VIPOAP_DATA.get(`operator:${booking.operatorId}`,'json');if(!operator?.email)return{};const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':`${booking.reference}-engineer-paid`},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[operator.email],subject:`Paid booking ready to confirm — ${booking.reference}`,html:`<h2>New paid VIPOAP booking</h2><p>Hello ${escapeHtml(operator.name)},</p><p>A booking matched to your availability has been paid and is ready for confirmation in VIPOAP OS.</p><p><strong>${escapeHtml(booking.reference)}</strong><br>${escapeHtml(booking.supportType)} · ${escapeHtml(booking.date)} at ${escapeHtml(booking.time)}<br>${escapeHtml(booking.service)}</p><p>Open My Area to review and confirm it.</p>`})});if(!response.ok)throw new Error(`Engineer notification failed with status ${response.status}`);return{engineerPaymentNotifiedAt:now}}
async function paymentByProvider(kv,id){const keys=await kv.list({prefix:'payment:'});for(const key of keys.keys){const value=await kv.get(key.name,'json');if(value?.providerPaymentId===id)return{key:key.name,...value}}return null}
async function paymentByIntent(kv,id){const keys=await kv.list({prefix:'payment:'});for(const key of keys.keys){const value=await kv.get(key.name,'json');if(value?.stripePaymentIntentId===id)return{key:key.name,...value}}return null}
export async function onRequestPost({request,env}){
  const raw=await request.text(),signature=request.headers.get('stripe-signature');if(!await verifyStripeSignature(env.STRIPE_WEBHOOK_SECRET,raw,signature))return Response.json({error:'Invalid Stripe signature.'},{status:401});
  let event;try{event=JSON.parse(raw)}catch{return Response.json({error:'Invalid event.'},{status:400})}const eventId=clean(event.id,150);if(!eventId)return Response.json({error:'Event ID is required.'},{status:400});
  const eventKey=`payment-event:${eventId}`;if(await env.VIPOAP_DATA.get(eventKey))return Response.json({ok:true,duplicate:true});
  const object=event.data?.object||{},isRefund=event.type==='charge.refunded',providerPaymentId=clean(object.id,200),payment=isRefund?await paymentByIntent(env.VIPOAP_DATA,clean(object.payment_intent,200)):await paymentByProvider(env.VIPOAP_DATA,providerPaymentId);if(!payment)return Response.json({error:'Payment not found.'},{status:404});
  if(isRefund){const now=new Date().toISOString(),amount=Number(object.amount_refunded||0)/100,refundKey=`refund:${eventId}`;await env.VIPOAP_DATA.put(payment.key,JSON.stringify({...payment,status:'refunded',updatedAt:now}));await env.VIPOAP_DATA.put(refundKey,JSON.stringify({paymentId:payment.key,bookingId:payment.bookingKey,customerId:payment.customerId,type:'service',amount,status:'completed',providerReference:providerPaymentId,reason:clean(object.refunds?.data?.[0]?.reason||'Stripe refund'),createdAt:now,completedAt:now}));const booking=await env.VIPOAP_DATA.get(payment.bookingKey,'json');if(booking)await env.VIPOAP_DATA.put(payment.bookingKey,JSON.stringify({...booking,paymentStatus:'refunded',updatedAt:now}));await env.VIPOAP_DATA.put(eventKey,JSON.stringify({provider:'stripe',type:event.type,providerPaymentId,processedAt:now}));return Response.json({ok:true})}
  const now=new Date().toISOString(),map={'checkout.session.completed':'paid','checkout.session.async_payment_succeeded':'paid','checkout.session.async_payment_failed':'failed','checkout.session.expired':'failed'},status=map[event.type];if(!status)return Response.json({error:'Unsupported event.'},{status:400});
  await env.VIPOAP_DATA.put(payment.key,JSON.stringify({...payment,status,stripePaymentIntentId:clean(object.payment_intent,200),providerReference:clean(object.payment_intent||object.id,200),updatedAt:now}));const booking=await env.VIPOAP_DATA.get(payment.bookingKey,'json');if(booking){const isAdditionalTime=payment.type==='additional-time',expired=!isAdditionalTime&&event.type==='checkout.session.expired',paymentStatus=status==='paid'?(isAdditionalTime?'paid':'prepaid'):status,bookingStatus=expired?'cancelled':status==='paid'?(isAdditionalTime?'completed':'requested'):booking.bookingStatus,settlement=status==='paid'&&isAdditionalTime?{finalSettlementPaidAt:now,finalSettlementStatus:'paid'}:isAdditionalTime?{finalSettlementStatus:status}:{},expiry=expired?{status:'cancelled',paymentExpiredAt:now,cancellationReason:'Payment was not completed before the Stripe session expired.'}:{};let notification={};if(status==='paid'&&!isAdditionalTime)try{notification=await notifyEngineer(env,booking,now)}catch(error){notification={engineerNotificationError:clean(error?.message),engineerNotificationFailedAt:now}}await env.VIPOAP_DATA.put(payment.bookingKey,JSON.stringify({...booking,paymentStatus,bookingStatus,...settlement,...expiry,...notification,updatedAt:now}))}
  if(status==='paid'&&payment.type!=='additional-time'){const paidBooking=await env.VIPOAP_DATA.get(payment.bookingKey,'json');if(paidBooking?.helpReference){const helpKey=await env.VIPOAP_DATA.get(`help-reference:${paidBooking.helpReference}`),help=helpKey?await env.VIPOAP_DATA.get(helpKey,'json'):null;if(help)await env.VIPOAP_DATA.put(helpKey,JSON.stringify({...help,status:'arranged',bookingKey:payment.bookingKey,bookingReference:paidBooking.reference,updatedAt:now}))}}
  await env.VIPOAP_DATA.put(eventKey,JSON.stringify({provider:'stripe',type:event.type,providerPaymentId,processedAt:now}));return Response.json({ok:true});
}
