import {verifyStripeSignature} from '../../_shared/payment-provider.js';
function clean(value,max=500){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
async function paymentByProvider(kv,id){const keys=await kv.list({prefix:'payment:'});for(const key of keys.keys){const value=await kv.get(key.name,'json');if(value?.providerPaymentId===id)return{key:key.name,...value}}return null}
async function paymentByIntent(kv,id){const keys=await kv.list({prefix:'payment:'});for(const key of keys.keys){const value=await kv.get(key.name,'json');if(value?.stripePaymentIntentId===id)return{key:key.name,...value}}return null}
export async function onRequestPost({request,env}){
  const raw=await request.text(),signature=request.headers.get('stripe-signature');if(!await verifyStripeSignature(env.STRIPE_WEBHOOK_SECRET,raw,signature))return Response.json({error:'Invalid Stripe signature.'},{status:401});
  let event;try{event=JSON.parse(raw)}catch{return Response.json({error:'Invalid event.'},{status:400})}const eventId=clean(event.id,150);if(!eventId)return Response.json({error:'Event ID is required.'},{status:400});
  const eventKey=`payment-event:${eventId}`;if(await env.VIPOAP_DATA.get(eventKey))return Response.json({ok:true,duplicate:true});
  const object=event.data?.object||{},isRefund=event.type==='charge.refunded',providerPaymentId=clean(object.id,200),payment=isRefund?await paymentByIntent(env.VIPOAP_DATA,clean(object.payment_intent,200)):await paymentByProvider(env.VIPOAP_DATA,providerPaymentId);if(!payment)return Response.json({error:'Payment not found.'},{status:404});
  if(isRefund){const now=new Date().toISOString(),amount=Number(object.amount_refunded||0)/100,refundKey=`refund:${eventId}`;await env.VIPOAP_DATA.put(payment.key,JSON.stringify({...payment,status:'refunded',updatedAt:now}));await env.VIPOAP_DATA.put(refundKey,JSON.stringify({paymentId:payment.key,bookingId:payment.bookingKey,customerId:payment.customerId,type:'service',amount,status:'completed',providerReference:providerPaymentId,reason:clean(object.refunds?.data?.[0]?.reason||'Stripe refund'),createdAt:now,completedAt:now}));const booking=await env.VIPOAP_DATA.get(payment.bookingKey,'json');if(booking)await env.VIPOAP_DATA.put(payment.bookingKey,JSON.stringify({...booking,paymentStatus:'refunded',updatedAt:now}));await env.VIPOAP_DATA.put(eventKey,JSON.stringify({provider:'stripe',type:event.type,providerPaymentId,processedAt:now}));return Response.json({ok:true})}
  const now=new Date().toISOString(),map={'checkout.session.completed':'paid','checkout.session.async_payment_succeeded':'paid','checkout.session.async_payment_failed':'failed','checkout.session.expired':'failed'},status=map[event.type];if(!status)return Response.json({error:'Unsupported event.'},{status:400});
  await env.VIPOAP_DATA.put(payment.key,JSON.stringify({...payment,status,stripePaymentIntentId:clean(object.payment_intent,200),providerReference:clean(object.payment_intent||object.id,200),updatedAt:now}));const booking=await env.VIPOAP_DATA.get(payment.bookingKey,'json');if(booking){const isAdditionalTime=payment.type==='additional-time',paymentStatus=status==='paid'?(isAdditionalTime?'paid':'prepaid'):status,bookingStatus=status==='paid'?(isAdditionalTime?'completed':'requested'):booking.bookingStatus,settlement=status==='paid'&&isAdditionalTime?{finalSettlementPaidAt:now,finalSettlementStatus:'paid'}:isAdditionalTime?{finalSettlementStatus:status}:{};await env.VIPOAP_DATA.put(payment.bookingKey,JSON.stringify({...booking,paymentStatus,bookingStatus,...settlement,updatedAt:now}))}
  await env.VIPOAP_DATA.put(eventKey,JSON.stringify({provider:'stripe',type:event.type,providerPaymentId,processedAt:now}));return Response.json({ok:true});
}
