const WINDOWS=[{id:'24h',target:24*60,tolerance:20},{id:'3h',target:3*60,tolerance:20}];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ukAppointment(date,time){const naive=Date.parse(`${date}T${time}:00Z`),parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(naive)).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),shown=Date.UTC(parts.year,parts.month-1,parts.day,parts.hour,parts.minute),offset=shown-naive;return new Date(naive-offset)}
async function send(env,booking,window,key){
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':key},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[booking.email],subject:`Reminder: your VIPOAP visit is ${window.id==='24h'?'tomorrow':'in a few hours'}`,html:`<div style="font-family:Arial,sans-serif;color:#102957"><h1>VIPOAP appointment reminder</h1><p>Hello ${esc(booking.name)},</p><p>This is a reminder that your local VIPOAP Engineer Partner is due to visit on <strong>${esc(booking.date)}</strong> at <strong>${esc(booking.time)}</strong>.</p><p><strong>Service:</strong> ${esc(booking.service)}<br><strong>Length:</strong> ${esc(booking.duration)} minutes<br><strong>Price:</strong> ${esc(booking.price)}</p><p>If you need to change the appointment, call 07977 254158 or email help@vipoap.co.uk as soon as possible.</p></div>`})});
  if(!response.ok)throw Error(`Reminder email failed with status ${response.status}`);
}
async function sendSettlementReminder(env,booking,window,key){const email=booking.email||booking.bookerEmail,response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':key},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[email],subject:`Reminder: additional time payment for ${booking.reference}`,html:`<div style="font-family:Arial,sans-serif;color:#102957"><h1>VIPOAP payment reminder</h1><p>Hello ${esc(booking.name)},</p><p>This is a ${window==='7d'?'follow-up ':''}reminder for the <strong>£${Number(booking.additionalAmount||0).toFixed(2)}</strong> additional time approved during your appointment.</p><p><a href="${esc(booking.finalPaymentUrl)}">Pay securely with Stripe</a></p><p>Your original appointment was paid separately. If you have already paid, no action is needed while Stripe updates the record.</p><p>If something does not look right, email help@vipoap.co.uk before paying.</p></div>`})});if(!response.ok)throw Error(`Settlement reminder failed with status ${response.status}`)}
export async function processReminders(env,now=new Date()){
  if(!env.VIPOAP_DATA||!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)throw Error('Reminder Worker bindings are incomplete.');
  const page=await env.VIPOAP_DATA.list({prefix:'booking:'});let sent=0,skipped=0;
  for(const item of page.keys){const booking=await env.VIPOAP_DATA.get(item.name,'json');if(!booking||booking.status!=='confirmed'||!booking.email){skipped++;continue}const appointment=ukAppointment(booking.date,booking.time),minutes=(appointment-now)/60000;const window=WINDOWS.find(x=>Math.abs(minutes-x.target)<=x.tolerance);if(!window){skipped++;continue}const marker=`reminder:${item.name}:${window.id}`;if(await env.VIPOAP_DATA.get(marker)){skipped++;continue}await send(env,booking,window,marker);await env.VIPOAP_DATA.put(marker,JSON.stringify({sentAt:now.toISOString(),reference:booking.reference}),{expirationTtl:604800});sent++}
  return{sent,skipped};
}
export async function processSettlementReminders(env,now=new Date()){if(!env.VIPOAP_DATA||!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)throw Error('Reminder Worker bindings are incomplete.');const page=await env.VIPOAP_DATA.list({prefix:'booking:'});let sent=0,skipped=0;for(const item of page.keys){const booking=await env.VIPOAP_DATA.get(item.name,'json'),email=booking?.email||booking?.bookerEmail;if(!booking||booking.paymentStatus!=='additional-payment-due'||booking.finalSettlementStatus!=='pending'||!booking.finalPaymentUrl||!email||!booking.completedAt){skipped++;continue}const age=(now-new Date(booking.completedAt))/86400000,window=age>=7?'7d':age>=2?'48h':'';if(!window){skipped++;continue}const marker=`settlement-reminder:${item.name}:${window}`;if(await env.VIPOAP_DATA.get(marker)){skipped++;continue}await sendSettlementReminder(env,booking,window,marker);const sentAt=now.toISOString();await env.VIPOAP_DATA.put(marker,JSON.stringify({sentAt,reference:booking.reference,window}),{expirationTtl:7776000});await env.VIPOAP_DATA.put(item.name,JSON.stringify({...booking,finalSettlementLastReminderAt:sentAt,finalSettlementReminderCount:Number(booking.finalSettlementReminderCount||0)+1,updatedAt:sentAt}));sent++}return{sent,skipped}}
export async function processExpiredHolds(env,now=new Date()){if(!env.VIPOAP_DATA)throw Error('Reminder Worker bindings are incomplete.');const page=await env.VIPOAP_DATA.list({prefix:'booking:'});let released=0,skipped=0;for(const item of page.keys){const booking=await env.VIPOAP_DATA.get(item.name,'json'),unpaid=['payment-required','pending','failed'].includes(booking?.paymentStatus),expired=booking?.holdExpiresAt&&new Date(booking.holdExpiresAt)<=now;if(!booking||!unpaid||!expired||['cancelled','declined','completed'].includes(booking.bookingStatus)){skipped++;continue}const releasedAt=now.toISOString();await env.VIPOAP_DATA.put(item.name,JSON.stringify({...booking,status:'cancelled',bookingStatus:'cancelled',paymentStatus:'failed',paymentExpiredAt:booking.paymentExpiredAt||releasedAt,holdReleasedAt:releasedAt,cancellationReason:'Payment was not completed before the slot hold expired.',updatedAt:releasedAt}));await env.VIPOAP_DATA.put(`audit:hold-release:${booking.reference||item.name}`,JSON.stringify({event:'booking_hold_released',bookingKey:item.name,reference:booking.reference||'',releasedAt,reason:'payment_timeout'}),{expirationTtl:7776000});released++}return{released,skipped}}
async function resolveRecovered(env,name,now){const page=await env.VIPOAP_DATA.list({prefix:'operational-failure:'});for(const key of page.keys){const failure=await env.VIPOAP_DATA.get(key.name,'json');if(failure?.stage===name&&failure.status==='open')await env.VIPOAP_DATA.put(key.name,JSON.stringify({...failure,status:'resolved',resolutionNotes:'Automatically resolved after a successful scheduled run.',resolvedAt:now.toISOString(),resolvedBy:'system'}),{expirationTtl:7776000})}}
async function runStage(env,name,operation,now){try{const result=await operation();await resolveRecovered(env,name,now);return result}catch(error){const message=String(error?.message||'Unknown scheduled task failure').slice(0,500),failedAt=now.toISOString();await env.VIPOAP_DATA.put(`operational-failure:${now.getTime()}:${name}`,JSON.stringify({source:'booking-reminders',stage:name,status:'open',message,failedAt}),{expirationTtl:7776000});return{error:message}}}
export async function processAllReminders(env,now=new Date()){if(!env.VIPOAP_DATA)throw Error('Reminder Worker bindings are incomplete.');const holds=await runStage(env,'expired-holds',()=>processExpiredHolds(env,now),now),appointments=await runStage(env,'appointment-reminders',()=>processReminders(env,now),now),settlements=await runStage(env,'settlement-reminders',()=>processSettlementReminders(env,now),now),result={holds,appointments,settlements},failedStages=Object.values(result).filter(stage=>stage?.error).length;await env.VIPOAP_DATA.put('system:booking-reminders:last-run',JSON.stringify({completedAt:now.toISOString(),status:failedStages?'attention':'ok',failedStages,result}),{expirationTtl:604800});return result}
export default{async scheduled(_controller,env,ctx){ctx.waitUntil(processAllReminders(env))}};
