import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPost as jobAction} from '../functions/api/admin/job-actions.js';
import {onRequestGet as getApproval,onRequestPost as answerApproval} from '../functions/api/additional-time-approval.js';

function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',RESEND_API_KEY:'resend',BOOKING_FROM_EMAIL:'VIPOAP <bookings@example.test>',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}}}}
const adminRequest=body=>new Request('https://example.test/api/admin/job-actions',{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify(body)});

test('additional time requires the customer response and is billed afterwards',async t=>{const{env,values}=setup();values.set('booking:one',JSON.stringify({reference:'VIP-ONE',name:'Margaret',email:'margaret@example.test',notificationChannel:'Email',jobStatus:'in-progress',paymentStatus:'prepaid',paymentMethod:'online'}));let email,original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{email=JSON.parse(options.body);return new Response('{}',{status:200})};t.after(()=>globalThis.fetch=original);let response=await jobAction({request:adminRequest({bookingKey:'booking:one',action:'request-additional-time',blocks:1}),env}),requested=await response.json();assert.equal(response.status,200);assert.equal(requested.status,'awaiting-customer');assert.equal(requested.charge,25);assert.match(email.html,/billed after the appointment/i);const token=new URL(requested.approvalUrl).searchParams.get('token');response=await getApproval({request:new Request(`https://example.test/api/additional-time-approval?token=${token}`),env});assert.equal((await response.json()).minutes,30);response=await answerApproval({request:new Request('https://example.test/api/additional-time-approval',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,decision:'approve'})}),env});assert.equal(response.status,200);const booking=JSON.parse(values.get('booking:one'));assert.equal(booking.additionalAmount,25);assert.equal(booking.paymentStatus,'additional-payment-due');assert.equal(booking.additionalTime[0].approvalMethod,'customer-link')});
