import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {digest} from '../functions/_shared/admin-auth.js';
import {onRequestGet as billingOverview} from '../functions/api/admin/billing-overview.js';
import {onRequestPost as membershipCheckout} from '../functions/api/payments/membership-checkout.js';
import {onRequestPost as connect} from '../functions/api/admin/stripe-connect.js';
import {onRequestPost as payout} from '../functions/api/admin/stripe-payouts.js';
import {onRequestPost as refundPayment} from '../functions/api/admin/refunds.js';
import {onRequestPost as webhook} from '../functions/api/payments/webhook.js';import {sign} from '../functions/_shared/payment-provider.js';
function setup(){const values=new Map(),kv={async get(k,t){const v=values.get(k);return t==='json'&&v?JSON.parse(v):v??null},async put(k,v){values.set(k,v)},async list({prefix}){return{keys:[...values.keys()].filter(k=>k.startsWith(prefix)).map(name=>({name}))}}};return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:kv,STRIPE_SECRET_KEY:'sk_test',STRIPE_PUBLISHABLE_KEY:'pk_test',STRIPE_SUPPORT_MONTHLY_PRICE_ID:'price_support',STRIPE_WEBHOOK_SECRET:'whsec_test'}}}
test('billing dashboard itemises Engineer liabilities and Connect readiness',async()=>{const{values,env}=setup();values.set('operator:alex',JSON.stringify({id:'alex',name:'Alex',email:'alex@example.test',territoryIds:['andover'],stripeConnectedAccountId:'acct_alex',stripePayoutsEnabled:true}));values.set('booking:one',JSON.stringify({reference:'VIP-ONE',operatorId:'alex',territoryId:'andover',status:'completed',supportType:'Remote support',duration:60,service:'Wi-Fi',name:'Customer'}));const response=await billingOverview({request:new Request('https://example.test/api/admin/billing-overview',{headers:{'x-admin-password':'secret'}}),env}),data=await response.json();assert.equal(response.status,200);assert.equal(data.summary.awaitingPence,3150);assert.equal(data.engineers[0].jobs[0].amountPence,3150);assert.equal(data.summary.connectReady,1)});
test('customer starts an embedded £7.99 Stripe subscription',async t=>{const{values,env}=setup(),token='customer-token';values.set(`customer-session:${await digest(token)}`,JSON.stringify({customerId:'customer:one',email:'one@example.test',expiresAt:new Date(Date.now()+86400000).toISOString()}));values.set('customer:one',JSON.stringify({name:'One',email:'one@example.test',membershipPlan:'none',membershipStatus:'none'}));const original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{assert.match(options.body,/mode=subscription/);assert.match(options.body,/ui_mode=embedded/);assert.match(options.body,/price_support/);return Response.json({id:'cs_sub',client_secret:'cs_secret'})};t.after(()=>globalThis.fetch=original);const response=await membershipCheckout({request:new Request('https://example.test/api/payments/membership-checkout',{method:'POST',headers:{'content-type':'application/json','x-customer-session':token},body:'{}'}),env}),data=await response.json();assert.equal(response.status,200);assert.equal(data.publishableKey,'pk_test');assert.equal(data.clientSecret,'cs_secret')});
test('Connect onboarding creates an Express account without storing bank details',async t=>{const{values,env}=setup();values.set('operator:alex',JSON.stringify({id:'alex',name:'Alex',email:'alex@example.test',territoryIds:['andover']}));const original=globalThis.fetch;globalThis.fetch=async(url)=>url.endsWith('/accounts')?Response.json({id:'acct_alex',details_submitted:false}):Response.json({url:'https://connect.stripe.test/onboard',expires_at:123});t.after(()=>globalThis.fetch=original);const response=await connect({request:new Request('https://example.test/api/admin/stripe-connect',{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify({operatorId:'alex'})}),env}),saved=JSON.parse(values.get('operator:alex'));assert.equal(response.status,200);assert.equal(saved.stripeConnectedAccountId,'acct_alex');assert.equal(JSON.stringify(saved).includes('bank'),false)});
test('confirmed Stripe Connect payout records the transfer and blocks duplicates',async t=>{const{values,env}=setup();values.set('operator:alex',JSON.stringify({id:'alex',stripeConnectedAccountId:'acct_alex',stripePayoutsEnabled:true}));values.set('booking:one',JSON.stringify({reference:'VIP-ONE',operatorId:'alex',territoryId:'andover',status:'completed',supportType:'Remote support',duration:30}));const original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{assert.match(options.body,/amount=1750/);return Response.json({id:'tr_one'})};t.after(()=>globalThis.fetch=original);const request=()=>new Request('https://example.test/api/admin/stripe-payouts',{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify({bookingKey:'booking:one',confirm:'VIP-ONE'})});let response=await payout({request:request(),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('booking:one')).providerStripeTransferId,'tr_one');response=await payout({request:request(),env});assert.equal(response.status,409)});
test('Stripe subscription and Connect webhooks update customer and Engineer status',async()=>{const{values,env}=setup();values.set('customer:one',JSON.stringify({name:'One',membershipPlan:'none'}));values.set('subscription-checkout:cs_sub',JSON.stringify({customerId:'customer:one',status:'pending'}));values.set('operator:alex',JSON.stringify({id:'alex',stripeConnectedAccountId:'acct_alex'}));async function send(event){const raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=`t=${timestamp},v1=${await sign(env.STRIPE_WEBHOOK_SECRET,`${timestamp}.${raw}`)}`;return webhook({request:new Request('https://example.test/api/payments/webhook',{method:'POST',headers:{'stripe-signature':signature},body:raw}),env})}let response=await send({id:'evt_sub',type:'checkout.session.completed',data:{object:{id:'cs_sub',mode:'subscription',customer:'cus_one',subscription:'sub_one'}}});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('customer:one')).membershipStatus,'active');response=await send({id:'evt_connect',type:'account.updated',data:{object:{id:'acct_alex',details_submitted:true,charges_enabled:true,payouts_enabled:true,requirements:{currently_due:[]}}}});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('operator:alex')).stripePayoutsEnabled,true)});
test('billing and Network pages expose the new Stripe controls',()=>{const billing=fs.readFileSync(new URL('../admin/billing.html',import.meta.url),'utf8'),control=fs.readFileSync(new URL('../admin/billing-control.js',import.meta.url),'utf8'),network=fs.readFileSync(new URL('../admin/franchise.html',import.meta.url),'utf8');assert.match(billing,/billing-control\.js/);assert.match(control,/Engineer payout queue/);assert.match(control,/Pay with Stripe/);assert.match(network,/stripe-connect-panel\.js/)});
test('confirmed customer refund is created in Stripe and recorded for reconciliation',async t=>{const{values,env}=setup();values.set('payment:booking:VIP-REFUND',JSON.stringify({bookingReference:'VIP-REFUND',bookingKey:'booking:refund',customerId:'customer:one',type:'service',amount:49,status:'paid',stripePaymentIntentId:'pi_refund'}));const original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{assert.match(options.body,/payment_intent=pi_refund/);assert.match(options.body,/amount=4900/);return Response.json({id:'re_one',status:'succeeded'})};t.after(()=>globalThis.fetch=original);const response=await refundPayment({request:new Request('https://example.test/api/admin/refunds',{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify({paymentKey:'payment:booking:VIP-REFUND',amountPence:4900,confirm:'VIP-REFUND',reason:'requested_by_customer'})}),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('payment:booking:VIP-REFUND')).status,'refunded');assert.equal(JSON.parse(values.get('refund-request:re_one')).amount,49)});
