import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestGet as listBookings,onRequestPatch as updateBooking} from '../functions/api/admin/bookings.js';
import {onRequestGet as getAvailability,onRequestPost as saveAvailability} from '../functions/api/admin/availability.js';
import {onRequestGet as getPublicAvailability} from '../functions/api/availability.js';
import {digest} from '../functions/_shared/admin-auth.js';

function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',RESEND_API_KEY:'resend',BOOKING_FROM_EMAIL:'VIPOAP <bookings@example.test>',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}}}}
const request=(url,body)=>new Request(url,{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify(body)});

test('paid booking confirmation sends the customer confirmation once',async t=>{const{env,values}=setup(),key='booking:2026-08-20:10:00';values.set(key,JSON.stringify({reference:'VIP-PAID',name:'Margaret',email:'margaret@example.test',supportType:'Home visit',date:'2026-08-20',time:'10:00',duration:60,price:'£30',status:'pending',paymentStatus:'prepaid'}));const sent=[],original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{sent.push(JSON.parse(options.body));return new Response('{}',{status:200})};t.after(()=>globalThis.fetch=original);let response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed',adminNotes:'Paid'}),env});assert.equal(response.status,200);assert.equal(sent.length,1);assert.match(sent[0].subject,/confirmed/i);assert.match(sent[0].html,/additional time.*billed after/i);response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed',adminNotes:'Updated'}),env});assert.equal(response.status,200);assert.equal(sent.length,1)});

test('unpaid booking cannot be confirmed',async()=>{const{env,values}=setup(),key='booking:2026-08-20:11:00';values.set(key,JSON.stringify({reference:'VIP-UNPAID',status:'pending',paymentStatus:'payment-required'}));const response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed'}),env});assert.equal(response.status,409);assert.match((await response.json()).error,/Advance payment/)});

test('Engineer Partner can use one seven-day calendar with services per time block',async()=>{const{env,values}=setup(),weeklyBlocks={monday:[{start:'09:00',end:'12:00',services:['home','remote']}],tuesday:[{start:'13:00',end:'18:00',services:['remote']}],wednesday:[],thursday:[],friday:[],saturday:[],sunday:[{start:'10:00',end:'12:00',services:['home']}]},body={weeklyBlocks,blockedDates:['2026-08-24'],overrides:[]};let response=await saveAvailability({request:request('https://example.test/api/admin/availability',body),env});assert.equal(response.status,200);assert.ok(values.has('availability:andover:dan-stevens'));response=await getAvailability({request:new Request('https://example.test/api/admin/availability',{headers:{'x-admin-password':'secret'}}),env});const data=await response.json();assert.deepEqual(data.weeklyBlocks,weeklyBlocks);assert.deepEqual(data.homeVisitWeekly.monday,[['09:00','12:00']]);assert.deepEqual(data.remoteWeekly.tuesday,[['13:00','18:00']]);assert.deepEqual(data.homeVisitWeekly.sunday,[['10:00','12:00']]);assert.deepEqual(data.blockedDates,['2026-08-24'])});

test('availability only accepts services enabled on the engineer profile',async()=>{const{env,values}=setup();values.set('operator:dan-stevens',JSON.stringify({id:'dan-stevens',serviceTypes:['remote']}));const weeklyBlocks=Object.fromEntries(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].map(day=>[day,day==='monday'?[{start:'09:00',end:'12:00',services:['home']}]:[]])),response=await saveAvailability({request:request('https://example.test/api/admin/availability',{weeklyBlocks,blockedDates:[],overrides:[]}),env});assert.equal(response.status,400);assert.match((await response.json()).error,/services from your profile/i)});

test('public booking hides services not enabled on the engineer profile',async()=>{const{env,values}=setup();values.set('operator:dan-stevens',JSON.stringify({id:'dan-stevens',serviceTypes:['remote']}));values.set('availability:andover:dan-stevens',JSON.stringify({territoryId:'andover',operatorId:'dan-stevens',homeVisitWeekly:{monday:[['09:00','12:00']]},remoteWeekly:{monday:[['09:00','12:00']]},blockedDates:[]}));const response=await getPublicAvailability({request:new Request('https://example.test/api/availability?date=2026-08-17&duration=60&supportType=Home%20visit'),env}),data=await response.json();assert.deepEqual(data.slots,[])});

test('operator booking queue only exposes and updates assigned work',async()=>{const{env,values}=setup(),token='operator-session';values.set(`admin-session:${await digest(token)}`,JSON.stringify({role:'operator',operatorId:'engineer-one',territoryIds:['andover']}));values.set('booking:one',JSON.stringify({reference:'VIP-ONE',operatorId:'engineer-one',territoryId:'andover',date:'2026-08-17',time:'10:00',status:'pending'}));values.set('booking:two',JSON.stringify({reference:'VIP-TWO',operatorId:'engineer-two',territoryId:'andover',date:'2026-08-17',time:'11:00',status:'pending'}));const headers={'x-admin-session':token,'content-type':'application/json'},listed=await listBookings({request:new Request('https://example.test/api/admin/bookings',{headers}),env}),data=await listed.json();assert.deepEqual(data.bookings.map(item=>item.reference),['VIP-ONE']);const response=await updateBooking({request:new Request('https://example.test/api/admin/bookings',{method:'PATCH',headers,body:JSON.stringify({key:'booking:two',status:'declined'})}),env});assert.equal(response.status,404)});
