import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPost} from '../functions/api/bookings.js';

function nextMonday(){const date=new Date();date.setUTCDate(date.getUTCDate()+((8-date.getUTCDay())%7||7));return date.toISOString().slice(0,10)}
function request(overrides={}){return new Request('https://example.test/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({supportType:'Home visit',service:'General Technology Help',duration:60,date:nextMonday(),time:'19:00',name:'Test Customer',phone:'01234 567890',email:'test@example.com',address:'1 Test Street',postcode:'SP10 1AA',notificationChannel:'Email',details:'Wi-Fi help',...overrides})})}
function environment(){const values=new Map();return{values,env:{RESEND_API_KEY:'test-key',BOOKING_FROM_EMAIL:'VIPOAP Bookings <bookings@example.test>',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async delete(key){values.delete(key)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}}}}
function storedBookings(values){return[...values.entries()].filter(([key])=>key.startsWith(`booking:${nextMonday()}:`)).map(([,value])=>JSON.parse(value))}

test('fails safely when required bindings are missing',async()=>{const response=await onRequestPost({request:request(),env:{}});assert.equal(response.status,503);assert.match((await response.json()).error,/temporarily unavailable/i)});
test('rejects a time outside configured availability',async()=>{const{env}=environment(),response=await onRequestPost({request:request({time:'18:00'}),env});assert.equal(response.status,409)});
test('stores an offered slot at the active one-hour home price',async t=>{const{env,values}=environment(),emails=[],originalFetch=globalThis.fetch;globalThis.fetch=async(_url,options)=>{emails.push(JSON.parse(options.body));return new Response(null,{status:202})};t.after(()=>{globalThis.fetch=originalFetch});const response=await onRequestPost({request:request({details:'Router <script>alert(1)</script> & setup'}),env}),result=await response.json();assert.equal(response.status,200);const dateCode=`${nextMonday().slice(5,7)}${nextMonday().slice(8,10)}`;assert.match(result.reference,new RegExp(`^VIP-${dateCode}\\d{4}$`));const[stored]=storedBookings(values);assert.ok(stored.customerId.startsWith('customer:'));assert.equal(stored.territoryId,'andover');assert.equal(stored.paymentMethod,'online');assert.equal(stored.paymentStatus,'payment-required');assert.equal(stored.bookingStatus,'slot-held');assert.equal(stored.price,'£64');assert.equal(stored.pricePence,6400);assert.equal(stored.providerEntitlementPence,4500);assert.equal(stored.platformFeePence,1900);assert.equal(result.paymentRequired,true);assert.equal(emails.length,2);assert.doesNotMatch(emails[0].html,/<script>/);assert.match(emails[0].html,/&amp;/);assert.match(emails[0].html,/£64/);assert.match(emails[1].html,/Service price:<\/strong> £64/)});
test('allows and prices a 30-minute home visit',async t=>{const{env,values}=environment(),originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:202});t.after(()=>{globalThis.fetch=originalFetch});const response=await onRequestPost({request:request({duration:30}),env});assert.equal(response.status,200);const[stored]=storedBookings(values);assert.equal(stored.price,'£39');assert.equal(stored.pricePence,3900);assert.equal(stored.providerEntitlementPence,2500);assert.equal(stored.platformFeePence,1400)});
test('prices and stores a 30-minute remote-support request',async t=>{const{env,values}=environment(),originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:202});t.after(()=>{globalThis.fetch=originalFetch});const response=await onRequestPost({request:request({supportType:'Remote support',duration:30,address:''}),env});assert.equal(response.status,200);const[stored]=storedBookings(values);assert.equal(stored.supportType,'Remote support');assert.equal(stored.price,'£25');assert.equal(stored.pricePence,2500)});
test('stores an authorised family contact when booking for someone else',async t=>{const{env,values}=environment(),emails=[],originalFetch=globalThis.fetch;globalThis.fetch=async(_url,options)=>{emails.push(JSON.parse(options.body));return new Response(null,{status:202})};t.after(()=>{globalThis.fetch=originalFetch});const response=await onRequestPost({request:request({bookingFor:'someone_else',bookerName:'Alex Customer',bookerPhone:'07123 456789',bookerEmail:'alex@example.com',relationship:'Daughter'}),env});assert.equal(response.status,200);const[stored]=storedBookings(values);assert.equal(stored.bookingFor,'someone_else');assert.equal(stored.bookerName,'Alex Customer');assert.match(emails[0].html,/Authorised family\/contact/);assert.deepEqual(emails[1].to,['test@example.com','alex@example.com'])});
test('removes the reservation when email delivery fails',async t=>{const{env,values}=environment(),originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:500});t.after(()=>{globalThis.fetch=originalFetch});const response=await onRequestPost({request:request(),env});assert.equal(response.status,502);assert.equal(storedBookings(values).length,0)});
test('matches simultaneous bookings to separate eligible engineers',async t=>{const{env,values}=environment(),weekly={monday:[['19:00','21:00']]};for(const id of ['engineer-one','engineer-two']){values.set(`operator:${id}`,JSON.stringify({id,serviceTypes:['home']}));values.set(`availability:andover:${id}`,JSON.stringify({territoryId:'andover',operatorId:id,homeVisitWeekly:weekly,remoteWeekly:{},blockedDates:[]}))}const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:202});t.after(()=>{globalThis.fetch=originalFetch});let response=await onRequestPost({request:request({name:'First Customer',email:'first@example.com'}),env});assert.equal(response.status,200);response=await onRequestPost({request:request({name:'Second Customer',email:'second@example.com',phone:'01234 111111',address:'2 Test Street'}),env});assert.equal(response.status,200);const bookings=storedBookings(values);assert.equal(bookings.length,2);assert.deepEqual(new Set(bookings.map(item=>item.operatorId)),new Set(['engineer-one','engineer-two']));response=await onRequestPost({request:request({name:'Third Customer',email:'third@example.com',phone:'01234 222222',address:'3 Test Street'}),env});assert.equal(response.status,409)});
