import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPatch as updateBooking} from '../functions/api/admin/bookings.js';
import {onRequestGet as getAvailability,onRequestPost as saveAvailability} from '../functions/api/admin/availability.js';

function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',RESEND_API_KEY:'resend',BOOKING_FROM_EMAIL:'VIPOAP <bookings@example.test>',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}}}}
const request=(url,body)=>new Request(url,{method:'POST',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify(body)});

test('paid booking confirmation sends the customer confirmation once',async t=>{const{env,values}=setup(),key='booking:2026-08-20:10:00';values.set(key,JSON.stringify({reference:'VIP-PAID',name:'Margaret',email:'margaret@example.test',supportType:'Home visit',date:'2026-08-20',time:'10:00',duration:60,price:'£30',status:'pending',paymentStatus:'prepaid'}));const sent=[],original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{sent.push(JSON.parse(options.body));return new Response('{}',{status:200})};t.after(()=>globalThis.fetch=original);let response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed',adminNotes:'Paid'}),env});assert.equal(response.status,200);assert.equal(sent.length,1);assert.match(sent[0].subject,/confirmed/i);assert.match(sent[0].html,/additional time.*billed after/i);response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed',adminNotes:'Updated'}),env});assert.equal(response.status,200);assert.equal(sent.length,1)});

test('unpaid booking cannot be confirmed',async()=>{const{env,values}=setup(),key='booking:2026-08-20:11:00';values.set(key,JSON.stringify({reference:'VIP-UNPAID',status:'pending',paymentStatus:'payment-required'}));const response=await updateBooking({request:request('https://example.test/api/admin/bookings',{key,status:'confirmed'}),env});assert.equal(response.status,409);assert.match((await response.json()).error,/Advance payment/)});

test('Engineer Partner can maintain separate home and remote availability',async()=>{const{env,values}=setup(),home={monday:[['09:00','12:00']]},remote={monday:[['13:00','18:00']]},body={homeVisitWeekly:home,remoteWeekly:remote,blockedDates:['2026-08-24'],overrides:[]};let response=await saveAvailability({request:request('https://example.test/api/admin/availability',body),env});assert.equal(response.status,200);assert.ok(values.has('availability:andover:dan-stevens'));response=await getAvailability({request:new Request('https://example.test/api/admin/availability',{headers:{'x-admin-password':'secret'}}),env});const data=await response.json();assert.deepEqual(data.homeVisitWeekly,home);assert.deepEqual(data.remoteWeekly,remote);assert.deepEqual(data.blockedDates,['2026-08-24'])});
