import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {operatorCompliance,operatorCanReceiveWork} from '../functions/_shared/compliance.js';
import {onRequestGet} from '../functions/api/admin/compliance.js';

function complete(overrides={}){return{id:'alex',name:'Alex',status:'active',territoryIds:['andover'],trainingStatus:'complete',dbsStatus:'verified',dbsRenewalDate:'2027-01-01',photoStatus:'approved',agreementStatus:'signed',insuranceStatus:'verified',insuranceExpiryDate:'2027-01-01',...overrides}}
test('work authorisation is derived from every required compliance control',()=>{let result=operatorCompliance(complete(),new Date('2026-08-10T12:00:00Z'));assert.equal(result.workAuthorised,true);assert.equal(result.status,'current');result=operatorCompliance(complete({trainingStatus:'in-progress'}),new Date('2026-08-10T12:00:00Z'));assert.equal(result.workAuthorised,false);assert.equal(result.status,'blocked');assert.ok(result.checks.some(item=>item.id==='training'&&item.status==='missing'))});
test('DBS and insurance expiry warnings are automatic and time based',()=>{const result=operatorCompliance(complete({dbsRenewalDate:'2026-09-01',insuranceExpiryDate:'2026-08-09'}),new Date('2026-08-10T12:00:00Z'));assert.equal(result.workAuthorised,false);assert.equal(result.checks.find(item=>item.id==='dbs').status,'expiring');assert.equal(result.checks.find(item=>item.id==='insurance').status,'expired')});
test('HQ can suspend one service without removing the other authorisation',()=>{const operator=complete({homeSuspended:true}),result=operatorCompliance(operator,new Date('2026-08-10T12:00:00Z'));assert.equal(result.workAuthorised,true);assert.deepEqual(result.capabilities,{home:false,remote:true});assert.equal(operatorCanReceiveWork(operator,new Date('2026-08-10T12:00:00Z'),'home'),false);assert.equal(operatorCanReceiveWork(operator,new Date('2026-08-10T12:00:00Z'),'remote'),true)});
test('HQ receives a network compliance summary',async()=>{const values=new Map([['operator:alex',JSON.stringify(complete())],['operator:blocked',JSON.stringify(complete({id:'blocked',name:'Blocked',photoStatus:'under-review'}))]]),env={ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}},request=new Request('https://example.test/api/admin/compliance',{headers:{'x-admin-password':'secret'}}),data=await(await onRequestGet({request,env})).json();assert.equal(data.summary.total,2);assert.equal(data.summary.authorised,1);assert.equal(data.summary.blocked,1)});
test('franchise workspace loads compliance oversight and caches it for the OS',()=>{const tools=fs.readFileSync('admin/franchise-tools.js','utf8'),ui=fs.readFileSync('admin/compliance.js','utf8'),worker=fs.readFileSync('admin/service-worker.js','utf8');assert.match(tools,/compliance\.js/);assert.match(tools,/Suspend home visits/);assert.match(tools,/Suspend remote support/);assert.match(ui,/work-authorisation checks/i);assert.match(worker,/compliance\.js/)});
