import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {onRequestPost as requestCode} from '../functions/api/account/auth/request.js';
import {onRequestPost as verifyCode} from '../functions/api/account/auth/verify.js';
import {onRequestGet as overview} from '../functions/api/account/overview.js';
import {onRequestPost as grantAccess,onRequestDelete as revokeAccess} from '../functions/api/account/delegated-access.js';
function setup(){const values=new Map();return{values,env:{RESEND_API_KEY:'test',BOOKING_FROM_EMAIL:'VIPOAP <help@example.test>',VIPOAP_DATA:{async get(k,t){const v=values.get(k);return t==='json'&&v?JSON.parse(v):v??null},async put(k,v){values.set(k,v)},async delete(k){values.delete(k)},async list({prefix}){return{keys:[...values.keys()].filter(k=>k.startsWith(prefix)).map(name=>({name}))}}}}}}
const request=(url,method='GET',body,token)=>new Request(url,{method,headers:{'content-type':'application/json',...(token?{'x-customer-session':token}:{})},body:body?JSON.stringify(body):undefined});
test('customer can securely sign in and view only their account overview',async t=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Margaret',email:'margaret@example.test',phone:'01234',postcode:'SP10',membershipPlan:'support',membershipStatus:'active'}));values.set('booking:one',JSON.stringify({customerId:'customer:one',date:'2026-08-20',time:'10:00'}));values.set('booking:other',JSON.stringify({customerId:'customer:other',date:'2026-08-20',time:'11:00'}));let sent,original=globalThis.fetch;globalThis.fetch=async(_u,o)=>{sent=JSON.parse(o.body);return new Response('{}',{status:200})};t.after(()=>globalThis.fetch=original);let response=await requestCode({request:request('https://example.test/api/account/auth/request','POST',{email:'margaret@example.test'}),env});assert.equal(response.status,200);const code=sent.html.match(/>(\d{6})</)[1];response=await verifyCode({request:request('https://example.test/api/account/auth/verify','POST',{email:'margaret@example.test',code}),env});const login=await response.json();assert.match(login.token,/^vcs_/);response=await overview({request:request('https://example.test/api/account/overview','GET',null,login.token),env});const data=await response.json();assert.equal(data.customer.name,'Margaret');assert.equal(data.appointments.length,1);assert.equal(data.entitlement.minutesRemaining,30)});
test('delegated permissions are granular and revocable by the customer',async()=>{const{env,values}=setup();values.set('customer-session:test',JSON.stringify({customerId:'customer:one'}));const cryptoModule=await import('../functions/_shared/admin-auth.js'),token='session',digest=await cryptoModule.digest(token);values.set(`customer-session:${digest}`,JSON.stringify({customerId:'customer:one',expiresAt:new Date(Date.now()+86400000).toISOString()}));let response=await grantAccess({request:request('https://example.test/api/account/delegated-access','POST',{delegateCustomerId:'customer:two',permissions:['book','view_history','invalid']},token),env});const data=await response.json();assert.deepEqual(data.grant.permissions,['book','view_history']);response=await revokeAccess({request:request(`https://example.test/api/account/delegated-access?key=${encodeURIComponent(data.key)}`,'DELETE',null,token),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get(data.key)).status,'revoked')});
test('customer PWA exposes account sign-in and core overview areas',()=>{const account=fs.readFileSync(new URL('../app/account.html',import.meta.url),'utf8'),home=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8'),worker=fs.readFileSync(new URL('../app/service-worker.js',import.meta.url),'utf8');assert.match(account,/six-digit code/i);assert.match(account,/Membership/);assert.match(account,/Family permissions/);assert.match(account,/Appointments/);assert.match(account,/Equipment/);assert.match(home,/account-link\.js/);assert.match(worker,/vipoap-app-v8/);assert.match(worker,/\/app\/account/)});
