import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {digest} from '../functions/_shared/admin-auth.js';
import {onRequestPost as requestAppointment} from '../functions/api/account/appointment-request.js';
import {onRequestPost as requestMembership} from '../functions/api/account/membership-request.js';
import {onRequestGet as downloadReceipt} from '../functions/api/account/receipt.js';
import {onRequestPost as grantAccess,onRequestDelete as revokeAccess} from '../functions/api/account/delegated-access.js';
function setup(){const values=new Map();return{values,env:{VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}}}}}
async function authenticated(env,values,body={},url='https://example.test/api/account/action',method='POST'){const token='customer-session',customerId='customer:one';values.set(`customer-session:${await digest(token)}`,JSON.stringify({customerId,email:'pat@example.test',expiresAt:new Date(Date.now()+86400000).toISOString()}));return new Request(url,{method,headers:{'content-type':'application/json','x-customer-session':token},body:method==='GET'?undefined:JSON.stringify(body)})}
test('customer appointment changes create an HQ request without changing the confirmed booking',async()=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Pat',email:'pat@example.test',preferredContact:'Email'}));values.set('booking:future',JSON.stringify({customerId:'customer:one',reference:'VIP-FUTURE',date:'2026-10-10',time:'10:00',bookingStatus:'confirmed',paymentStatus:'prepaid'}));const response=await requestAppointment({request:await authenticated(env,values,{bookingKey:'booking:future',requestType:'change',details:'Tuesday afternoon'}),env}),data=await response.json(),booking=JSON.parse(values.get('booking:future'));assert.equal(response.status,200);assert.equal(booking.bookingStatus,'confirmed');assert.equal(booking.paymentStatus,'prepaid');assert.equal(booking.customerRequestStatus,'received');assert.ok([...values.keys()].some(key=>key.startsWith('help-request:')));assert.match(data.reference,/^HELP-/)});
test('customer cannot request changes to somebody else’s booking',async()=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Pat',email:'pat@example.test'}));values.set('booking:other',JSON.stringify({customerId:'customer:two',bookingStatus:'confirmed'}));const response=await requestAppointment({request:await authenticated(env,values,{bookingKey:'booking:other',requestType:'cancel'}),env});assert.equal(response.status,404)});
test('membership changes enter the existing HQ help queue and do not alter entitlement',async()=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Pat',email:'pat@example.test',membershipPlan:'support',membershipStatus:'active'}));const response=await requestMembership({request:await authenticated(env,values,{action:'cancel',note:'At the end of this month'}),env}),data=await response.json(),customer=JSON.parse(values.get('customer:one'));assert.equal(response.status,200);assert.equal(customer.membershipPlan,'support');assert.equal(customer.membershipStatus,'active');assert.equal(customer.membershipRequestStatus,'received');assert.match(data.reference,/^HELP-/)});
test('customer downloads only their own printable invoice',async()=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Pat',email:'pat@example.test',postcode:'SP10'}));values.set('invoice:one',JSON.stringify({customerId:'customer:one',number:'INV-ONE',issueDate:'2026-09-01',dueDate:'2026-09-15',status:'paid',total:49,lines:[{description:'Home visit',quantity:1,unitPrice:49,total:49}]}));values.set('invoice:other',JSON.stringify({customerId:'customer:two',number:'INV-OTHER',total:99}));let response=await downloadReceipt({request:await authenticated(env,values,{},'https://example.test/api/account/receipt?key=invoice%3Aone','GET'),env});assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/INV-ONE/);assert.match(await response.text(),/Home visit/);response=await downloadReceipt({request:await authenticated(env,values,{},'https://example.test/api/account/receipt?key=invoice%3Aother','GET'),env});assert.equal(response.status,404)});
test('family access can be granted by account email and revoked by its owner',async()=>{const{env,values}=setup();values.set('customer:one',JSON.stringify({name:'Pat',email:'pat@example.test'}));values.set('customer:two',JSON.stringify({name:'Alex',email:'alex@example.test'}));let response=await grantAccess({request:await authenticated(env,values,{delegateEmail:'alex@example.test',permissions:['book','view_history','invalid']}),env}),data=await response.json();assert.equal(response.status,201);assert.equal(data.grant.delegateCustomerId,'customer:two');assert.deepEqual(data.grant.permissions,['book','view_history']);response=await revokeAccess({request:await authenticated(env,values,{},`https://example.test/api/account/delegated-access?key=${encodeURIComponent(data.key)}`,'DELETE'),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get(data.key)).status,'revoked')});
test('customer portal presents stable navigation and accessible account controls',()=>{const page=fs.readFileSync('app/account.html','utf8'),css=fs.readFileSync('app/account.css','utf8'),script=fs.readFileSync('app/account.js','utf8');assert.match(page,/aria-label="My VIPOAP sections"/);assert.equal((page.match(/data-view=/g)||[]).length,8);assert.match(page,/download a printable copy/i);assert.match(script,/Your booking remains unchanged until we confirm it/i);assert.match(css,/@media\(max-width:650px\)/);assert.match(css,/\.account-view\.active\{display:block\}/);assert.match(script,/vipoapCustomerSession/)});
