import test from 'node:test';import assert from 'node:assert/strict';import {onRequestGet,onRequestPost,onRequestPatch} from '../functions/api/admin/customers.js';import {onRequestGet as exportData} from '../functions/api/admin/export.js';
function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(x=>x.startsWith(prefix)).map(name=>({name}))}}}}}}
const req=(method,body,url='https://example.test/api/admin/customers',password='secret')=>new Request(url,{method,headers:{'content-type':'application/json','x-admin-password':password},body:body?JSON.stringify(body):undefined});
const customer={name:'Margaret Test',phone:'01234 567890',email:'m@example.test',postcode:'SP10 1AA',membership:'monthly',equipment:[{type:'Router',brand:'Example',model:'R1',status:'Working well',upgradePriority:'Worth considering',upgradeRecommendation:'Replace when support ends'}],attachments:[]};
test('protects customer records',async()=>{const{env}=setup();assert.equal((await onRequestGet({request:req('GET',null,undefined,'wrong'),env})).status,401)});
test('creates, lists and updates a customer with equipment',async()=>{const{env}=setup();const made=await (await onRequestPost({request:req('POST',customer),env})).json();assert.ok(made.key.startsWith('customer:'));const listed=await (await onRequestGet({request:req('GET'),env})).json();assert.equal(listed.customers[0].equipment[0].type,'Router');const changed=await onRequestPatch({request:req('PATCH',{...customer,key:made.key,customerNotes:'Prefers afternoon calls.'}),env});assert.equal(changed.status,200);assert.equal((await env.VIPOAP_DATA.get(made.key,'json')).customerNotes,'Prefers afternoon calls.')});
test('rejects oversized attachments',async()=>{const{env}=setup();const response=await onRequestPost({request:req('POST',{...customer,attachments:[{name:'large.jpg',size:2097153,data:'data:image/jpeg;base64,abc'}]}),env});assert.equal(response.status,200);const saved=await env.VIPOAP_DATA.get((await response.json()).key,'json');assert.equal(saved.attachments.length,0)});
test('exports Zoho-ready customer CSV',async()=>{const{env}=setup();await onRequestPost({request:req('POST',customer),env});const response=await exportData({request:req('GET',null,'https://example.test/api/admin/export?type=customers'),env});assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/customers/);assert.match(await response.text(),/Margaret Test/)});
test('uses the agreed Support and Family membership prices',async()=>{const{env}=setup();const made=await(await onRequestPost({request:req('POST',{...customer,membership:'support'}),env})).json();const saved=await env.VIPOAP_DATA.get(made.key,'json');assert.equal(saved.membershipPlan,'support');assert.equal(saved.membershipMonthlyPrice,7.99);assert.equal(saved.membershipAnnualPrice,79);const changed=await onRequestPatch({request:req('PATCH',{...saved,key:made.key,membershipPlan:'family',membershipMonthlyPrice:0,membershipAnnualPrice:0}),env});assert.equal(changed.status,200);const family=await env.VIPOAP_DATA.get(made.key,'json');assert.equal(family.membershipMonthlyPrice,12.99);assert.equal(family.membershipAnnualPrice,129)});
test('exports Zoho Books finance datasets',async()=>{const{env}=setup();await onRequestPost({request:req('POST',{...customer,membership:'support'}),env});await env.VIPOAP_DATA.put('credit:one',JSON.stringify({customerId:'customer:one',amount:5,source:'referral',status:'available'}));for(const type of ['memberships','payments','credits','settlements','equipment-funds','refunds']){const response=await exportData({request:req('GET',null,`https://example.test/api/admin/export?type=${type}`),env});assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),new RegExp(type))}});
