import test from 'node:test';import assert from 'node:assert/strict';
import {onRequestPost as createRole,onRequestGet as listRoles} from '../functions/api/admin/roles.js';
import {onRequestPost as uploadDbs,onRequestGet as getDbs} from '../functions/api/admin/operator-dbs.js';
import {onRequestGet as getTraining,onRequestPatch as saveProgress} from '../functions/api/admin/training.js';
import {onRequestPost as createFollowup,onRequestGet as listFollowups,onRequestPatch as closeFollowup} from '../functions/api/admin/followups.js';
function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const v=values.get(key);return type==='json'&&v?JSON.parse(v):v??null},async put(key,v){values.set(key,v)},async list({prefix}){return{keys:[...values.keys()].filter(x=>x.startsWith(prefix)).map(name=>({name}))}}}}}}
const req=(method,body,url='https://example.test/api/admin/test')=>new Request(url,{method,headers:{'content-type':'application/json','x-admin-password':'secret'},body:body?JSON.stringify(body):undefined});
test('creates a granular custom role',async()=>{const{env}=setup();const response=await createRole({request:req('POST',{name:'Territory manager',permissions:['view_dashboard','manage_calls','manage_training']}),env});assert.equal(response.status,200);const data=await(await listRoles({request:req('GET'),env})).json();assert.ok(data.roles.some(x=>x.id==='territory-manager'));assert.ok(data.permissions.includes('manage_dbs'))});
test('uploads and protects an operator DBS document',async()=>{const{env,values}=setup();values.set('operator:test',JSON.stringify({id:'test',name:'Test',territoryIds:['andover']}));const data=btoa('test pdf');const uploaded=await uploadDbs({request:req('POST',{operatorId:'test',name:'check.pdf',type:'application/pdf',size:8,data}),env});assert.equal(uploaded.status,200);const listed=await(await getDbs({request:req('GET',null,'https://example.test/api/admin/operator-dbs?operatorId=test'),env})).json();assert.equal(listed.documents.length,1);assert.equal(listed.documents[0].name,'check.pdf');assert.equal((await env.VIPOAP_DATA.get('operator:test','json')).dbsStatus,'verified')});
test('training completion and score come only from a server-marked assessment',async()=>{const{env,values}=setup();values.set('operator:dan-stevens',JSON.stringify({id:'dan-stevens',name:'Engineer',territoryIds:['andover']}));const initial=await(await getTraining({request:req('GET',null,'https://example.test/api/admin/training?operatorId=dan-stevens'),env})).json();assert.ok(initial.courses.length>=10);assert.equal(initial.courses[0].questions[0].correctIndex,undefined);let saved=await saveProgress({request:req('PATCH',{operatorId:'dan-stevens',courseId:initial.courses[0].id,status:'complete',score:100}),env});assert.equal(saved.status,400);saved=await saveProgress({request:req('PATCH',{operatorId:'dan-stevens',courseId:initial.courses[0].id,answers:[0]}),env});assert.equal(saved.status,200);const record=await env.VIPOAP_DATA.get(`training-progress:dan-stevens:${initial.courses[0].id}`,'json');assert.equal(record.status,'complete');assert.equal(record.score,100);assert.equal(record.attempts.length,1)});
test('HQ cannot complete an assessment on behalf of another engineer',async()=>{const{env,values}=setup();values.set('operator:test',JSON.stringify({id:'test',name:'Test',territoryIds:['andover']}));const response=await saveProgress({request:req('PATCH',{operatorId:'test',courseId:'brand-promise',answers:[0]}),env});assert.equal(response.status,403);assert.equal(values.has('training-progress:test:brand-promise'),false)});
test('attaches and completes a follow-up against a completed call',async()=>{const{env}=setup();const created=await(await createFollowup({request:req('POST',{relatedKey:'callout:one',reference:'CO-ONE',customerName:'Customer',territoryId:'andover',dueDate:'2026-08-20',notes:'Check Wi-Fi stability'}),env})).json();let data=await(await listFollowups({request:req('GET'),env})).json();assert.equal(data.followups.length,1);const closed=await closeFollowup({request:req('PATCH',{key:created.key,status:'complete',outcome:'Customer confirmed stable'}),env});assert.equal(closed.status,200);data=await(await listFollowups({request:req('GET'),env})).json();assert.equal(data.followups[0].status,'complete')});

