import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {onRequestPost as createRole,onRequestGet as listRoles} from '../functions/api/admin/roles.js';
import {onRequestPost as uploadDbs,onRequestGet as getDbs} from '../functions/api/admin/operator-dbs.js';
import {onRequestGet as getTraining,onRequestPut as completeModule,onRequestPatch as saveProgress} from '../functions/api/admin/training.js';
import {onRequestPost as createFollowup,onRequestGet as listFollowups,onRequestPatch as closeFollowup} from '../functions/api/admin/followups.js';
function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const v=values.get(key);return type==='json'&&v?JSON.parse(v):v??null},async put(key,v){values.set(key,v)},async list({prefix}){return{keys:[...values.keys()].filter(x=>x.startsWith(prefix)).map(name=>({name}))}}}}}}
const req=(method,body,url='https://example.test/api/admin/test')=>new Request(url,{method,headers:{'content-type':'application/json','x-admin-password':'secret'},body:body?JSON.stringify(body):undefined});
test('creates a granular custom role',async()=>{const{env}=setup();const response=await createRole({request:req('POST',{name:'Territory manager',permissions:['view_dashboard','manage_calls','manage_training']}),env});assert.equal(response.status,200);const data=await(await listRoles({request:req('GET'),env})).json();assert.ok(data.roles.some(x=>x.id==='territory-manager'));assert.ok(data.permissions.includes('manage_dbs'))});
test('uploads and protects an operator DBS document',async()=>{const{env,values}=setup();values.set('operator:test',JSON.stringify({id:'test',name:'Test',territoryIds:['andover']}));const data=btoa('test pdf');const uploaded=await uploadDbs({request:req('POST',{operatorId:'test',name:'check.pdf',type:'application/pdf',size:8,data}),env});assert.equal(uploaded.status,200);const listed=await(await getDbs({request:req('GET',null,'https://example.test/api/admin/operator-dbs?operatorId=test'),env})).json();assert.equal(listed.documents.length,1);assert.equal(listed.documents[0].name,'check.pdf');assert.equal((await env.VIPOAP_DATA.get('operator:test','json')).dbsStatus,'verified')});
test('training completion and score come only after tracked modules and a server-marked assessment',async()=>{const{env,values}=setup();values.set('operator:dan-stevens',JSON.stringify({id:'dan-stevens',name:'Engineer',territoryIds:['andover'],trainingStatus:'not-started'}));const initial=await(await getTraining({request:req('GET',null,'https://example.test/api/admin/training?operatorId=dan-stevens'),env})).json(),course=initial.courses[0];assert.ok(initial.courses.length>=10);assert.equal(course.questions.length,10);assert.equal(course.questions[0].correctIndex,undefined);let saved=await saveProgress({request:req('PATCH',{operatorId:'dan-stevens',courseId:course.id,status:'complete',score:100}),env});assert.equal(saved.status,400);saved=await saveProgress({request:req('PATCH',{operatorId:'dan-stevens',courseId:course.id,answers:[0,1,2,0,1,0,1,2,0,1]}),env});assert.equal(saved.status,409);for(let lessonIndex=0;lessonIndex<course.lessons.length;lessonIndex++)assert.equal((await completeModule({request:req('PUT',{operatorId:'dan-stevens',courseId:course.id,lessonIndex}),env})).status,200);saved=await saveProgress({request:req('PATCH',{operatorId:'dan-stevens',courseId:course.id,answers:[0,1,2,0,1,0,1,2,0,1]}),env});assert.equal(saved.status,200);const record=await env.VIPOAP_DATA.get(`training-progress:dan-stevens:${course.id}`,'json'),operator=await env.VIPOAP_DATA.get('operator:dan-stevens','json');assert.equal(record.status,'complete');assert.equal(record.moduleProgress,100);assert.equal(record.score,100);assert.equal(record.attempts.length,1);assert.equal(operator.trainingStatus,'in-progress')});
test('training UI saves each lesson immediately and displays the real question count',()=>{const ui=fs.readFileSync(new URL('../admin/training-learning.js',import.meta.url),'utf8'),page=fs.readFileSync(new URL('../admin/training.html',import.meta.url),'utf8');assert.match(ui,/Mark lesson complete and continue/);assert.match(ui,/data-complete-lesson/);assert.match(ui,/method:'PUT'/);assert.match(ui,/questionItems\.length/);assert.doesNotMatch(ui,/Answer all \$\{questions\.length\}/);assert.match(page,/\.question-list/);assert.match(page,/\.lesson-step\.current/)});
test('HQ receives an all-engineer training overview with module scores and progress',async()=>{const{env,values}=setup();values.set('operator:alex',JSON.stringify({id:'alex',name:'Alex Engineer',email:'alex@example.test',role:'operator',status:'active',territoryIds:['andover'],trainingStatus:'in-progress'}));values.set('training-progress:alex:brand-promise',JSON.stringify({operatorId:'alex',courseId:'brand-promise',status:'complete',moduleProgress:100,completedLessonIndexes:[0,1,2,3,4],score:90,attempts:[{score:70},{score:90}],updatedAt:'2026-09-01T10:00:00Z'}));const response=await getTraining({request:req('GET',null,'https://example.test/api/admin/training?overview=1'),env}),data=await response.json();assert.equal(response.status,200);assert.equal(data.summary.engineers,1);assert.equal(data.summary.assessmentsPassed,1);assert.equal(data.engineers[0].overallProgress>0,true);const module=data.engineers[0].modules.find(item=>item.id==='brand-promise');assert.equal(module.score,90);assert.equal(module.attempts,2);assert.equal(module.completedLessons,5)});
test('training page exposes a clear administrator progress and scoring dashboard',()=>{const page=fs.readFileSync(new URL('../admin/training.html',import.meta.url),'utf8'),admin=fs.readFileSync(new URL('../admin/training-admin.js',import.meta.url),'utf8');assert.match(page,/training-admin\.js\?v=1/);assert.match(admin,/ADMIN TRAINING CONTROL/);assert.match(admin,/Engineer progress and scores/);assert.match(admin,/engineer-list/);assert.match(admin,/Assessment.*passed/i);assert.match(admin,/View learning plan/);assert.match(admin,/dataset\.requiresPermission='manage_training'/)});
test('network management presents scrollable territories, portal users and roles with direct actions',()=>{const page=fs.readFileSync(new URL('../admin/franchise.html',import.meta.url),'utf8'),tools=fs.readFileSync(new URL('../admin/franchise-tools.js',import.meta.url),'utf8');assert.match(page,/franchise-tools\.js\?v=2/);assert.match(tools,/Territories, people and access roles/);assert.match(tools,/directory-list/);assert.match(tools,/overflow:auto/);assert.match(tools,/data-edit-territory/);assert.match(tools,/data-edit-operator/);assert.match(tools,/data-edit-role/);assert.match(tools,/method:'PATCH'/);assert.match(tools,/built-in role is protected/i)});
test('HQ cannot complete an assessment on behalf of another engineer',async()=>{const{env,values}=setup();values.set('operator:test',JSON.stringify({id:'test',name:'Test',territoryIds:['andover']}));const response=await saveProgress({request:req('PATCH',{operatorId:'test',courseId:'brand-promise',answers:[0,1,2,0,1,0,1,2,0,1]}),env});assert.equal(response.status,403);assert.equal(values.has('training-progress:test:brand-promise'),false)});
test('attaches and completes a follow-up against a completed call',async()=>{const{env}=setup();const created=await(await createFollowup({request:req('POST',{relatedKey:'callout:one',reference:'CO-ONE',customerName:'Customer',territoryId:'andover',dueDate:'2026-08-20',notes:'Check Wi-Fi stability'}),env})).json();let data=await(await listFollowups({request:req('GET'),env})).json();assert.equal(data.followups.length,1);const closed=await closeFollowup({request:req('PATCH',{key:created.key,status:'complete',outcome:'Customer confirmed stable'}),env});assert.equal(closed.status,200);data=await(await listFollowups({request:req('GET'),env})).json();assert.equal(data.followups[0].status,'complete')});

