import test from 'node:test';import assert from 'node:assert/strict';
import {onRequestGet,onRequestPost} from '../functions/api/help-requests.js';
import {onRequestGet as adminGet,onRequestPatch as adminPatch} from '../functions/api/admin/help-requests.js';

function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async delete(key){values.delete(key)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name})),list_complete:true}}}}}}
const request=(url,body,headers={})=>new Request(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});

test('creates a private help request and lets the customer continue the conversation',async()=>{const{env}=setup();let response=await onRequestPost({request:request('https://vipoap.test/api/help-requests',{name:'Margaret',email:'margaret@example.test',contactPreference:'Email',category:'device',description:'My tablet keeps showing a message.'},{'CF-Connecting-IP':'192.0.2.1'}),env}),created=await response.json();assert.equal(response.status,200);assert.match(created.reference,/^HELP-\d{8}$/);const access=new URL(created.statusUrl).searchParams.get('access');response=await onRequestGet({request:new Request(`https://vipoap.test/api/help-requests?access=${access}`),env});let view=await response.json();assert.equal(view.statusLabel,'We have received your request.');assert.equal(view.messages.length,1);response=await onRequestPost({request:request(`https://vipoap.test/api/help-requests?access=${access}`,{message:'It appeared again today.'},{'CF-Connecting-IP':'192.0.2.1'}),env});assert.equal(response.status,200);response=await onRequestGet({request:new Request(`https://vipoap.test/api/help-requests?access=${access}`),env});view=await response.json();assert.equal(view.messages.length,2)});

test('does not reveal a help request without its private access token',async()=>{const{env}=setup();const response=await onRequestGet({request:new Request('https://vipoap.test/api/help-requests'),env});assert.equal(response.status,404)});

test('admin queue requires permission and can update status and reply',async()=>{const{env,values}=setup(),key='help-request:2026-08-10:HELP-08101234';values.set(key,JSON.stringify({reference:'HELP-08101234',name:'Margaret',email:'',phone:'01234',contactPreference:'Phone',territoryId:'andover',status:'received',messages:[],createdAt:'2026-08-10T10:00:00.000Z',updatedAt:'2026-08-10T10:00:00.000Z'}));let response=await adminGet({request:new Request('https://vipoap.test/api/admin/help-requests'),env});assert.equal(response.status,401);response=await adminGet({request:new Request('https://vipoap.test/api/admin/help-requests',{headers:{'x-admin-password':'secret'}}),env});let data=await response.json();assert.equal(data.requests.length,1);response=await adminPatch({request:new Request('https://vipoap.test/api/admin/help-requests',{method:'PATCH',headers:{'content-type':'application/json','x-admin-password':'secret'},body:JSON.stringify({key,status:'looking',message:'We are checking this now.'})}),env});assert.equal(response.status,200);const saved=JSON.parse(values.get(key));assert.equal(saved.status,'looking');assert.equal(saved.messages[0].author,'VIPOAP')});

test('validates contact details and plain-language description',async()=>{const{env}=setup();const response=await onRequestPost({request:request('https://vipoap.test/api/help-requests',{name:'Margaret',contactPreference:'Email',description:''},{'CF-Connecting-IP':'192.0.2.2'}),env});assert.equal(response.status,400)});
