import test from 'node:test';
import assert from 'node:assert/strict';
import {applyMembershipPricing,providerEligible,resolveBookingPricing,resolveBookingPricingFromEnvironment,resolveBookingService} from '../functions/_shared/marketplace.js';

test('maps legacy Technology labels to stable service IDs',()=>{const result=resolveBookingService({service:'General Technology Help',supportType:'Home visit',duration:60});assert.equal(result.categoryId,'technology');assert.equal(result.serviceId,'tech-general');assert.equal(result.fulfilmentType,'home')});
test('records future fulfilment rules without breaking legacy booking combinations',()=>{const result=resolveBookingService({service:'Wi-Fi / internet',supportType:'Remote support',duration:60});assert.equal(result.serviceId,'tech-wifi');assert.equal(result.fulfilmentType,'remote');assert.equal(result.fulfilmentSupported,false)});
test('uses the active Technology marketplace pricing fallback',()=>{assert.deepEqual(resolveBookingPricing({supportType:'Home visit',duration:30}),{pricingRuleId:'technology-home-30',billingModel:'time_blocks',currency:'GBP',customerPence:4900,providerEntitlementPence:2500,platformFeePence:2400,price:'£49',source:'active-config'});assert.deepEqual(resolveBookingPricing({supportType:'Home visit',duration:60}),{pricingRuleId:'technology-home-60',billingModel:'time_blocks',currency:'GBP',customerPence:7900,providerEntitlementPence:4500,platformFeePence:3400,price:'£79',source:'active-config'});assert.deepEqual(resolveBookingPricing({supportType:'Remote support',duration:30}),{pricingRuleId:'technology-remote-30',billingModel:'fixed',currency:'GBP',customerPence:2500,providerEntitlementPence:1750,platformFeePence:750,price:'£25',source:'active-config'});assert.deepEqual(resolveBookingPricing({supportType:'Remote support',duration:60}),{pricingRuleId:'technology-remote-60',billingModel:'fixed',currency:'GBP',customerPence:4500,providerEntitlementPence:3150,platformFeePence:1350,price:'£45',source:'active-config'});assert.equal(resolveBookingPricing({supportType:'Remote support',duration:90}).providerEntitlementPence,4550)});
test('active members receive the sustainable remote rate with a 70 percent provider share',async()=>{const env={VIPOAP_DATA:{async get(){return null}}},standard=resolveBookingPricing({supportType:'Remote support',duration:60}),member=await applyMembershipPricing(env,standard,{membershipPlan:'support',membershipStatus:'active'},{supportType:'Remote support',duration:60});assert.equal(member.pricingRuleId,'technology-remote-member-60');assert.equal(member.customerPence,4000);assert.equal(member.providerEntitlementPence,2800);assert.equal(member.platformFeePence,1200);assert.equal(member.price,'£40');assert.equal(member.source,'membership')});
test('uses a D1 time-block pricing rule when one is active',async()=>{const row={id:'technology-home-local',billing_model:'time_blocks',currency:'GBP',customer_base_pence:4900,customer_increment_pence:3000,base_minutes:30,increment_minutes:30,provider_base_pence:2500,provider_increment_pence:2000,platform_fee_mode:'derived',platform_fee_value:0},env={VIPOAP_DB:{prepare(){return{bind(){return{async first(){return row}}}}}}},price=await resolveBookingPricingFromEnvironment(env,{categoryId:'technology',serviceId:'tech-computer',supportType:'Home visit',duration:60,territoryId:'andover'});assert.equal(price.source,'d1');assert.equal(price.customerPence,7900);assert.equal(price.providerEntitlementPence,4500);assert.equal(price.platformFeePence,3400);assert.equal(price.price,'£79')});
test('a stale founding D1 rule cannot override the release-managed live price',async()=>{const row={id:'technology-home-standard',billing_model:'time_blocks',currency:'GBP',customer_base_pence:6400,customer_increment_pence:2000,base_minutes:60,increment_minutes:30,provider_base_pence:4000,provider_increment_pence:1500,platform_fee_mode:'derived',platform_fee_value:0},env={VIPOAP_DB:{prepare(){return{bind(){return{async first(){return row}}}}}}},price=await resolveBookingPricingFromEnvironment(env,{categoryId:'technology',serviceId:'tech-general',supportType:'Home visit',duration:60,territoryId:'andover'});assert.equal(price.customerPence,7900);assert.equal(price.providerEntitlementPence,4500);assert.equal(price.source,'active-config')});
test('a stale founding remote D1 rule cannot override the 70 percent engineer share',async()=>{const row={id:'technology-remote-standard',billing_model:'time_blocks',currency:'GBP',customer_base_pence:2500,customer_increment_pence:2000,base_minutes:30,increment_minutes:30,provider_base_pence:0,provider_increment_pence:0,platform_fee_mode:'derived',platform_fee_value:0},env={VIPOAP_DB:{prepare(){return{bind(){return{async first(){return row}}}}}}},price=await resolveBookingPricingFromEnvironment(env,{categoryId:'technology',serviceId:'tech-general',supportType:'Remote support',duration:60,territoryId:'andover'});assert.equal(price.customerPence,4500);assert.equal(price.providerEntitlementPence,3150);assert.equal(price.platformFeePence,1350);assert.equal(price.source,'active-config')});
test('legacy providers remain eligible using existing serviceTypes',()=>{assert.equal(providerEligible({serviceTypes:['home']},{serviceId:'tech-general',fulfilmentType:'home',postcode:'SP10 1AA',territoryId:'andover'}),true);assert.equal(providerEligible({serviceTypes:['home']},{serviceId:'tech-general',fulfilmentType:'remote',postcode:'SP10 1AA',territoryId:'andover'}),false)});
test('future-ready provider records can restrict service and postcode',()=>{const provider={serviceTypes:['home'],providerServices:[{serviceId:'tech-wifi',status:'approved'}],serviceAreas:[{territoryId:'andover',serviceId:'tech-wifi',fulfilmentType:'home',postcodePattern:'SP10',status:'active'}]};assert.equal(providerEligible(provider,{serviceId:'tech-wifi',fulfilmentType:'home',postcode:'SP10 3AB',territoryId:'andover'}),true);assert.equal(providerEligible(provider,{serviceId:'tech-wifi',fulfilmentType:'home',postcode:'SP11 3AB',territoryId:'andover'}),false);assert.equal(providerEligible(provider,{serviceId:'tech-printer',fulfilmentType:'home',postcode:'SP10 3AB',territoryId:'andover'}),false)});
