import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULES,platformRules} from '../functions/_shared/platform-rules.js';
import {initialBookingState,validPaymentMethod} from '../functions/_shared/booking-state.js';
import {onRequestPost as createIncident} from '../functions/api/admin/incidents.js';
import {onRequestPost as consentRecording,onRequestPatch as updateRecording} from '../functions/api/admin/remote-recordings.js';
import {onRequestPost as recordMembershipUsage} from '../functions/api/admin/membership-usage.js';
import {onRequestPost as saveProduct} from '../functions/api/admin/equipment-catalogue.js';
import {onRequestPost as recommendProduct,onRequestPatch as updateRecommendation} from '../functions/api/admin/equipment-recommendations.js';

function setup(){const values=new Map();return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:{async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(x=>x.startsWith(prefix)).map(name=>({name}))}}}}}}
function request(method,body){return new Request('https://example.test',{method,headers:{'content-type':'application/json','x-admin-password':'secret'},body:body?JSON.stringify(body):undefined})}

test('definitive rules contain no membership home-visit discount',async()=>{const{env}=setup();const rules=await platformRules(env);assert.equal(rules.membership.homeVisitDiscount,0);assert.equal(rules.prices.homeFirstHour,30);assert.equal(rules.engineerEntitlements.homeFirstHour,25);assert.equal(DEFAULT_RULES.onboarding.home,69)});

test('booking and payment states remain separate',()=>{assert.deepEqual(initialBookingState({supportType:'Home visit',paymentMethod:'cash'}),{bookingStatus:'requested',paymentStatus:'cash-selected',paymentRequired:false});assert.deepEqual(initialBookingState({supportType:'Remote support',paymentMethod:'online'}),{bookingStatus:'slot-held',paymentStatus:'payment-required',paymentRequired:true});assert.equal(validPaymentMethod('Remote support','cash'),false)});

test('safety stop creates a restricted incident and reviews the booking payment',async()=>{const{env,values}=setup();values.set('booking:one',JSON.stringify({reference:'VIP-ONE',status:'in-progress',paymentStatus:'prepaid'}));const response=await createIncident({request:request('POST',{bookingKey:'booking:one',concernType:'Engineer safety',severity:'high',description:'Threatening behaviour observed.',currentlySafe:true,stopWork:true,paymentReview:true}),env});assert.equal(response.status,201);const data=await response.json();assert.equal(data.incident.restricted,true);const booking=JSON.parse(values.get('booking:one'));assert.equal(booking.status,'safety-stopped');assert.equal(booking.paymentStatus,'review')});

test('remote recording requires consent and supports a pause state',async()=>{const{env}=setup();let response=await consentRecording({request:request('POST',{bookingKey:'booking:remote',consent:false}),env});assert.equal(response.status,409);response=await consentRecording({request:request('POST',{bookingKey:'booking:remote',consent:true,consentMethod:'verbal'}),env});assert.equal(response.status,201);const {key}=await response.json();response=await updateRecording({request:request('PATCH',{key,action:'pause'}),env});assert.equal(response.status,200);assert.equal((await response.json()).record.status,'paused')});

test('membership usage is ledger-based and splits excess paid time',async()=>{const{env,values}=setup(),today=new Date().toISOString().slice(0,10),future=new Date(Date.now()+30*86400000).toISOString().slice(0,10);values.set('customer:member',JSON.stringify({membershipPlan:'support',membershipStatus:'active',currentPeriodStart:today,currentPeriodEnd:future}));let response=await recordMembershipUsage({request:request('POST',{customerId:'customer:member',bookingKey:'booking:remote',minutes:20}),env});assert.equal(response.status,201);let data=await response.json();assert.equal(data.entitlement.minutesRemaining,10);response=await recordMembershipUsage({request:request('POST',{customerId:'customer:member',bookingKey:'booking:remote-two',minutes:25}),env});data=await response.json();assert.equal(data.usage.includedMinutes,10);assert.equal(data.usage.paidMinutes,15);assert.equal(data.entitlement.minutesRemaining,0)});

test('equipment purchases require an approved product and cannot exceed authorisation',async()=>{const{env}=setup();let response=await saveProduct({request:request('POST',{name:'Supported mesh kit',category:'Mesh Wi-Fi',status:'approved'}),env}),productKey=(await response.json()).key;response=await recommendProduct({request:request('POST',{productKey,customerId:'customer:one',price:100,delivery:5,retailer:'Example retailer',reason:'Improve whole-home coverage'}),env});assert.equal(response.status,201);const {key,recommendation}=await response.json();assert.equal(recommendation.total,105);response=await updateRecommendation({request:request('PATCH',{key,status:'purchased',actualCost:110}),env});assert.equal(response.status,409)});
