import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {digest} from '../functions/_shared/admin-auth.js';
import {onRequestGet,onRequestPut,onRequestDelete} from '../functions/api/account/preferred-engineer.js';
import {onRequestPost as book} from '../functions/api/bookings.js';

function setup(){const values=new Map();return{values,env:{RESEND_API_KEY:'test',BOOKING_FROM_EMAIL:'VIPOAP <help@example.test>',VIPOAP_DATA:{async get(k,t){const value=values.get(k);return t==='json'&&value?JSON.parse(value):value??null},async put(k,v){values.set(k,v)},async delete(k){values.delete(k)},async list({prefix}){return{keys:[...values.keys()].filter(k=>k.startsWith(prefix)).map(name=>({name}))}}}}}}
function accountRequest(method='GET',body,token='customer-token'){return new Request('https://example.test/api/account/preferred-engineer',{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined})}
async function customerSession(values){values.set(`customer-session:${await digest('customer-token')}`,JSON.stringify({customerId:'customer:one',expiresAt:new Date(Date.now()+86400000).toISOString()}))}
function nextMonday(){const date=new Date();date.setUTCDate(date.getUTCDate()+((8-date.getUTCDay())%7||7));return date.toISOString().slice(0,10)}

test('customer may only prefer a VIPOAP Engineer who completed their work',async()=>{const{env,values}=setup();await customerSession(values);values.set('customer:one',JSON.stringify({name:'Margaret'}));values.set('operator:known',JSON.stringify({id:'known',name:'Alice Engineer',territoryIds:['andover']}));values.set('operator:other',JSON.stringify({id:'other',name:'Bob Engineer'}));values.set('callout:mine',JSON.stringify({customerId:'customer:one',status:'completed',assignedEngineerId:'known'}));values.set('callout:other',JSON.stringify({customerId:'customer:two',status:'completed',assignedEngineerId:'other'}));let response=await onRequestGet({request:accountRequest(),env}),data=await response.json();assert.deepEqual(data.engineers.map(item=>item.id),['known']);response=await onRequestPut({request:accountRequest('PUT',{engineerId:'other'}),env});assert.equal(response.status,400);response=await onRequestPut({request:accountRequest('PUT',{engineerId:'known'}),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('customer:one')).preferredEngineerId,'known');response=await onRequestDelete({request:accountRequest('DELETE'),env});assert.equal(response.status,200);assert.equal(JSON.parse(values.get('customer:one')).preferredEngineerId,'')});

test('available preferred Engineer is prioritised for a new booking',async t=>{const{env,values}=setup(),date=nextMonday(),weekly={monday:[['19:00','21:00']]};values.set('customer:one',JSON.stringify({name:'Test Customer',phone:'01234 567890',email:'test@example.com',preferredEngineerId:'engineer-two'}));values.set('customer-phone:01234567890','customer:one');for(const id of ['engineer-one','engineer-two']){values.set(`operator:${id}`,JSON.stringify({id,serviceTypes:['home']}));values.set(`availability:andover:${id}`,JSON.stringify({territoryId:'andover',operatorId:id,homeVisitWeekly:weekly,remoteWeekly:{},blockedDates:[]}))}const original=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:202});t.after(()=>globalThis.fetch=original);const request=new Request('https://example.test/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({supportType:'Home visit',service:'General Technology Help',duration:60,date,time:'19:00',name:'Test Customer',phone:'01234 567890',email:'test@example.com',address:'1 Test Street',postcode:'SP10 1AA',notificationChannel:'Email'})}),response=await book({request,env}),result=await response.json();assert.equal(response.status,200);assert.equal(result.preferredEngineerMatched,true);const saved=[...values.entries()].find(([key])=>key.startsWith(`booking:${date}:`));assert.equal(JSON.parse(saved[1]).operatorId,'engineer-two')});

test('customer app explains Preferred Engineer availability and caches the feature',()=>{const feature=fs.readFileSync(new URL('../app/preferred-engineer.js',import.meta.url),'utf8'),loader=fs.readFileSync(new URL('../app/account-health.js',import.meta.url),'utf8'),worker=fs.readFileSync(new URL('../app/service-worker.js',import.meta.url),'utf8');assert.match(feature,/cannot guarantee/i);assert.match(feature,/Book .* again/);assert.match(loader,/preferred-engineer\.js/);assert.match(worker,/vipoap-app-v18/);assert.match(worker,/preferred-engineer\.js/)});
