import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=file=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
test('public site presents the local UK operator model',()=>{const home=read('assets/script.js'),join=read('join-us.html');assert.match(home,/Local people, local support/);assert.match(home,/throughout the UK/);assert.match(join,/run by local people/i);assert.match(join,/Lead volume and income are not guaranteed/);assert.match(join,/four to eight weeks/);assert.match(join,/register/i)});
test('engineer partner pricing protects the engineer payment',()=>{const script=read('assets/script.js'),services=read('services.html'),membership=read('membership.html');assert.match(script,/Customer pays £30/);assert.match(script,/Engineer receives £25/);assert.match(script,/Members pay £25\.50; the engineer still receives £25/);assert.match(script,/No monthly Engineer Partner membership fee/);assert.match(services,/First hour/);assert.match(membership,/15% off standard call-outs/)});
test('family-managed support explains consent and control',()=>{const page=read('family-support.html'),script=read('assets/script.js');assert.match(page,/Trusted local technology help for your parents/);assert.match(page,/parent remains in control/i);assert.match(page,/authorised family contact/);assert.match(script,/For Your Parents/);assert.match(script,/family-support\.html/)});
test('public pages no longer present a named individual as the business',()=>{for(const file of ['index.html','services.html','membership.html','stories.html','contact.html','tips.html','how-it-works.html','app/index.html'])assert.doesNotMatch(read(file),/\bDan\b|About Dan/i)});
test('high contrast mode covers core surfaces and controls',()=>{const css=read('assets/style.css');for(const selector of ['html.contrast body','html.contrast .site-header','html.contrast input','html.contrast .btn-primary','html.contrast footer'])assert.match(css,new RegExp(selector.replace(/[.]/g,'\\.')))});
test('engineer call form can capture and retain on-site photos',()=>{const page=read('admin/index.html'),camera=read('admin/callout-camera.js'),worker=read('admin/service-worker.js');assert.match(page,/callout-camera\.js/);assert.match(camera,/capture="environment"/);assert.match(camera,/photos:selected/);assert.match(worker,/callout-camera\.js/)});
test('public service pages cover remote support, safety and customer-funded equipment',()=>{const remote=read('remote-support.html'),safety=read('safety.html'),equipment=read('equipment.html'),services=read('services.html'),app=read('app/index.html');assert.match(remote,/never call unexpectedly/i);assert.match(remote,/£15/);assert.match(safety,/DBS/);assert.match(safety,/passwords, PINs, card details/i);assert.match(equipment,/paid in full before it is purchased/i);assert.match(services,/Cancellation is free until one hour/);assert.match(app,/Accessibility or communication notes/);assert.match(app,/Do not enter passwords/);assert.match(app,/Book for myself/);assert.match(app,/Book for someone else/);assert.match(app,/person receiving support remains in control/i)});
