import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {onRequestGet,onRequestPost,onRequestPatch} from '../functions/api/admin/tickets.js';
import {onRequestGet as getControlOverview} from '../functions/api/admin/control-overview.js';

function setup(){const values=new Map(),kv={async get(key,type){const value=values.get(key);return type==='json'&&value?JSON.parse(value):value??null},async put(key,value){values.set(key,value)},async list({prefix}){return{keys:[...values.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name}))}}};return{values,env:{ADMIN_PASSWORD:'secret',VIPOAP_DATA:kv}}}
const owner=(method='GET',body,url='https://example.test/api/admin/tickets')=>new Request(url,{method,headers:{'content-type':'application/json','x-admin-password':'secret'},body:body?JSON.stringify(body):undefined});
async function partner(values){const token='partner-token',bytes=new TextEncoder().encode(token),hash=await crypto.subtle.digest('SHA-256',bytes),digest=[...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('');values.set(`admin-session:${digest}`,JSON.stringify({role:'operator',email:'engineer@example.com',operatorId:'eng-one',territoryIds:['andover']}));return(method='GET',body)=>new Request('https://example.test/api/admin/tickets',{method,headers:{'content-type':'application/json','x-admin-session':token},body:body?JSON.stringify(body):undefined})}

test('ticket queue combines bookings and help while restricting partners to assigned work',async()=>{const{env,values}=setup();values.set('operator:eng-one',JSON.stringify({id:'eng-one',name:'Alice',status:'active',territoryIds:['andover']}));values.set('operator:eng-two',JSON.stringify({id:'eng-two',name:'Bob',status:'active',territoryIds:['andover']}));values.set('booking:one',JSON.stringify({reference:'BK-1',name:'Customer One',service:'Printer help',status:'confirmed',assignedEngineerId:'eng-one',territoryId:'andover',date:'2026-09-10'}));values.set('booking:two',JSON.stringify({reference:'BK-2',name:'Customer Two',service:'Wi-Fi help',status:'confirmed',assignedEngineerId:'eng-two',territoryId:'andover',date:'2026-09-11'}));values.set('help-request:one',JSON.stringify({reference:'HELP-1',name:'Customer One',category:'appointment',description:'Please change the date',assignedEngineerId:'eng-one',territoryId:'andover'}));const all=await(await onRequestGet({request:owner(),env})).json();assert.equal(all.tickets.length,3);assert.equal(all.central,true);const partnerRequest=await partner(values),mine=await(await onRequestGet({request:partnerRequest(),env})).json();assert.deepEqual(new Set(mine.tickets.map(item=>item.reference)),new Set(['BK-1','HELP-1']));assert.equal(mine.central,false)});

test('engineers can log, annotate, escalate and arrange a repeat ticket',async()=>{const{env,values}=setup();values.set('operator:eng-one',JSON.stringify({id:'eng-one',name:'Alice',territoryIds:['andover']}));const partnerRequest=await partner(values);let response=await onRequestPost({request:partnerRequest('POST',{customerName:'Jane Customer',title:'Laptop help',summary:'Laptop will not start',territoryId:'andover'}),env}),created=await response.json();assert.equal(response.status,201);assert.equal(created.ticket.assignedEngineerId,'eng-one');response=await onRequestPatch({request:partnerRequest('PATCH',{sourceKey:created.key,action:'note',note:'Power supply tested'}),env});assert.equal(response.status,200);response=await onRequestPatch({request:partnerRequest('PATCH',{sourceKey:created.key,action:'escalate',note:'Possible hardware repair'}),env});assert.equal(response.status,200);const data=await(await onRequestGet({request:partnerRequest(),env})).json(),ticket=data.tickets.find(item=>item.sourceKey===created.key);assert.equal(ticket.status,'escalated');assert.equal(ticket.priority,'urgent');assert.equal(ticket.activity.length,3);response=await onRequestPost({request:partnerRequest('POST',{sourceType:'repeat-call',parentTicketId:created.key,customerName:'Jane Customer',title:'Repeat visit: Laptop help',summary:'Return with charger',territoryId:'andover'}),env});assert.equal(response.status,201)});

test('admin control room summarises engineers, compliance, workload and payouts',async()=>{const{env,values}=setup();values.set('operator:eng-one',JSON.stringify({id:'eng-one',name:'Alice',email:'alice@example.com',status:'active',territoryIds:['andover'],trainingStatus:'complete',dbsStatus:'verified',dbsRenewalDate:'2099-01-01'}));values.set('training-progress:eng-one:course',JSON.stringify({operatorId:'eng-one',courseId:'course',status:'complete'}));values.set('booking:open',JSON.stringify({assignedEngineerId:'eng-one',territoryId:'andover',jobStatus:'in-progress',date:'2099-01-01'}));values.set('booking:done',JSON.stringify({assignedEngineerId:'eng-one',territoryId:'andover',jobStatus:'completed',providerEntitlementPence:2500}));const response=await getControlOverview({request:owner('GET',null,'https://example.test/api/admin/control-overview'),env}),data=await response.json();assert.equal(response.status,200);assert.equal(data.summary.engineers,1);assert.equal(data.summary.openJobs,1);assert.equal(data.summary.awaitingPayoutPence,2500);assert.equal(data.engineers[0].trainingCompleted,1)});

test('My Work presents the unified ticket workflow and admin gets a compact control room',()=>{const page=fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8'),workspace=fs.readFileSync(new URL('../admin/ticket-workspace.js',import.meta.url),'utf8'),overview=fs.readFileSync(new URL('../admin/control-overview.js',import.meta.url),'utf8');assert.match(page,/ticket-workspace\.js\?v=2/);for(const label of ['Log a job','Extend job','Escalate ticket','Repeat call','Complete job'])assert.match(workspace,new RegExp(label));assert.match(workspace,/showModal\(\)/);for(const label of ['Engineers, compliance and payments','Training complete','DBS current','Awaiting payout'])assert.match(overview,new RegExp(label))});

test('availability is collapsed by default and the admin helpdesk has its own page',()=>{const partner=fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8'),admin=fs.readFileSync(new URL('../admin/os.html',import.meta.url),'utf8'),helpdesk=fs.readFileSync(new URL('../admin/helpdesk.html',import.meta.url),'utf8'),navigation=fs.readFileSync(new URL('../admin/mobile-nav.js',import.meta.url),'utf8'),workspace=fs.readFileSync(new URL('../admin/ticket-workspace.js',import.meta.url),'utf8');assert.match(partner,/id="areaAvailability"/);assert.match(workspace,/Show availability/);assert.match(workspace,/content\.hidden=true/);assert.match(workspace,/aria-expanded/);assert.doesNotMatch(admin,/ticket-workspace\.js/);assert.match(admin,/href="helpdesk"/);assert.match(helpdesk,/data-workspace="admin"/);assert.match(helpdesk,/ticket-workspace\.js\?v=3/);assert.match(navigation,/label:'Helpdesk'/);assert.match(workspace,/ADMIN HELPDESK/);assert.match(workspace,/All tickets/);assert.match(workspace,/document\.body\.dataset\.workspace==='admin'/)});
