(()=>{
  const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const state={token:localStorage.getItem('vipoapCustomerSession')||'',data:null,waiting:false};
  const permissionLabels={book:'Book support',change_cancel:'Request appointment changes',pay:'Make payments',receive_notifications:'Receive notifications',view_history:'View appointment history',view_summaries:'View Engineer summaries',view_receipts:'View invoices',message_support:'Contact VIPOAP'};
  const statusLabel=value=>String(value||'pending').replaceAll('-',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
  const empty=text=>`<div class="empty">${esc(text)}</div>`;
  const formatDate=value=>{if(!value)return'';const date=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isNaN(date.getTime())?esc(value):date.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'})};
  const formatMoney=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(value)||0);

  async function api(url,options={}){
    const headers={...(state.token?{'x-customer-session':state.token}:{}),...(options.body?{'content-type':'application/json'}:{})};
    const response=await fetch(url,{...options,headers:{...headers,...options.headers}});
    const type=response.headers.get('content-type')||'';
    const data=type.includes('application/json')?await response.json():await response.blob();
    if(!response.ok){const error=new Error(data?.error||'Something went wrong. Please try again.');error.status=response.status;throw error}
    return data;
  }
  async function publicPost(url,body){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error||'Please try again.');return data}
  function showStatus(message,error=false){const box=$('portalStatus');box.textContent=message;box.classList.toggle('error',error);box.classList.remove('hidden');clearTimeout(showStatus.timer);showStatus.timer=setTimeout(()=>box.classList.add('hidden'),7000)}
  function openView(name,updateHash=true){const allowed=[...document.querySelectorAll('[data-panel]')].map(panel=>panel.dataset.panel),view=allowed.includes(name)?name:'overview';document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===view));document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===view;button.classList.toggle('active',active);active?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current')});if(updateHash)history.replaceState(null,'',`#${view}`);document.querySelector(`[data-panel="${view}"]`)?.scrollIntoView({block:'start'});}

  function renderOverview(data){
    const active=data.appointments.filter(item=>!['completed','cancelled','declined'].includes(item.bookingStatus||item.status));
    const next=[...active].filter(item=>item.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`))[0];
    $('overviewCards').innerHTML=`<article class="metric"><strong>${active.length}</strong><span>Current appointments</span></article><article class="metric"><strong>${data.visitHistory.length}</strong><span>Completed visits</span></article><article class="metric"><strong>${data.receipts.length}</strong><span>Invoices and receipts</span></article><article class="metric"><strong>${data.entitlement?.active?`£${Number(data.entitlement.memberRemotePrice||20).toFixed(0)}`:'PAYG'}</strong><span>${data.entitlement?.active?'Member remote rate · 30 min':'Membership status'}</span></article>`;
    $('nextAppointment').innerHTML=next?`<div class="timeline-item"><h4>${formatDate(next.date)} at ${esc(next.time)}</h4><p>${esc(next.service||next.category||'Technology support')} · ${esc(next.supportType||'')}</p><span class="pill">${esc(statusLabel(next.bookingStatus||next.status))}</span></div><button class="text-button" type="button" data-open-view="appointments">View all appointments</button>`:empty('You have no upcoming appointment.');
  }
  function renderAppointments(data){
    if(!data.appointments.length){$('appointmentList').innerHTML=empty('No appointments yet. When you book support, it will appear here.');return}
    $('appointmentList').innerHTML=data.appointments.map(item=>{const status=item.bookingStatus||item.status||'pending',canChange=!['completed','cancelled','declined','in-progress','safety-stopped'].includes(status),requestPending=item.customerRequestStatus==='received';return `<article class="record"><div><h3>${formatDate(item.date)} at ${esc(item.time||'Time to be confirmed')}</h3><p>${esc(item.service||item.category||'Technology support')}${item.supportType?` · ${esc(item.supportType)}`:''}${item.reference?` · ${esc(item.reference)}`:''}</p><span class="pill">${esc(statusLabel(status))}</span> <span class="pill neutral">${esc(statusLabel(item.paymentStatus||''))}</span>${requestPending?'<p><strong>We have received your change request.</strong></p>':''}</div>${canChange&&!requestPending?`<details class="manage"><summary>Need to change this appointment?</summary><div class="manage-grid"><div class="field"><label>Request</label><select data-appointment-type><option value="change">A different date or time</option><option value="cancel">Cancellation</option></select></div><div class="field"><label>Preferred date or details</label><input data-appointment-details maxlength="300" placeholder="For example: Tuesday afternoon"></div><button class="button primary" type="button" data-appointment-request="${esc(item.key)}">Send request</button></div><p class="muted">This sends a request to VIPOAP. Your booking remains unchanged until we confirm it.</p></details>`:''}</article>`}).join('');
  }
  function renderReceipts(data){$('receiptList').innerHTML=data.receipts.length?data.receipts.map(item=>`<article class="record"><div><h3>${esc(item.number||'VIPOAP invoice')}</h3><p>Issued ${formatDate(item.issueDate)}${item.dueDate?` · Due ${formatDate(item.dueDate)}`:''}</p><span class="pill">${esc(statusLabel(item.status))}</span></div><div><div class="amount">${formatMoney(item.total)}</div><div class="record-actions"><button class="button secondary compact" type="button" data-receipt="${esc(item.key)}" data-number="${esc(item.number||'VIPOAP-invoice')}">Download copy</button></div></div></article>`).join(''):empty('No invoices or receipts are available yet.')}
  function renderMembership(data){const e=data.entitlement;$('membershipSignup').classList.toggle('hidden',Boolean(e?.active));if(e?.active){$('membershipSummary').innerHTML=`<p class="eyebrow">${esc(statusLabel(e.plan))} membership</p><h3>Your member remote-support rate</h3><div class="membership-minutes">£${Number(e.memberRemotePrice||20).toFixed(0)}</div><p>For each 30-minute remote-support session. Support time is charged only when you use it; there is no monthly allowance to lose.</p><p class="muted">Current period: ${formatDate(e.period.start)} to ${formatDate(e.period.end)}. You also receive priority booking and the other benefits of your plan.</p>${e.annualCheckupAvailable?'<p><span class="pill">Annual Technology Review available</span></p>':''}`;}else $('membershipSummary').innerHTML='<p class="eyebrow">Pay as you go</p><h3>No active membership</h3><p>You can still book friendly support whenever you need it.</p><p><a class="button secondary" href="../membership.html">Compare memberships</a></p>'}
  function renderFamily(data){const active=data.delegatedAccess.filter(item=>item.status==='active'&&item.relationship==='granted');$('familyList').innerHTML=active.length?active.map(item=>`<article class="record"><div><h3>${esc(item.personName||item.personEmail||'Trusted person')}</h3><p>${item.permissions.map(permission=>esc(permissionLabels[permission]||permission)).join(' · ')}</p><span class="pill">Active</span></div><button class="button quiet compact" type="button" data-revoke-family="${esc(item.key)}">Remove access</button></article>`).join(''):empty('Nobody else currently has access to manage your support.')}
  function renderHealth(data){const latest=data.healthChecks[0];$('healthSummary').innerHTML=latest?`<section class="card health-card"><div class="health-score" style="--score:${Number(latest.overallScore)||0}"><strong>${Number(latest.overallScore)||0}/100</strong></div><div><p class="eyebrow">Latest Home Health Check</p><h3>Your home technology overview</h3><div class="score-grid"><span>Wi-Fi<br>${latest.scores.wifi}</span><span>Security<br>${latest.scores.security}</span><span>Backups<br>${latest.scores.backup}</span><span>Devices<br>${latest.scores.device}</span><span>Scam safety<br>${latest.scores.scamAwareness}</span></div>${latest.observations?`<p>${esc(latest.observations)}</p>`:''}${latest.recommendations?.length?`<ul>${latest.recommendations.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:''}<p class="muted">Next suggested review: ${formatDate(latest.nextReviewDue)}</p></div></section>`:empty('No Home Health Check has been completed yet.');$('visitHistory').innerHTML=data.visitHistory.length?data.visitHistory.map(item=>`<div class="timeline-item"><h4>${formatDate(item.date)} · ${esc(item.reference||'Completed visit')}</h4><p>${esc(item.summary||item.category||'Technology support')}</p>${item.actionsTaken?`<p><strong>What was done:</strong> ${esc(item.actionsTaken)}</p>`:''}${item.recommendations?`<p><strong>Recommendations:</strong> ${esc(item.recommendations)}</p>`:''}</div>`).join(''):empty('No completed visits yet.');$('technologyList').innerHTML=data.technology.length?data.technology.map(item=>`<article class="record"><div><h3>${esc([item.brand,item.model].filter(Boolean).join(' ')||item.type)}</h3><p>${esc(item.type)}${item.location?` · ${esc(item.location)}`:''}</p></div><span class="pill neutral">${esc(item.status||'Recorded')}</span></article>`).join(''):empty('No household technology has been recorded yet.')}
  function renderHelp(data){$('helpRequestList').innerHTML=data.helpRequests.length?data.helpRequests.map(item=>`<div class="timeline-item"><h4>${esc(item.reference)}</h4><p>${esc(statusLabel(item.status))} · ${formatDate(item.updatedAt)}</p></div>`).join(''):empty('You have no open help requests.')}
  function renderSettings(data){$('accountName').value=data.customer.name||'';$('accountEmail').value=data.customer.email||'';$('accountPreferredContact').value=['Email','Phone','SMS'].includes(data.customer.preferredContact)?data.customer.preferredContact:'Email';$('accountAccessibility').value=data.customer.accessibilityPreferences||''}
  function render(data){$('welcome').textContent=`Welcome, ${data.customer.name?.split(/\s+/)[0]||'there'}`;renderOverview(data);renderAppointments(data);renderReceipts(data);renderMembership(data);renderFamily(data);renderHealth(data);renderHelp(data);renderSettings(data)}

  async function load(){const data=await api('/api/account/overview');state.data=data;$('login').classList.add('hidden');$('account').classList.remove('hidden');$('signout').classList.remove('hidden');render(data);await loadPreferred();openView(location.hash.slice(1)||'overview',false)}
  async function loadPreferred(){const target=$('preferredEngineerContent');try{const data=await api('/api/account/preferred-engineer'),selected=data.engineers.find(item=>item.id===data.preferredEngineerId);target.innerHTML=selected?`<p><strong>${esc(selected.firstName)}</strong> is your preferred Engineer.</p><p class="muted">We will prioritise your preference when they are available, but cannot guarantee a particular Engineer or appointment time.</p><button class="button quiet compact" type="button" data-remove-preferred>Remove preference</button>`:data.engineers.length?`<p>Choose an Engineer who has helped you before. We cannot guarantee availability.</p><div class="record-actions"><select id="preferredChoice"><option value="">Choose an Engineer</option>${data.engineers.map(item=>`<option value="${esc(item.id)}">${esc(item.firstName)}</option>`).join('')}</select><button class="button primary compact" type="button" data-save-preferred>Save preference</button></div>`:'<p class="muted">After a completed appointment, you can choose that Engineer for future bookings.</p>'}catch{target.innerHTML='<p class="muted">Your Engineer preference is temporarily unavailable.</p>'}}

  $('continue').addEventListener('click',async()=>{const status=$('loginStatus'),button=$('continue');status.textContent='';button.disabled=true;try{if(!state.waiting){await publicPost('/api/account/auth/request',{email:$('email').value});state.waiting=true;$('email').readOnly=true;$('codeField').classList.remove('hidden');$('differentEmail').classList.remove('hidden');button.textContent='Sign in';$('code').focus();status.textContent='If that account exists, your private code is on its way.'}else{const data=await publicPost('/api/account/auth/verify',{email:$('email').value,code:$('code').value});state.token=data.token;localStorage.setItem('vipoapCustomerSession',state.token);await load()}}catch(error){status.textContent=error.message}finally{button.disabled=false}});
  $('code').addEventListener('keydown',event=>{if(event.key==='Enter')$('continue').click()});
  $('differentEmail').addEventListener('click',()=>{state.waiting=false;$('email').readOnly=false;$('code').value='';$('codeField').classList.add('hidden');$('differentEmail').classList.add('hidden');$('continue').textContent='Send my sign-in code';$('email').focus()});
  $('signout').addEventListener('click',()=>{localStorage.removeItem('vipoapCustomerSession');location.href='./account'});
  $('refreshAccount').addEventListener('click',async()=>{try{await load();showStatus('Your account is up to date.')}catch(error){showStatus(error.message,true)}});
  document.querySelector('.account-nav').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button)openView(button.dataset.view)});
  document.addEventListener('click',async event=>{
    const opener=event.target.closest('[data-open-view]');if(opener)return openView(opener.dataset.openView);
    const appointment=event.target.closest('[data-appointment-request]');if(appointment){const details=appointment.closest('details'),type=details.querySelector('[data-appointment-type]').value,note=details.querySelector('[data-appointment-details]').value;appointment.disabled=true;try{await api('/api/account/appointment-request',{method:'POST',body:JSON.stringify({bookingKey:appointment.dataset.appointmentRequest,requestType:type,details:note})});await load();openView('appointments');showStatus('Your request has been sent. The appointment stays as booked until VIPOAP confirms the change.')}catch(error){showStatus(error.message,true)}finally{appointment.disabled=false}return}
    const receipt=event.target.closest('[data-receipt]');if(receipt){receipt.disabled=true;try{const blob=await api(`/api/account/receipt?key=${encodeURIComponent(receipt.dataset.receipt)}`),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${receipt.dataset.number}.html`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){showStatus(error.message,true)}finally{receipt.disabled=false}return}
    const revoke=event.target.closest('[data-revoke-family]');if(revoke){revoke.disabled=true;try{await api(`/api/account/delegated-access?key=${encodeURIComponent(revoke.dataset.revokeFamily)}`,{method:'DELETE'});await load();openView('family');showStatus('That person’s access has been removed.')}catch(error){showStatus(error.message,true)}finally{revoke.disabled=false}return}
    if(event.target.closest('[data-save-preferred]')){const engineerId=$('preferredChoice').value;if(!engineerId)return;try{await api('/api/account/preferred-engineer',{method:'PUT',body:JSON.stringify({engineerId})});await loadPreferred();showStatus('Your preferred Engineer has been saved.')}catch(error){showStatus(error.message,true)}return}
    if(event.target.closest('[data-remove-preferred]')){try{await api('/api/account/preferred-engineer',{method:'DELETE'});await loadPreferred();showStatus('Your Engineer preference has been removed.')}catch(error){showStatus(error.message,true)}}
  });
  $('membershipAction').addEventListener('change',()=>$('membershipPlanField').classList.toggle('hidden',$('membershipAction').value!=='change'));
  $('startMembership').addEventListener('click',async()=>{const button=$('startMembership'),status=$('membershipCheckoutStatus');button.disabled=true;status.textContent='Opening secure Stripe membership form…';try{const data=await api('/api/payments/membership-checkout',{method:'POST',body:JSON.stringify({successUrl:`${location.origin}/app/account?membership=success#membership`,cancelUrl:`${location.origin}/app/account#membership`})});await window.openVipoapStripe(data);status.textContent='Complete signup in the secure form.'}catch(error){status.textContent=error.message;button.disabled=false}});
  $('requestMembership').addEventListener('click',async()=>{const button=$('requestMembership'),status=$('membershipRequestStatus');button.disabled=true;status.textContent='Sending…';try{const data=await api('/api/account/membership-request',{method:'POST',body:JSON.stringify({action:$('membershipAction').value,plan:$('membershipPlan').value,note:$('membershipNote').value})});status.textContent=`Request ${data.reference} has been sent. We will contact you before anything changes.`;$('membershipNote').value='';await load()}catch(error){status.textContent=error.message}finally{button.disabled=false}});
  $('addFamily').addEventListener('click',async()=>{const button=$('addFamily'),status=$('familyStatus'),permissions=[...document.querySelectorAll('[name="familyPermission"]:checked')].map(input=>input.value);button.disabled=true;status.textContent='Saving…';try{await api('/api/account/delegated-access',{method:'POST',body:JSON.stringify({delegateEmail:$('delegateEmail').value,permissions})});$('delegateEmail').value='';status.textContent='Access has been added. You can remove it at any time.';await load();openView('family')}catch(error){status.textContent=error.message}finally{button.disabled=false}});
  $('askSubmit').addEventListener('click',async()=>{const button=$('askSubmit'),answer=$('askAnswer');button.disabled=true;answer.textContent='Preparing a careful answer…';try{const data=await api('/api/account/ask',{method:'POST',body:JSON.stringify({question:$('askQuestion').value,includeHousehold:$('askHousehold').checked})});answer.innerHTML=`<p>${esc(data.answer).replace(/\n/g,'<br>')}</p><p class="muted">${data.usedHousehold?'Used your approved household context. ':''}${data.remaining} question${data.remaining===1?'':'s'} remaining today.${data.requiresHuman?' A local person should take over from here.':''}</p>`}catch(error){answer.textContent=error.message}finally{button.disabled=false}});
  $('savePreferences').addEventListener('click',async()=>{const button=$('savePreferences'),status=$('preferenceStatus');button.disabled=true;status.textContent='Saving…';try{await api('/api/account/profile',{method:'PATCH',body:JSON.stringify({preferredContact:$('accountPreferredContact').value,accessibilityPreferences:$('accountAccessibility').value})});status.textContent='Your preferences have been saved.';await load()}catch(error){status.textContent=error.message}finally{button.disabled=false}});
  addEventListener('hashchange',()=>openView(location.hash.slice(1),false));
  if(state.token)load().catch(error=>{if([401,403].includes(error.status)){localStorage.removeItem('vipoapCustomerSession');state.token=''}else $('loginStatus').textContent='Your saved sign-in is being kept. Reconnect to load your account.'});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
})();
