(()=>{
  const guides={
    wifi:{title:'The internet or Wi-Fi is not working',steps:['Check whether one device or every device is affected.','Look at the router without pressing its reset button. Check that its power light is on.','If cables look loose, gently reconnect only the power and broadband cables where they were already fitted.','Switch the router off at its power switch, wait 30 seconds, then switch it on. Allow up to five minutes to reconnect.'],warning:'Never press the small factory-reset button. It can erase the connection settings.'},
    printer:{title:'The printer will not print',steps:['Check the printer is on and has paper.','Read any message on its screen; do not dismiss it until you know what it says.','On your phone or computer, make sure the selected printer has the same name as your printer.','Cancel only the failed print job, then try one simple page again.'],warning:'Do not install software from an advert or an unexpected pop-up.'},
    device:{title:'A phone, tablet or computer is stuck',steps:['If an update is showing, keep the device plugged into power and allow it time to finish.','If no update is running, close the app and open it again.','If it is still stuck, restart the device normally from its power menu.','Write down any error message exactly as it appears.'],warning:'Do not share a password, PIN, recovery code or security answer with anyone.'},
    scam:{title:'A message or caller does not feel right',steps:['Stop. Do not click, reply, pay or allow remote access.','Do not use contact details or links in the message.','Contact the organisation using a number on a bank card, bill or official website you find independently.','If bank details or money may be involved, call your bank immediately using the number on your card.'],warning:'VIPOAP will never unexpectedly call and ask for passwords, payment codes or unattended remote access.'}
  };
  const screen=document.getElementById('help');if(!screen)return;
  const panel=document.createElement('div');panel.className='guided-help';panel.innerHTML='<h3>What would you like help with?</h3><p class="lead">Choose the closest problem. These checks are safe to stop at any time.</p><div class="guide-choices"></div><div id="guideSteps" aria-live="polite"></div>';
  screen.querySelector('.note')?.after(panel);
  panel.querySelector('.guide-choices').innerHTML=Object.entries(guides).map(([id,guide])=>`<button class="service" data-guide="${id}">${guide.title}</button>`).join('');
  function show(id){const guide=guides[id],target=document.getElementById('guideSteps');target.innerHTML=`<div class="panel" style="padding:16px"><h3>${guide.title}</h3><ol>${guide.steps.map(step=>`<li style="margin-bottom:10px">${step}</li>`).join('')}</ol><div class="note"><strong>Important:</strong><br>${guide.warning}</div><p><strong>Did that solve the problem?</strong></p><div class="choices"><button class="btn primary" data-guide-done>Yes, it is working</button><button class="btn secondary" data-guide-more>I still need help</button></div></div>`;target.scrollIntoView({behavior:'smooth',block:'start'});target.querySelector('[data-guide-done]').onclick=()=>target.innerHTML='<div class="note"><strong>Good news.</strong><br>If the problem returns, write down what you were doing and any message you see.</div>';target.querySelector('[data-guide-more]').onclick=()=>target.innerHTML='<div class="note"><strong>You do not have to keep troubleshooting.</strong><br>A local VIPOAP Engineer Partner can take it from here.</div><button class="btn primary" data-screen="book">Book technology help</button><button class="btn secondary" onclick="location.href=\'../help.html\'">Send a help request</button>';target.querySelector('[data-screen]')?.addEventListener('click',()=>openScreen('book'))}
  panel.querySelectorAll('[data-guide]').forEach(button=>button.onclick=()=>show(button.dataset.guide));
})();
