const DEFAULT_AVAILABILITY={monday:[['19:00','21:00']],wednesday:[['19:00','21:00']],saturday:[['11:00','13:00'],['16:00','19:00']]};
const DAY_NAMES=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
function addMinutes(time,mins){const [h,m]=time.split(':').map(Number);const d=new Date(2000,0,1,h,m+mins);return d.toTimeString().slice(0,5)}
function toMinutes(time){const [h,m]=time.split(':').map(Number);return h*60+m}
async function getSettings(env,supportType){if(!env.VIPOAP_DATA)return [{operatorId:'dan-stevens',weekly:DEFAULT_AVAILABILITY,blockedDates:[]}];const service=supportType==='Remote support'?'remote':'home',keys=await env.VIPOAP_DATA.list({prefix:'availability:'}),records=(await Promise.all(keys.keys.map(key=>env.VIPOAP_DATA.get(key.name,'json')))).filter(record=>record?.territoryId==='andover'),eligible=[];for(const record of records){const operator=record.operatorId?await env.VIPOAP_DATA.get(`operator:${record.operatorId}`,'json'):null,services=Array.isArray(operator?.serviceTypes)?operator.serviceTypes:['home','remote'];if(services.includes(service))eligible.push(record)}if(eligible.length)return eligible.map(record=>({operatorId:record.operatorId||'dan-stevens',weekly:supportType==='Remote support'?record.remoteWeekly:record.homeVisitWeekly,blockedDates:record.blockedDates||[],overrides:record.overrides||[]}));if(records.length)return[];const saved=await env.VIPOAP_DATA.get('availability','json');return[{operatorId:'dan-stevens',...(saved||{weekly:DEFAULT_AVAILABILITY,blockedDates:[]})}]}
export async function onRequestGet({request,env}){
  if(!env.VIPOAP_DATA)return Response.json({error:'Booking is temporarily unavailable. Please call 07977 254158.'},{status:503});
  const url=new URL(request.url),date=url.searchParams.get('date'),duration=Number(url.searchParams.get('duration')),supportType=url.searchParams.get('supportType')==='Remote support'?'Remote support':'Home visit';
  if(!date||![30,60].includes(duration))return Response.json({error:'Choose a valid date and appointment length.'},{status:400});
  const chosen=new Date(`${date}T12:00:00Z`);if(Number.isNaN(chosen.getTime())||chosen.toISOString().slice(0,10)!==date)return Response.json({error:'Invalid date.'},{status:400});
  const settings=await getSettings(env,supportType),capacity=new Map();
  for(const setting of settings){if(setting.blockedDates?.includes(date)&&!setting.overrides?.some(item=>item.date===date&&item.status==='available'))continue;const ranges=setting.weekly?.[DAY_NAMES[chosen.getUTCDay()]]||[];for(const [start,end] of ranges){for(let t=start;toMinutes(t)+duration<=toMinutes(end);t=addMinutes(t,30)){if(!capacity.has(t))capacity.set(t,new Set());capacity.get(t).add(setting.operatorId)}}}
  const keys=await env.VIPOAP_DATA.list({prefix:`booking:${date}:`});
  const booked=(await Promise.all(keys.keys.map(k=>env.VIPOAP_DATA.get(k.name,'json')))).filter(Boolean).filter(b=>!['declined','cancelled'].includes(b.status)&&!(b.paymentStatus==='payment-required'&&b.holdExpiresAt&&new Date(b.holdExpiresAt)<=new Date()));
  const slots=[...capacity.keys()].sort().filter(slot=>{const start=toMinutes(slot),end=start+duration,globalConflict=booked.some(b=>!b.operatorId&&!b.assignedEngineerId&&start<toMinutes(b.time)+Number(b.duration||30)&&end>toMinutes(b.time));if(globalConflict)return false;return[...capacity.get(slot)].some(operatorId=>!booked.some(b=>{const assigned=b.operatorId||b.assignedEngineerId;if(assigned!==operatorId)return false;const bs=toMinutes(b.time),be=bs+Number(b.duration||30);return start<be&&end>bs}))});
  return Response.json({slots,timezone:'Europe/London'});
}
