import {takeRateLimit} from '../_shared/rate-limit.js';
import {onRequestPost as createHelpRequest} from './help-requests.js';
const clean=(value,max=2500)=>String(value??'').trim().replace(/[<>]/g,'').slice(0,max);
const patterns=[
  {test:/password|passcode|pin\b|one[ -]?time (?:code|password)|security code/i,reason:'It asks for private security information.',weight:4},
  {test:/gift card|crypto(?:currency)?|bitcoin|bank transfer|wire transfer/i,reason:'It asks for a difficult-to-recover payment method.',weight:4},
  {test:/remote access|anydesk|teamviewer|screen share/i,reason:'It asks for remote access to a device.',weight:4},
  {test:/act now|immediately|urgent|final warning|account (?:will be )?(?:closed|suspended|blocked)/i,reason:'It creates pressure or a false sense of urgency.',weight:2},
  {test:/click (?:this|the) link|verify (?:your )?account|confirm (?:your )?details|login here/i,reason:'It asks you to use a link to confirm personal details.',weight:3},
  {test:/won|prize|refund|inheritance|parcel (?:fee|charge)|delivery fee/i,reason:'It promises money, a prize, refund or delivery after an unexpected contact.',weight:2},
  {test:/police|hmrc|tax office|bank security|fraud team|microsoft support/i,reason:'It may be impersonating a trusted organisation.',weight:2},
  {test:/keep (?:this|it) secret|do not tell|don't tell/i,reason:'It asks you to keep the contact secret.',weight:4}
];
function assessment(text){const matches=patterns.filter(item=>item.test.test(text)),score=matches.reduce((sum,item)=>sum+item.weight,0);let outcome='uncertain',headline='There is not enough information to be sure.';if(score>=6){outcome='likely';headline='This looks likely to be a scam.'}else if(score>=2){outcome='suspicious';headline='I would be careful with this.'}else if(text.length>=80){outcome='verify';headline='This may be genuine, but check it independently before acting.'}return{outcome,headline,reasons:matches.map(item=>item.reason).slice(0,4),safetySteps:['Do not click links or reply yet.','Do not share passwords, PINs or one-time codes.','Contact the organisation using a telephone number or website you find independently.','If money or bank details may be involved, contact your bank using the number on your card.']}}
export async function onRequestPost({request,env}){if(!env.VIPOAP_DATA)return Response.json({error:'The checker is temporarily unavailable. Please call 07977 254158.'},{status:503});let body;try{body=await request.json()}catch{return Response.json({error:'Please check the information and try again.'},{status:400})}const ip=request.headers.get('CF-Connecting-IP')||request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown',rate=await takeRateLimit(env.VIPOAP_DATA,{scope:'public-scam-check',identifier:ip,limit:12,windowSeconds:3600});if(!rate.allowed)return new Response(JSON.stringify({error:'Too many checks have been made. Please wait, or call 07977 254158.'}),{status:429,headers:{'content-type':'application/json','retry-after':String(rate.retryAfter)}});const channel=clean(body.channel,30),text=clean(body.text,2500);if(!['Email','Text message','Phone call','WhatsApp','Website','Parcel message','Bank message','Something else'].includes(channel)||text.length<15)return Response.json({error:'Please choose what you received and add a little more detail.'},{status:400});const result=assessment(text),now=new Date().toISOString(),id=crypto.randomUUID(),record={id,channel,outcome:result.outcome,reasons:result.reasons,createdAt:now,expiresAt:new Date(Date.now()+90*86400000).toISOString(),humanReview:false};await env.VIPOAP_DATA.put(`scam-check:${now.slice(0,10)}:${id}`,JSON.stringify(record),{expirationTtl:90*86400});let help=null;if(body.humanReview){const helpBody={name:clean(body.name,100),email:clean(body.email,120),phone:clean(body.phone,40),contactPreference:clean(body.contactPreference||'Email',20),category:'scam',postcode:clean(body.postcode,20),description:`Possible ${channel.toLowerCase()} scam for human review:\n\n${text}`},helpRequest=new Request(new URL('/api/help-requests',request.url),{method:'POST',headers:{'content-type':'application/json','CF-Connecting-IP':ip},body:JSON.stringify(helpBody)}),response=await createHelpRequest({request:helpRequest,env});help=await response.json();if(!response.ok)return Response.json({error:help.error,result},{status:response.status});record.humanReview=true;record.helpReference=help.reference;await env.VIPOAP_DATA.put(`scam-check:${now.slice(0,10)}:${id}`,JSON.stringify(record),{expirationTtl:90*86400})}return Response.json({ok:true,automated:true,disclaimer:'This is an automated guide, not a guarantee that something is safe or fraudulent.',...result,help})}
export {assessment};
