const clean=(value,max=3000)=>String(value??'').trim().slice(0,max);
const normalisePhone=value=>clean(value,40).replace(/[^\d+]/g,'');

export const COMMUNICATION_EVENTS=Object.freeze({
  BOOKING_RECEIVED:'booking_received',
  BOOKING_CONFIRMED:'booking_confirmed',
  BOOKING_REMINDER_24H:'booking_reminder_24h',
  BOOKING_REMINDER_3H:'booking_reminder_3h',
  PROVIDER_JOB_OFFER:'provider_job_offer',
  PROVIDER_JOB_CONFIRMED:'provider_job_confirmed',
  ADDITIONAL_TIME_REQUEST:'additional_time_request',
  PAYMENT_REMINDER:'payment_reminder',
  REFERRAL_INVITE:'referral_invite',
  REFERRAL_REWARD:'referral_reward',
  REVIEW_INVITE:'review_invite'
});

export function whatsappConfigured(env){return Boolean(env.WHATSAPP_API_URL&&env.WHATSAPP_ACCESS_TOKEN)}
export function whatsappTemplateName(env,event){const key=`VIPOAP_WA_TEMPLATE_${String(event||'').toUpperCase()}`;return clean(env[key],120)}
export function whatsappBodyComponents(templateData={}){const values=Object.values(templateData).filter(value=>value!==undefined&&value!==null&&String(value)!=='').map(value=>({type:'text',text:clean(value,900)}));return values.length?[{type:'body',parameters:values}]:[]}

export async function recordCommunication(env,{customerId='',providerId='',bookingKey='',reference='',channel,direction='outbound',event='',recipient='',subject='',message='',deliveryStatus='recorded',providerMessageId='',metadata={}}){if(!env.VIPOAP_DATA)return'';const id=crypto.randomUUID(),now=new Date().toISOString(),owner=customerId||providerId||'system',key=`communication:${owner}:${now}:${id}`;await env.VIPOAP_DATA.put(key,JSON.stringify({id,customerId,providerId,bookingKey,reference,channel,direction,event,recipient,subject,message,deliveryStatus,providerMessageId,metadata,createdAt:now,updatedAt:now}));return key}

export async function sendEmail(env,{to,subject,html,text='',idempotencyKey='',event='',customerId='',providerId='',bookingKey='',reference=''}){const recipient=clean(to,180);if(!recipient)return{ok:false,status:'missing-recipient'};if(!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)return{ok:false,status:'not-configured'};const headers={authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'};if(idempotencyKey)headers['idempotency-key']=clean(idempotencyKey,180);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers,body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[recipient],subject:clean(subject,180),html,text:text||undefined})});let body={};try{body=await response.json()}catch{}const status=response.ok?'sent':'failed';await recordCommunication(env,{customerId,providerId,bookingKey,reference,channel:'Email',event,recipient,subject,message:text||subject,deliveryStatus:status,providerMessageId:clean(body.id,160)});return{ok:response.ok,status,providerMessageId:clean(body.id,160),httpStatus:response.status}}

export async function sendWhatsAppTemplate(env,{to,event,templateName='',language='en_GB',components=[],customerId='',providerId='',bookingKey='',reference='',metadata={}}){const recipient=normalisePhone(to);if(!recipient)return{ok:false,status:'missing-recipient'};if(!whatsappConfigured(env))return{ok:false,status:'not-configured'};const template=templateName||whatsappTemplateName(env,event);if(!template)return{ok:false,status:'template-not-configured'};const payload={messaging_product:'whatsapp',to:recipient,type:'template',template:{name:template,language:{code:language},...(components.length?{components}:{})}};const response=await fetch(env.WHATSAPP_API_URL,{method:'POST',headers:{authorization:`Bearer ${env.WHATSAPP_ACCESS_TOKEN}`,'content-type':'application/json'},body:JSON.stringify(payload)});let body={};try{body=await response.json()}catch{}const providerMessageId=clean(body?.messages?.[0]?.id,200),status=response.ok?'sent':'failed';await recordCommunication(env,{customerId,providerId,bookingKey,reference,channel:'WhatsApp',event,recipient,message:`Template: ${template}`,deliveryStatus:status,providerMessageId,metadata:{template,language,...metadata}});return{ok:response.ok,status,providerMessageId,httpStatus:response.status,error:response.ok?'':clean(body?.error?.message||'',500)}}

export async function queueCommunication(env,{event,channel,recipient,customerId='',providerId='',bookingKey='',reference='',templateData={},subject='',message=''}){if(!env.VIPOAP_DATA)return'';const id=crypto.randomUUID(),now=new Date().toISOString(),key=`communication-queue:${now}:${id}`;await env.VIPOAP_DATA.put(key,JSON.stringify({id,event,channel,recipient,customerId,providerId,bookingKey,reference,templateData,subject,message,status:'pending',attempts:0,createdAt:now,updatedAt:now}));return key}

export async function processCommunicationQueue(env,{limit=20,now=new Date()}={}){if(!env.VIPOAP_DATA)return{processed:0,sent:0,failed:0,skipped:0};const page=await env.VIPOAP_DATA.list({prefix:'communication-queue:'}),pending=[];for(const item of page.keys){const record=await env.VIPOAP_DATA.get(item.name,'json');if(record?.status==='pending')pending.push({key:item.name,...record})}pending.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));let processed=0,sent=0,failed=0,skipped=0;for(const item of pending.slice(0,limit)){processed++;let result={ok:false,status:'unsupported-channel'};if(item.channel==='WhatsApp')result=await sendWhatsAppTemplate(env,{to:item.recipient,event:item.event,components:whatsappBodyComponents(item.templateData),customerId:item.customerId,providerId:item.providerId,bookingKey:item.bookingKey,reference:item.reference,metadata:{queueId:item.id}});else if(item.channel==='Email'&&item.message)result=await sendEmail(env,{to:item.recipient,subject:item.subject||'An update from VIPOAP',html:`<p>${clean(item.message).replace(/\n/g,'<br>')}</p>`,text:item.message,event:item.event,customerId:item.customerId,providerId:item.providerId,bookingKey:item.bookingKey,reference:item.reference,idempotencyKey:item.id});if(result.ok){sent++;await env.VIPOAP_DATA.put(item.key,JSON.stringify({...item,status:'sent',providerMessageId:result.providerMessageId||'',sentAt:now.toISOString(),attempts:Number(item.attempts||0)+1,updatedAt:now.toISOString()}),{expirationTtl:7776000})}else if(['not-configured','template-not-configured','unsupported-channel'].includes(result.status)){skipped++}else{failed++;const attempts=Number(item.attempts||0)+1;await env.VIPOAP_DATA.put(item.key,JSON.stringify({...item,status:attempts>=5?'failed':'pending',attempts,lastError:clean(result.error||result.status,500),updatedAt:now.toISOString()}),{expirationTtl:7776000})}}return{processed,sent,failed,skipped}}
