import {requireCustomer} from '../../_shared/customer-auth.js';
import {membershipEntitlement} from '../../_shared/membership.js';
async function records(kv,prefix){const keys=await kv.list({prefix});return Promise.all(keys.keys.map(async k=>({key:k.name,...await kv.get(k.name,'json')})))}
export async function onRequestGet({request,env}){
  const session=await requireCustomer(request,env);if(!session)return Response.json({error:'Please sign in.'},{status:401});
  const customer=await env.VIPOAP_DATA.get(session.customerId,'json');if(!customer)return Response.json({error:'Account not found.'},{status:404});
  const [bookings,receipts,recommendations,delegates,helpRequests,visits,scamChecks,healthChecks]=await Promise.all([records(env.VIPOAP_DATA,'booking:'),records(env.VIPOAP_DATA,'invoice:'),records(env.VIPOAP_DATA,'equipment-recommendation:'),records(env.VIPOAP_DATA,'delegated-access:'),records(env.VIPOAP_DATA,'help-request:'),records(env.VIPOAP_DATA,'callout:'),records(env.VIPOAP_DATA,'scam-check:'),records(env.VIPOAP_DATA,`health-check:${session.customerId}:`)]);
  const own=x=>x.customerId===session.customerId,redacted={id:session.customerId,name:customer.name,email:customer.email,phone:customer.phone,postcode:customer.postcode,preferredContact:customer.preferredContact||'',accessibilityPreferences:customer.accessibilityPreferences||'',membershipPlan:customer.membershipPlan||customer.membership||'none'};
  return Response.json({customer:redacted,entitlement:await membershipEntitlement(env,session.customerId),appointments:bookings.filter(own).sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)),healthChecks:healthChecks.map(x=>({overallScore:x.overallScore,scores:{wifi:x.wifiScore,security:x.securityScore,backup:x.backupScore,device:x.deviceScore,scamAwareness:x.scamAwarenessScore},recommendations:x.recommendations||[],observations:x.observations||'',completedAt:x.completedAt,nextReviewDue:x.nextReviewDue})).sort((a,b)=>b.completedAt.localeCompare(a.completedAt)),visitHistory:visits.filter(own).map(x=>({reference:x.reference,date:x.date,status:x.status,category:x.category,summary:x.summary||x.serviceSummary||'',actionsTaken:x.actionsTaken||'',recommendations:x.recommendations||'',followUpRequired:Boolean(x.followUpRequired)})).sort((a,b)=>String(b.date).localeCompare(String(a.date))),helpRequests:helpRequests.filter(own).map(x=>({reference:x.reference,status:x.status,category:x.category,updatedAt:x.updatedAt})).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),scamChecks:scamChecks.filter(own).map(x=>({id:x.id,outcome:x.outcome,reasons:x.reasons||[],createdAt:x.createdAt,helpReference:x.helpReference||''})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),technology:(customer.equipment||[]).map(x=>({id:x.id||'',type:x.type||'Device',brand:x.brand||'',model:x.model||'',location:x.location||'',status:x.status||'',upgradePriority:x.upgradePriority||'None'})),receipts:receipts.filter(own),equipment:recommendations.filter(own),delegatedAccess:delegates.filter(x=>x.customerId===session.customerId||x.delegateCustomerId===session.customerId).map(x=>({key:x.key,customerId:x.customerId,delegateCustomerId:x.delegateCustomerId,permissions:x.permissions,status:x.status}))});
}

