import {requireCustomer} from '../../_shared/customer-auth.js';
const clean=(value,max=250)=>String(value??'').trim().replace(/[<>]/g,'').slice(0,max);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>`£${(Number(value)||0).toFixed(2)}`;
export async function onRequestGet({request,env}){
  const session=await requireCustomer(request,env);if(!session)return Response.json({error:'Please sign in.'},{status:401});
  const key=clean(new URL(request.url).searchParams.get('key'));if(!key.startsWith('invoice:'))return Response.json({error:'Invoice not found.'},{status:404});
  const invoice=await env.VIPOAP_DATA.get(key,'json');if(!invoice||invoice.customerId!==session.customerId)return Response.json({error:'Invoice not found.'},{status:404});
  const customer=await env.VIPOAP_DATA.get(session.customerId,'json')||{},number=clean(invoice.number,80)||'VIPOAP-invoice',lines=(invoice.lines||[]).map(line=>`<tr><td>${escapeHtml(line.description)}</td><td>${Number(line.quantity)||0}</td><td>${money(line.unitPrice)}</td><td>${money(line.total)}</td></tr>`).join(''),html=`<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><title>${escapeHtml(number)}</title><style>body{font:16px Arial,sans-serif;color:#102957;max-width:820px;margin:40px auto;padding:20px}header{display:flex;justify-content:space-between;gap:30px;border-bottom:4px solid #5a8f5a;padding-bottom:20px}h1{letter-spacing:.12em}table{width:100%;border-collapse:collapse;margin:30px 0}th,td{text-align:left;padding:12px;border-bottom:1px solid #dce5da}.total{text-align:right;font-size:1.4rem}.muted{color:#667085}@media print{body{margin:0}.print{display:none}}</style></head><body><button class="print" onclick="print()">Print or save as PDF</button><header><div><h1>VIPO<span style="color:#5a8f5a">AP</span></h1><p>Technology without the worry</p></div><div><h2>${escapeHtml(number)}</h2><p>Issued ${escapeHtml(invoice.issueDate||'')}<br>Due ${escapeHtml(invoice.dueDate||'')}</p></div></header><h3>For</h3><p>${escapeHtml(customer.name||'Customer')}<br>${escapeHtml(customer.address||'')}<br>${escapeHtml(customer.postcode||'')}</p><table><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${lines}</tbody></table><p class="total"><strong>Total ${money(invoice.total)}</strong></p><p>Status: <strong>${escapeHtml(invoice.status||'')}</strong></p><p class="muted">VIPOAP · help@vipoap.co.uk · 07977 254158</p></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-disposition':`attachment; filename="${number.replace(/[^a-z0-9-]/gi,'-')}.html"`,'cache-control':'private, no-store','x-content-type-options':'nosniff'}});
}
