(()=>{
  let model;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=pence=>`£${(Number(pence||0)/100).toFixed(2)}`,auth=()=>({'content-type':'application/json','x-admin-password':sessionStorage.getItem('vipoapAdmin')||'','x-admin-session':sessionStorage.getItem('vipoapAdminSession')||''});
  async function api(url,options={}){const response=await fetch(url,{...options,headers:{...auth(),...options.headers}}),data=await response.json();if(!response.ok)throw Error(data.error||'Billing request failed.');return data}
  function mount(){if(document.getElementById('billingControl'))return;const section=document.createElement('section');section.id='billingControl';section.className='card';section.innerHTML='<div class="row"><div><p class="muted">Money control</p><h2>Payments, subscriptions and engineer settlements</h2><p class="muted">Every completed job and the amount owed to its Engineer, with Stripe status and a clear audit trail.</p></div><button class="btn secondary" id="refreshBilling" type="button">Refresh</button></div><div id="billingMetrics" class="billing-metrics"></div><div class="billing-grid"><section class="billing-panel"><div class="row"><div><h3>Engineer payout queue</h3><p class="muted">Open an Engineer to see the jobs making up the balance.</p></div><a class="btn secondary" href="my-payments">Full payment history</a></div><div id="engineerSettlements" class="billing-scroll"></div></section><aside class="billing-panel"><h3>Stripe and accounting</h3><div id="stripeReadiness"></div><hr><h3>Membership subscriptions</h3><div id="subscriptions"></div><hr><h3>Recent customer payments</h3><div id="customerPayments" class="refund-list"></div><hr><h3>Recent refunds</h3><div id="refunds" class="refund-list"></div></aside></div><p id="billingControlStatus" aria-live="polite"></p>';document.querySelector('.os-page-heading')?.after(section);document.getElementById('refreshBilling').onclick=load}
  function render(){const s=model.summary;document.getElementById('billingMetrics').innerHTML=[[money(s.awaitingPence),'Engineers awaiting payment'],[s.engineersAwaiting,'Engineers owed'],[`${s.connectReady}/${s.engineers}`,'Stripe Connect ready'],[s.activeSubscriptions,'Active memberships'],[money(Math.round(s.monthlyRecurringRevenue*100)),'Monthly membership value'],[money(s.customerPaymentsPence),'Customer payments'],[money(s.refundPence),'Refunded'],[model.memberships.length,'Membership records']].map(([v,l])=>`<article class="billing-metric"><strong>${esc(v)}</strong><span>${esc(l)}</span></article>`).join('');
    document.getElementById('engineerSettlements').innerHTML=model.engineers.length?model.engineers.map(e=>`<article class="engineer-settlement"><div class="settlement-summary"><div><strong>${esc(e.name)}</strong><br><small>${esc(e.email)}</small></div><span>${e.summary.awaitingJobs} job${e.summary.awaitingJobs===1?'':'s'}</span><strong>${money(e.summary.awaitingPence)}</strong><span class="stripe-state ${e.stripe.payoutsEnabled?'ready':''}">${e.stripe.payoutsEnabled?'Connect ready':esc(e.stripe.status)}</span></div><details><summary>View ${e.summary.jobs} completed job${e.summary.jobs===1?'':'s'}</summary><div class="settlement-jobs"><table><thead><tr><th>Date</th><th>Job</th><th>Customer</th><th>Service</th><th>Time</th><th>Engineer pay</th><th>Status</th><th></th></tr></thead><tbody>${e.jobs.map(j=>`<tr><td>${esc(j.date)}</td><td>${esc(j.reference)}</td><td>${esc(j.customer)}</td><td>${esc(j.supportType)}<br><small>${esc(j.service)}</small></td><td>${j.duration} mins</td><td><strong>${money(j.amountPence)}</strong></td><td>${esc(j.status)}</td><td>${j.status==='paid'?esc(j.paymentReference||'Recorded'):e.stripe.payoutsEnabled?`<button class="btn primary danger-action" data-stripe-pay="${esc(j.key)}" data-reference="${esc(j.reference)}">Pay with Stripe</button>`:`<a class="btn secondary" href="franchise?operator=${encodeURIComponent(e.id)}">Set up Connect</a>`}</td></tr>`).join('')}</tbody></table></div></details></article>`).join(''):'<p class="muted">No Engineer records are available yet.</p>';
    const checkoutState=model.embeddedCheckoutConfigured?'Embedded checkout ready':'Add STRIPE_PUBLISHABLE_KEY for embedded checkout';
    const membershipState=model.membershipPriceConfigured?'£7.99 membership Price ready':'Add STRIPE_SUPPORT_MONTHLY_PRICE_ID before memberships go live';
    document.getElementById('stripeReadiness').innerHTML=`<p class="billing-note"><strong>${model.stripeConfigured?'Stripe platform connected':'Stripe setup required'}</strong><br>${checkoutState}<br>${membershipState}<br>${s.connectReady===s.engineers&&s.engineers?'All Engineer accounts are ready.':'Engineers complete secure Stripe Connect onboarding before payouts can be sent.'}</p><p class="muted">Customer card details stay with Stripe. VIPOAP stores payment, refund and transfer references for reconciliation.</p><p><a class="btn secondary" href="franchise">Manage Engineer Connect accounts</a></p><p class="muted"><strong>Zoho Books:</strong> customer payments can reconcile through the Stripe bank feed. Engineer earnings and Connect transfers remain itemised here and should be mapped to bills/expenses and a clearing account.</p>`;
    document.getElementById('subscriptions').innerHTML=model.memberships.length?model.memberships.slice(0,12).map(x=>`<p><strong>${esc(x.name)}</strong><br><small>${esc(x.plan)} · £${Number(x.price).toFixed(2)}/${esc(x.billingCycle)} · ${esc(x.status)}${x.renewalDate?` · renews ${esc(x.renewalDate)}`:''}</small></p>`).join(''):'<p class="muted">No memberships yet. Customers can start VIPOAP Support for £7.99/month from their account.</p>';
    document.getElementById('customerPayments').innerHTML=model.payments.length?model.payments.slice(0,8).map(x=>`<div class="refund-row"><span><strong>${esc(x.reference)}</strong><br><small>${esc(x.status)} · £${Number(x.amount).toFixed(2)}</small></span>${x.refundable?`<button class="btn secondary" data-refund-payment="${esc(x.key)}" data-reference="${esc(x.reference)}" data-amount="${Number(x.amount)}">Refund</button>`:''}</div>`).join(''):'<p class="muted">No customer payments recorded.</p>';
    document.getElementById('refunds').innerHTML=model.refunds.length?model.refunds.slice(0,8).map(x=>`<div class="refund-row"><span>${esc(x.createdAt.slice(0,10))}<br><small>${esc(x.reason||x.status)}</small></span><strong>£${Number(x.amount).toFixed(2)}</strong></div>`).join(''):'<p class="muted">No refunds recorded.</p>'}
  async function load(){mount();const status=document.getElementById('billingControlStatus');status.textContent='Refreshing billing information…';try{model=await api('/api/admin/billing-overview');render();status.textContent=`Updated ${new Date(model.generatedAt).toLocaleString('en-GB')}.`}catch(error){status.textContent=error.message}}
  document.addEventListener('click',async event=>{const refund=event.target.closest('[data-refund-payment]');if(refund){const reference=refund.dataset.reference,amount=Number(prompt('Refund amount in pounds:',refund.dataset.amount));if(!Number.isFinite(amount)||amount<=0)return;const typed=prompt(`Type ${reference} to confirm this refund:`,'');if(typed!==reference)return;refund.disabled=true;try{await api('/api/admin/refunds',{method:'POST',body:JSON.stringify({paymentKey:refund.dataset.refundPayment,amountPence:Math.round(amount*100),confirm:typed,reason:'requested_by_customer',note:'Refund created in VIPOAP OS'})});await load()}catch(error){document.getElementById('billingControlStatus').textContent=error.message;refund.disabled=false}return}const button=event.target.closest('[data-stripe-pay]');if(!button)return;const reference=button.dataset.reference;if(!confirm(`Send the recorded Engineer entitlement for ${reference} through Stripe Connect? This moves real money and cannot be undone here.`))return;const typed=prompt(`Type ${reference} to confirm this payout:`,'');if(typed!==reference)return;button.disabled=true;try{await api('/api/admin/stripe-payouts',{method:'POST',body:JSON.stringify({bookingKey:button.dataset.stripePay,confirm:typed})});await load()}catch(error){document.getElementById('billingControlStatus').textContent=error.message;button.disabled=false}});
  document.getElementById('loginBtn')?.addEventListener('click',()=>setTimeout(load,450));if(sessionStorage.getItem('vipoapAdmin')||sessionStorage.getItem('vipoapAdminSession'))load()
})();
