(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const auth=()=>({'content-type':'application/json','x-admin-password':sessionStorage.getItem('vipoapAdmin')||'','x-admin-session':sessionStorage.getItem('vipoapAdminSession')||''});
  async function api(url,options={}){const response=await fetch(url,{...options,headers:{...auth(),...options.headers}}),data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
  const field=(label,id,type='text')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}"></div>`;
  let operators=[],territories=[],roles=[],permissions=[],visits=[];
  function install(){const app=document.getElementById('app');if(!app||document.getElementById('franchiseTools'))return false;const section=document.createElement('div');section.id='franchiseTools';section.innerHTML=`
    <section class="card"><div class="row"><div><h2>Territory drill-down</h2><p class="muted">Open one territory to see its calls, customers, revenue and operators.</p></div><select id="drillTerritory" style="max-width:300px"></select></div><div id="territoryDetail"></div></section>
    <section class="card" data-requires-permission="manage_operators"><div class="row"><div><h2>Edit operators</h2><p class="muted">Update role, territory access, services, readiness and DBS records.</p></div><select id="editOperator" style="max-width:320px"><option value="">Choose operator</option></select></div><div id="operatorEditor" class="hidden"><div class="grid">${field('Name','editOperatorName')}${field('Email','editOperatorEmail','email')}${field('Telephone','editOperatorPhone','tel')}<div class="field"><label for="editOperatorRole">Role</label><select id="editOperatorRole"></select></div><div class="field"><label for="editOperatorTerritories">Territories</label><select id="editOperatorTerritories" multiple size="4"></select></div><div class="field"><label for="editOperatorStatus">Status</label><select id="editOperatorStatus"><option>active</option><option>invited</option><option>paused</option><option>left</option></select></div><div class="field wide"><label>Services this engineer can provide</label><div class="actions"><label><input id="editServiceHome" type="checkbox"> Home visits</label><label><input id="editServiceRemote" type="checkbox"> Remote support</label></div></div><div class="field"><label for="editTrainingStatus">Training</label><select id="editTrainingStatus"><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="complete">Complete</option></select></div><div class="field"><label for="editDbsStatus">DBS status</label><select id="editDbsStatus"><option value="not-recorded">Not recorded</option><option value="required">Required</option><option value="in-progress">In progress</option><option value="verified">Verified</option><option value="expired">Expired</option></select></div>${field('DBS renewal','editDbsRenewal','date')}<div class="field wide"><label for="editOperatorNotes">Notes</label><textarea id="editOperatorNotes"></textarea></div></div><div class="actions"><button class="btn primary" id="updateOperator">Save operator</button><a class="btn secondary" href="training">Open training</a></div><p id="operatorEditStatus"></p><hr><h3>DBS documents</h3><p class="muted">Restricted to authorised DBS administrators. PDF, JPG or PNG; maximum 2 MB.</p><input id="dbsFile" type="file" accept="application/pdf,image/jpeg,image/png"><button class="btn secondary" id="uploadDbs">Upload DBS document</button><div id="dbsDocuments"></div></div></section>
    <section class="card" data-requires-permission="manage_roles"><div class="row"><div><h2>Roles and permissions</h2><p class="muted">Create a role with only the system access it needs.</p></div><select id="editRole"><option value="">Create new role</option></select></div><div class="grid">${field('Role name','roleName')}<div class="field wide"><label for="roleDescription">Description</label><textarea id="roleDescription"></textarea></div><div class="field wide"><label>Permissions</label><div id="rolePermissions" class="permission-grid"></div></div></div><button class="btn primary" id="saveRole">Save role</button><p id="roleStatus"></p></section>
    <section class="card"><h2>Add follow-up to a completed call</h2><div class="grid"><div class="field"><label for="followupCall">Call</label><select id="followupCall"></select></div>${field('Due date','followupDue','date')}<div class="field wide"><label for="followupNotes">What needs following up?</label><textarea id="followupNotes"></textarea></div></div><button class="btn primary" id="createFollowup">Create follow-up</button><p id="followupStatus"></p></section>`;
    app.insertBefore(section,app.lastElementChild);const services=document.getElementById('editServiceHome')?.closest('.field');if(services){const controls=document.createElement('div');controls.className='field wide';controls.innerHTML='<label>HQ service controls</label><div class="actions"><label><input id="suspendHome" type="checkbox"> Suspend home visits</label><label><input id="suspendRemote" type="checkbox"> Suspend remote support</label></div><p class="muted">Suspending one service leaves the other available when compliance is current.</p>';services.after(controls)}bind();return true
  }
  function selectedOperator(){return operators.find(x=>x.key===document.getElementById('editOperator').value)}
  async function load(){const [t,o,r,report]=await Promise.all([api('/api/admin/territories'),api('/api/admin/operators'),api('/api/admin/roles'),api('/api/admin/franchise-report')]);territories=t.territories||[];operators=o.operators||[];roles=r.roles||[];permissions=r.permissions||[];visits=report.completedVisits||[];render()}
  function render(){const territoryOptions=territories.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');document.getElementById('drillTerritory').innerHTML='<option value="">All territories</option>'+territoryOptions;document.getElementById('editOperator').innerHTML='<option value="">Choose operator</option>'+operators.map(x=>`<option value="${esc(x.key)}">${esc(x.name)}</option>`).join('');document.getElementById('editOperatorRole').innerHTML=roles.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');document.getElementById('editOperatorTerritories').innerHTML=territoryOptions;document.getElementById('editRole').innerHTML='<option value="">Create new role</option>'+roles.filter(x=>!x.system).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');document.getElementById('rolePermissions').innerHTML=permissions.map(x=>`<label class="permission"><input type="checkbox" value="${esc(x)}"> ${esc(x.replaceAll('_',' '))}</label>`).join('');document.getElementById('followupCall').innerHTML='<option value="">Choose completed call</option>'+visits.map((x,i)=>`<option value="${i}">${esc(x.date)} · ${esc(x.customerName)} · ${esc(x.reference||x.kind)}</option>`).join('');document.getElementById('followupDue').value=new Date(Date.now()+7*86400000).toISOString().slice(0,10);drill('')}
  async function drill(id){const data=await api(`/api/admin/franchise-report?territory=${encodeURIComponent(id)}`),m=data.metrics,ops=id?operators.filter(x=>(x.territoryIds||[]).includes(id)):operators;document.getElementById('territoryDetail').innerHTML=`<div class="metrics">${[['Customers',m.customers],['Completed calls',m.completedCallouts],['Revenue',`£${Number(m.revenue).toFixed(2)}`],['Outstanding',`£${Number(m.outstanding).toFixed(2)}`]].map(([a,b])=>`<article class="card metric"><span>${a}</span><strong>${b}</strong></article>`).join('')}</div><h3>Operators</h3>${ops.map(x=>`<p><strong>${esc(x.name)}</strong> · ${esc(x.role)} · ${esc(x.trainingStatus||'training not started')}</p>`).join('')||'<p class="muted">No operators assigned.</p>'}<h3>Recent calls</h3>${(data.completedVisits||[]).slice(0,10).map(x=>`<p><strong>${esc(x.date)} · ${esc(x.customerName)}</strong><br>${esc(x.summary||'No summary')}</p>`).join('')||'<p class="muted">No completed calls.</p>'}`}
  async function chooseOperator(){const x=selectedOperator(),editor=document.getElementById('operatorEditor');if(!x){editor.classList.add('hidden');return}editor.classList.remove('hidden');for(const [id,value] of [['editOperatorName',x.name],['editOperatorEmail',x.email],['editOperatorPhone',x.phone],['editOperatorRole',x.role],['editOperatorStatus',x.status],['editTrainingStatus',x.trainingStatus],['editDbsStatus',x.dbsStatus],['editDbsRenewal',x.dbsRenewalDate],['editOperatorNotes',x.notes]])document.getElementById(id).value=value||'';const serviceTypes=x.configuredServiceTypes||x.serviceTypes||['home','remote'];document.getElementById('editServiceHome').checked=serviceTypes.includes('home');document.getElementById('editServiceRemote').checked=serviceTypes.includes('remote');document.getElementById('suspendHome').checked=x.homeSuspended===true;document.getElementById('suspendRemote').checked=x.remoteSuspended===true;[...document.getElementById('editOperatorTerritories').options].forEach(o=>o.selected=(x.territoryIds||[]).includes(o.value));await loadDbs(x.id)}
  async function saveOperator(){const x=selectedOperator();if(!x)return;const serviceTypes=[['home','editServiceHome'],['remote','editServiceRemote']].filter(([,id])=>document.getElementById(id).checked).map(([service])=>service);if(!serviceTypes.length)throw Error('Choose at least one service for this engineer.');const body={...x,name:document.getElementById('editOperatorName').value,email:document.getElementById('editOperatorEmail').value,phone:document.getElementById('editOperatorPhone').value,role:document.getElementById('editOperatorRole').value,status:document.getElementById('editOperatorStatus').value,territoryIds:[...document.getElementById('editOperatorTerritories').selectedOptions].map(x=>x.value),serviceTypes,homeSuspended:document.getElementById('suspendHome').checked,remoteSuspended:document.getElementById('suspendRemote').checked,trainingStatus:document.getElementById('editTrainingStatus').value,dbsStatus:document.getElementById('editDbsStatus').value,dbsRenewalDate:document.getElementById('editDbsRenewal').value,notes:document.getElementById('editOperatorNotes').value};await api('/api/admin/operators',{method:'PATCH',body:JSON.stringify(body)});document.getElementById('operatorEditStatus').textContent='Operator updated. Service restrictions now apply to new allocations.';await load()}
  async function loadDbs(id){const data=await api(`/api/admin/operator-dbs?operatorId=${encodeURIComponent(id)}`);document.getElementById('dbsDocuments').innerHTML=(data.documents||[]).map(x=>`<p><a href="/api/admin/operator-dbs?operatorId=${encodeURIComponent(id)}&fileId=${encodeURIComponent(x.id)}" data-dbs-download="${esc(x.id)}">${esc(x.name)}</a> · ${esc(x.uploadedAt.slice(0,10))}</p>`).join('')||'<p class="muted">No DBS documents uploaded.</p>'}
  async function uploadDbs(){const x=selectedOperator(),file=document.getElementById('dbsFile').files[0];if(!x||!file)return;if(file.size>2*1024*1024)throw Error('The DBS file must be no larger than 2 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});await api('/api/admin/operator-dbs',{method:'POST',body:JSON.stringify({operatorId:x.id,name:file.name,type:file.type,size:file.size,data})});await loadDbs(x.id);document.getElementById('operatorEditStatus').textContent='DBS document uploaded securely.'}
  function chooseRole(){const role=roles.find(x=>x.id===document.getElementById('editRole').value);document.getElementById('roleName').value=role?.name||'';document.getElementById('roleDescription').value=role?.description||'';[...document.querySelectorAll('#rolePermissions input')].forEach(x=>x.checked=role?.permissions?.includes(x.value)||false)}
  async function saveRole(){const id=document.getElementById('editRole').value,body={id,name:document.getElementById('roleName').value,description:document.getElementById('roleDescription').value,permissions:[...document.querySelectorAll('#rolePermissions input:checked')].map(x=>x.value)};await api('/api/admin/roles',{method:id?'PATCH':'POST',body:JSON.stringify(body)});document.getElementById('roleStatus').textContent='Role saved.';await load()}
  async function followup(){const visit=visits[Number(document.getElementById('followupCall').value)];if(!visit)throw Error('Choose a completed call.');await api('/api/admin/followups',{method:'POST',body:JSON.stringify({relatedKey:visit.key,reference:visit.reference,customerName:visit.customerName,territoryId:visit.territoryId,dueDate:document.getElementById('followupDue').value,notes:document.getElementById('followupNotes').value})});document.getElementById('followupStatus').textContent='Follow-up added to the work queue.';document.getElementById('followupNotes').value=''}
  function safe(action,status){return async()=>{try{await action()}catch(e){document.getElementById(status).textContent=e.message}}}
  function bind(){document.getElementById('drillTerritory').onchange=e=>safe(()=>drill(e.target.value),'territoryDetail')();document.getElementById('editOperator').onchange=safe(chooseOperator,'operatorEditStatus');document.getElementById('updateOperator').onclick=safe(saveOperator,'operatorEditStatus');document.getElementById('uploadDbs').onclick=safe(uploadDbs,'operatorEditStatus');document.getElementById('editRole').onchange=chooseRole;document.getElementById('saveRole').onclick=safe(saveRole,'roleStatus');document.getElementById('createFollowup').onclick=safe(followup,'followupStatus');document.addEventListener('click',async e=>{const a=e.target.closest('[data-dbs-download]');if(!a)return;e.preventDefault();try{const response=await fetch(a.href,{headers:auth()}),blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=a.textContent.trim();link.click();URL.revokeObjectURL(url)}catch{document.getElementById('operatorEditStatus').textContent='DBS document could not be downloaded.'}});load().catch(e=>document.getElementById('territoryDetail').textContent=e.message)}
  const timer=setInterval(()=>{if(install())clearInterval(timer)},100);
})();
(function(){if(document.querySelector('script[src="compliance.js"]'))return;const script=document.createElement('script');script.src='compliance.js';document.body.append(script)})();

