(()=>{
  const os=document.getElementById('os');if(!os)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label=value=>String(value||'').replaceAll('-',' ').replace(/^./,character=>character.toUpperCase());
  const headers=()=>({'content-type':'application/json','x-admin-password':sessionStorage.getItem('vipoapAdmin')||'','x-admin-session':sessionStorage.getItem('vipoapAdminSession')||''});
  const section=document.createElement('section');section.className='card hidden dashboard-panel';section.id='operationalHealth';
  section.innerHTML='<div class="row"><div><p class="dashboard-kicker">At-a-glance control room</p><h2>Business &amp; platform health</h2><p class="muted">Bookings, follow-ups, payments and system services in one place.</p></div><button class="btn secondary" id="refreshHealth" type="button">Refresh dashboard</button></div><div class="pulse-grid" id="businessPulse"></div><div class="quick-actions"><a href="/admin/">View all jobs</a><a href="/admin/customers">Customers</a><a href="/admin/health-check">Home Health Checks</a><a href="/admin/help-requests">Help requests</a><a href="/admin/billing">Billing</a><a href="/admin/franchise">Network &amp; access</a></div><h3 class="health-heading">Systems</h3><div class="metrics" id="healthServices"></div><p id="healthExceptions" class="muted"></p><div id="healthFailures"></div>';
  document.getElementById('metrics')?.before(section);
  const pulseCard=(title,value,href,tone='')=>`<a class="pulse-card ${tone}" href="${href}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>View details →</small></a>`;
  async function refresh(){
    const [healthResponse,dashboardResponse]=await Promise.all([fetch('/api/admin/health',{headers:headers()}),fetch('/api/admin/dashboard',{headers:headers()})]);
    if(!healthResponse.ok||!dashboardResponse.ok)return;
    const [data,dashboard]=await Promise.all([healthResponse.json(),dashboardResponse.json()]),m=dashboard.metrics;
    section.classList.remove('hidden');
    document.getElementById('businessPulse').innerHTML=[pulseCard('Booked today',m.today,'/admin/'),pulseCard('Next 7 days',m.nextSevenDays,'/admin/'),pulseCard('Booked this month',m.bookedThisMonth,'/admin/'),pulseCard('Completed this month',m.completedThisMonth,'/admin/','good'),pulseCard('Overdue jobs',m.overdueJobs,'/admin/',m.overdueJobs?'alert':''),pulseCard('Overdue follow-ups',m.overdueFollowUps,'/admin/os#follow-up-work',m.overdueFollowUps?'alert':''),pulseCard('Unfilled jobs',m.unfilledBookings,'/admin/',m.unfilledBookings?'warn':''),pulseCard('Needs attention',m.attention,'/admin/os#operationalHealth',m.attention?'warn':''),pulseCard('Awaiting payment',`£${Number(m.unpaidTotal).toFixed(2)}`,'/admin/billing',m.unpaidTotal?'warn':''),pulseCard('Completion rate',`${m.completionRate}%`,'/admin/','good')].join('');
    document.getElementById('healthServices').innerHTML=Object.entries(data.services).map(([name,service])=>`<article class="metric"><span>${label(name)}</span><strong class="${service.status==='ok'?'':'danger'}">${label(service.status)}</strong>${service.lastRunAt?`<small class="muted">${new Date(service.lastRunAt).toLocaleString('en-GB')}</small>`:''}</article>`).join('');
    const total=Object.values(data.exceptions).reduce((sum,value)=>sum+Number(value||0),0);document.getElementById('healthExceptions').textContent=total?`${total} failed operation${total===1?'':'s'} need attention.`:'No recorded integration, message or settlement failures.';
    const failuresResponse=await fetch('/api/admin/operational-failures',{headers:headers()});if(failuresResponse.ok){const failures=(await failuresResponse.json()).failures||[];document.getElementById('healthFailures').innerHTML=failures.map(item=>`<article class="item"><div class="row"><div><strong>${esc(label(item.stage))}</strong><p>${esc(item.message)}</p><small class="muted">${esc(new Date(item.failedAt).toLocaleString('en-GB'))}</small></div><button class="btn quiet" data-resolve-failure="${esc(item.key)}">Resolve</button></div></article>`).join('')}
  }
  async function resolveFailure(key){const notes=prompt('Resolution notes (do not include passwords or secret keys):','Issue checked and corrected.');if(notes===null)return;const response=await fetch('/api/admin/operational-failures',{method:'PATCH',headers:headers(),body:JSON.stringify({key,notes})}),data=await response.json();if(!response.ok)return alert(data.error||'Unable to resolve failure');refresh()}
  section.addEventListener('click',event=>{if(event.target.dataset.resolveFailure)resolveFailure(event.target.dataset.resolveFailure)});document.getElementById('refreshHealth').onclick=refresh;document.getElementById('loginBtn')?.addEventListener('click',()=>setTimeout(refresh,500));if(sessionStorage.getItem('vipoapAdmin')||sessionStorage.getItem('vipoapAdminSession'))refresh();
})();
