(()=>{
  const auth=()=>({'x-admin-password':sessionStorage.getItem('vipoapAdmin')||'','x-admin-session':sessionStorage.getItem('vipoapAdminSession')||''});
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const label=value=>String(value||'not-started').replaceAll('-',' ');
  let data,selectedId='',query='';
  function install(){
    const list=document.getElementById('courseListView');if(!list||document.getElementById('trainingAdmin'))return false;
    const style=document.createElement('style');style.textContent='.training-admin{border:2px solid #d8c7e2;background:linear-gradient(145deg,#fff,#faf6fc)}.admin-kicker{margin:0;color:#713b86;font-size:.78rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.admin-training-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.admin-training-metrics article{padding:14px;border:1px solid #dbe4ef;border-radius:14px;background:#fff}.admin-training-metrics strong{display:block;font-size:1.6rem;color:#713b86}.training-admin-layout{display:grid;grid-template-columns:310px 1fr;gap:16px}.engineer-search{margin-bottom:10px}.engineer-list{max-height:520px;overflow:auto;border:1px solid #dbe4ef;border-radius:14px;background:#fff}.engineer-row{display:block;width:100%;padding:13px;text-align:left;border:0;border-bottom:1px solid #e5ebf2;background:#fff;color:#102957;cursor:pointer}.engineer-row:last-child{border-bottom:0}.engineer-row:hover,.engineer-row.active{background:#eef5ec}.engineer-row strong,.engineer-row span{display:block}.engineer-row small{color:#667085}.training-record{min-width:0}.training-record-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.training-table-wrap{max-height:520px;overflow:auto;border:1px solid #dbe4ef;border-radius:14px}.training-table{width:100%;border-collapse:collapse;background:#fff}.training-table th,.training-table td{padding:11px;text-align:left;border-bottom:1px solid #e5ebf2;vertical-align:top}.training-table th{position:sticky;top:0;background:#102957;color:#fff;z-index:1}.training-table .score{font-weight:900}.training-empty{padding:24px;color:#667085}@media(max-width:850px){.training-admin-layout{grid-template-columns:1fr}.admin-training-metrics{grid-template-columns:1fr 1fr}.engineer-list{max-height:280px}.training-record-head{flex-direction:column}}';document.head.append(style);
    const section=document.createElement('section');section.id='trainingAdmin';section.className='card training-admin';section.dataset.requiresPermission='manage_training';section.innerHTML='<div class="row"><div><p class="admin-kicker">ADMIN TRAINING CONTROL</p><h2>Engineer progress and scores</h2><p class="muted">Select an engineer to review every module, lesson progress, assessment score and attempt count.</p></div><button class="btn secondary" id="refreshTrainingAdmin" type="button">Refresh</button></div><div class="admin-training-metrics" id="adminTrainingMetrics"></div><div class="training-admin-layout"><div><label for="engineerTrainingSearch">Engineers and portal users</label><input class="engineer-search" id="engineerTrainingSearch" type="search" placeholder="Search name or email"><div class="engineer-list" id="engineerTrainingList"></div></div><div class="training-record" id="engineerTrainingRecord"></div></div>';
    list.before(section);document.getElementById('refreshTrainingAdmin').onclick=load;document.getElementById('engineerTrainingSearch').oninput=event=>{query=event.target.value.toLowerCase();renderList()};document.getElementById('loginBtn')?.addEventListener('click',()=>setTimeout(load,700));const app=document.getElementById('app'),observer=new MutationObserver(()=>{if(!app.classList.contains('hidden'))load()});observer.observe(app,{attributes:true,attributeFilter:['class']});return true;
  }
  function renderMetrics(){const summary=data.summary;document.getElementById('adminTrainingMetrics').innerHTML=[['Engineers',summary.engineers],['Fully complete',summary.fullyComplete],['In progress',summary.inProgress],['Assessments passed',summary.assessmentsPassed]].map(([name,value])=>`<article><span>${name}</span><strong>${value}</strong></article>`).join('')}
  function renderList(){const engineers=data.engineers.filter(item=>!query||`${item.name} ${item.email} ${item.role}`.toLowerCase().includes(query));document.getElementById('engineerTrainingList').innerHTML=engineers.length?engineers.map(item=>`<button class="engineer-row ${item.id===selectedId?'active':''}" data-engineer-training="${esc(item.id)}" type="button"><strong>${esc(item.name)}</strong><span>${item.requiredCompleted}/${item.requiredTotal} required complete · ${item.overallProgress}%</span><small>${esc(item.email)} · ${esc(label(item.trainingStatus))}</small></button>`).join(''):'<div class="training-empty">No engineers match this search.</div>';document.querySelectorAll('[data-engineer-training]').forEach(button=>button.onclick=()=>{selectedId=button.dataset.engineerTraining;renderList();renderRecord()})}
  function renderRecord(){const engineer=data.engineers.find(item=>item.id===selectedId),target=document.getElementById('engineerTrainingRecord');if(!engineer){target.innerHTML='<div class="training-empty">Select an engineer to see their training record.</div>';return}target.innerHTML=`<div class="training-record-head"><div><h3>${esc(engineer.name)}</h3><p class="muted">${esc(engineer.email)} · ${esc((engineer.territoryIds||[]).join(', ')||'No territory')} · ${esc(label(engineer.status))}</p></div><button class="btn secondary" id="openEngineerPlan" type="button">View learning plan</button></div><div class="training-table-wrap"><table class="training-table"><thead><tr><th>Module</th><th>Lessons</th><th>Score</th><th>Attempts</th><th>Status</th><th>Last activity</th></tr></thead><tbody>${engineer.modules.map(module=>`<tr><td><strong>${esc(module.title)}</strong><br><small>${esc(module.category)}${module.required?' · Required':''}</small></td><td>${module.completedLessons}/${module.lessonCount}<br><small>${module.moduleProgress}%</small></td><td class="score">${module.score===null?'—':`${module.score}%`}<br><small>Pass ${module.passingScore}%</small></td><td>${module.attempts}</td><td><span class="pill status-${esc(module.status)}">${esc(label(module.status))}</span></td><td>${module.lastActivity?esc(String(module.lastActivity).slice(0,10)):'—'}</td></tr>`).join('')}</tbody></table></div>`;document.getElementById('openEngineerPlan').onclick=()=>{const select=document.getElementById('operatorSelect');select.value=engineer.id;select.dispatchEvent(new Event('change'));document.getElementById('courseListView').scrollIntoView({behavior:'smooth',block:'start'})}}
  function render(){renderMetrics();if(!selectedId||!data.engineers.some(item=>item.id===selectedId))selectedId=data.engineers[0]?.id||'';renderList();renderRecord()}
  async function load(){try{const response=await fetch('/api/admin/training?overview=1',{headers:auth()}),section=document.getElementById('trainingAdmin');if(response.status===403){section.hidden=true;return}const payload=await response.json();if(!response.ok)throw Error(payload.error||'Training overview could not be loaded.');section.hidden=false;data=payload;render()}catch(error){const target=document.getElementById('engineerTrainingRecord');if(target)target.innerHTML=`<div class="training-empty">${esc(error.message)}</div>`}}
  const timer=setInterval(()=>{if(!install())return;clearInterval(timer);load()},100);
})();
