import {adminContext} from '../../_shared/admin-auth.js';
import {hasPermission} from '../../_shared/permissions.js';

const DEFAULT_WEEKLY={monday:[['19:00','21:00']],wednesday:[['19:00','21:00']],saturday:[['11:00','13:00'],['16:00','19:00']]};
const DEFAULT={homeVisitWeekly:DEFAULT_WEEKLY,remoteWeekly:DEFAULT_WEEKLY,blockedDates:[],overrides:[]};
const DAYS=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
const clean=(value,max=100)=>String(value??'').trim().replace(/[<>]/g,'').slice(0,max);
const validTime=value=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value);
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(`${value}T12:00:00Z`).toISOString().slice(0,10)===value;
function validWeekly(weekly){return weekly&&typeof weekly==='object'&&Object.values(weekly).every(ranges=>Array.isArray(ranges)&&ranges.every(range=>Array.isArray(range)&&range.length===2&&validTime(range[0])&&validTime(range[1])&&range[0]<range[1]))}
function blocksFromSchedules(home={},remote={}){return Object.fromEntries(DAYS.map(day=>{const map=new Map();for(const [service,weekly] of [['home',home],['remote',remote]])for(const range of weekly?.[day]||[]){const key=range.join('-'),current=map.get(key)||{start:range[0],end:range[1],services:[]};current.services.push(service);map.set(key,current)}return[day,[...map.values()]]}))}
function validBlocks(weekly,allowed){return weekly&&typeof weekly==='object'&&DAYS.every(day=>Array.isArray(weekly[day]||[])&&(weekly[day]||[]).every(block=>validTime(block.start)&&validTime(block.end)&&block.start<block.end&&Array.isArray(block.services)&&block.services.length>0&&block.services.every(service=>allowed.includes(service))))}
function schedulesFromBlocks(weekly){const result={home:{},remote:{}};for(const day of DAYS)for(const service of ['home','remote'])result[service][day]=(weekly[day]||[]).filter(block=>block.services.includes(service)).map(block=>[block.start,block.end]);return result}
function scope(context,body={}){const requestedTerritory=clean(body.territoryId||new URL(body.url||'https://vipoap.local').searchParams.get('territory'),80),territoryId=context.territoryIds.includes('*')?(requestedTerritory||'andover'):(context.territoryIds.includes(requestedTerritory)?requestedTerritory:context.territoryIds[0]),requestedOperator=clean(body.operatorId,80),operatorId=context.territoryIds.includes('*')?(requestedOperator||context.operatorId):context.operatorId;return{territoryId,operatorId,key:`availability:${territoryId}:${operatorId}`}}

export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});const target=scope(context,{url:request.url}),stored=env.VIPOAP_DATA?await env.VIPOAP_DATA.get(target.key,'json'):null,legacy=env.VIPOAP_DATA?await env.VIPOAP_DATA.get('availability','json'):null,operator=env.VIPOAP_DATA?await env.VIPOAP_DATA.get(`operator:${target.operatorId}`,'json'):null,serviceTypes=Array.isArray(operator?.serviceTypes)&&operator.serviceTypes.length?operator.serviceTypes:['home','remote'],data={...DEFAULT,...(legacy?{homeVisitWeekly:legacy.weekly,remoteWeekly:legacy.weekly,blockedDates:legacy.blockedDates}:{}),...stored,...target};return Response.json({...data,serviceTypes,weeklyBlocks:data.weeklyBlocks||blocksFromSchedules(data.homeVisitWeekly,data.remoteWeekly)})}

export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});const body=await request.json(),target=scope(context,body),operator=await env.VIPOAP_DATA.get(`operator:${target.operatorId}`,'json'),serviceTypes=Array.isArray(operator?.serviceTypes)&&operator.serviceTypes.length?operator.serviceTypes:['home','remote'],weeklyBlocks=body.weeklyBlocks||blocksFromSchedules(body.homeVisitWeekly,body.remoteWeekly),schedules=schedulesFromBlocks(weeklyBlocks),homeVisitWeekly=schedules.home,remoteWeekly=schedules.remote,blockedDates=body.blockedDates,overrides=Array.isArray(body.overrides)?body.overrides:[];if(!validBlocks(weeklyBlocks,serviceTypes)||!validWeekly(homeVisitWeekly)||!validWeekly(remoteWeekly)||!Array.isArray(blockedDates)||!blockedDates.every(validDate)||!overrides.every(item=>validDate(item.date)&&['available','blocked'].includes(item.status)))return Response.json({error:'Choose valid days, times and services from your profile.'},{status:400});const record={...target,weeklyBlocks,homeVisitWeekly,remoteWeekly,blockedDates:[...new Set(blockedDates)],overrides,updatedAt:new Date().toISOString(),updatedBy:context.operatorId};await env.VIPOAP_DATA.put(target.key,JSON.stringify(record));return Response.json({ok:true,...target})}
