import {adminContext,canAccessTerritory} from '../../_shared/admin-auth.js';
import {hasPermission} from '../../_shared/permissions.js';
function clean(value,max=1000){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function sendConfirmation(env,booking){
  if(!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)throw new Error('Confirmation email is not configured.');
  const recipients=[booking.email,booking.bookerEmail].filter((email,index,list)=>email&&list.indexOf(email)===index);
  if(!recipients.length)return;
  const html=`<h2>Your VIPOAP appointment is confirmed</h2><p>Hello ${escapeHtml(booking.name)},</p><p>Your appointment is confirmed and the booked session has been paid.</p><p><strong>Reference:</strong> ${escapeHtml(booking.reference)}<br><strong>Support:</strong> ${escapeHtml(booking.supportType)}<br><strong>Date:</strong> ${escapeHtml(booking.date)}<br><strong>Time:</strong> ${escapeHtml(booking.time)}<br><strong>Booked duration:</strong> ${escapeHtml(booking.duration)} minutes<br><strong>Paid:</strong> ${escapeHtml(booking.price)}</p><p>If additional time is useful, your Engineer Partner will explain it and ask for your approval first. Any approved extra time will be billed after the appointment.</p><p>Need to change anything? Call 07977 254158 or email help@vipoap.co.uk.</p>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':`${booking.reference}-confirmed`},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:recipients,subject:`Your VIPOAP appointment is confirmed — ${booking.reference}`,html})});
  if(!response.ok)throw new Error(`Confirmation email failed with status ${response.status}`);
}
function canUse(context,booking){return canAccessTerritory(context,booking.territoryId||'andover')&&(context.role!=='operator'||(booking.operatorId||booking.assignedEngineerId)===context.operatorId)}
const DAY_NAMES=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
function toMinutes(time){const [hours,minutes]=String(time||'00:00').split(':').map(Number);return hours*60+minutes}
async function replacementEngineer(env,booking,bookingKey,excluded){const service=booking.supportType==='Remote support'?'remote':'home',chosen=new Date(`${booking.date}T12:00:00Z`),start=toMinutes(booking.time),end=start+Number(booking.duration||30),availabilityKeys=await env.VIPOAP_DATA.list({prefix:'availability:'}),records=(await Promise.all(availabilityKeys.keys.map(key=>env.VIPOAP_DATA.get(key.name,'json')))).filter(record=>(record?.territoryId||'andover')===(booking.territoryId||'andover')&&record.operatorId&&record.operatorId!==excluded),candidates=[];for(const record of records){const operator=await env.VIPOAP_DATA.get(`operator:${record.operatorId}`,'json'),services=Array.isArray(operator?.serviceTypes)?operator.serviceTypes:['home','remote'],override=record.overrides?.find(item=>item.date===booking.date);if(!services.includes(service)||((record.blockedDates?.includes(booking.date)||override?.status==='blocked')&&override?.status!=='available'))continue;const weekly=booking.supportType==='Remote support'?record.remoteWeekly:record.homeVisitWeekly,ranges=weekly?.[DAY_NAMES[chosen.getUTCDay()]]||[];if(ranges.some(([from,to])=>start>=toMinutes(from)&&end<=toMinutes(to)))candidates.push(record.operatorId)}const bookingKeys=await env.VIPOAP_DATA.list({prefix:`booking:${booking.date}:`}),bookings=(await Promise.all(bookingKeys.keys.map(key=>env.VIPOAP_DATA.get(key.name,'json')))).filter(Boolean),free=candidates.filter(operatorId=>!bookings.some(item=>item.key!==bookingKey&&(item.operatorId||item.assignedEngineerId)===operatorId&&!['declined','cancelled'].includes(item.status)&&start<toMinutes(item.time)+Number(item.duration||30)&&end>toMinutes(item.time))).sort((a,b)=>bookings.filter(item=>(item.operatorId||item.assignedEngineerId)===a).length-bookings.filter(item=>(item.operatorId||item.assignedEngineerId)===b).length||a.localeCompare(b));return free[0]||''}
async function sendReassignment(env,booking,operatorId){if(booking.paymentStatus!=='prepaid'||!env.RESEND_API_KEY||!env.BOOKING_FROM_EMAIL)return false;const operator=await env.VIPOAP_DATA.get(`operator:${operatorId}`,'json');if(!operator?.email)return false;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':`${booking.reference}-reassigned-${operatorId}`},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[operator.email],subject:`Paid booking reassigned to you — ${booking.reference}`,html:`<h2>VIPOAP booking reassigned</h2><p>Hello ${escapeHtml(operator.name)},</p><p>This paid booking now matches your availability and is ready to review in My Area.</p><p><strong>${escapeHtml(booking.reference)}</strong><br>${escapeHtml(booking.supportType)} · ${escapeHtml(booking.date)} at ${escapeHtml(booking.time)}<br>${escapeHtml(booking.service)}</p>`})});return response.ok}

export async function onRequestGet({request,env}){
  const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});
  if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});
  const keys=await env.VIPOAP_DATA.list({prefix:'booking:'});
  const bookings=(await Promise.all(keys.keys.map(async key=>({key:key.name,...await env.VIPOAP_DATA.get(key.name,'json')})))).filter(x=>x.reference&&canUse(context,x)).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`));
  return Response.json({bookings});
}

export async function onRequestPatch({request,env}){
  const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});
  if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});
  const body=await request.json(); const key=clean(body.key,200); const status=clean(body.status,20); const adminNotes=clean(body.adminNotes,1500);const cancellationReason=clean(body.cancellationReason,500);const cancellationWaived=Boolean(body.cancellationWaived);const cancellationCharge=status==='cancelled'&&!cancellationWaived?Math.max(0,Math.min(15,Number(body.cancellationCharge)||0)):0;
  if(!key.startsWith('booking:')||!['pending','confirmed','declined','completed','cancelled'].includes(status))return Response.json({error:'Invalid update.'},{status:400});
  const booking=await env.VIPOAP_DATA.get(key,'json'); if(!booking||!canUse(context,booking))return Response.json({error:'Booking not found.'},{status:404});
  if(context.role==='operator'&&status==='declined'){const now=new Date().toISOString(),replacement=await replacementEngineer(env,{...booking,key},key,context.operatorId),history=[...(booking.assignmentHistory||[]),{operatorId:context.operatorId,action:'declined',at:now,reason:adminNotes}];let notified=false;if(replacement)try{notified=await sendReassignment(env,booking,replacement)}catch{}const updated={...booking,operatorId:replacement,assignedEngineerId:'',status:'pending',bookingStatus:replacement?'requested':'unfilled',assignmentHistory:replacement?[...history,{operatorId:replacement,action:'reassigned',at:now}]:history,assignmentNotificationSent:notified,unfilledAt:replacement?'':now,updatedAt:now};await env.VIPOAP_DATA.put(key,JSON.stringify(updated));return Response.json({ok:true,reassignedTo:replacement||null,unfilled:!replacement})}
  if(status==='confirmed'&&booking.status!=='confirmed'&&booking.paymentStatus!=='prepaid')return Response.json({error:'Advance payment must be completed before this appointment can be confirmed.'},{status:409});
  let confirmationEmailSentAt=booking.confirmationEmailSentAt;
  if(status==='confirmed'&&!confirmationEmailSentAt){try{await sendConfirmation(env,booking);confirmationEmailSentAt=new Date().toISOString()}catch(error){return Response.json({error:error.message},{status:502})}}
  await env.VIPOAP_DATA.put(key,JSON.stringify({...booking,status,bookingStatus:status==='confirmed'?'confirmed':booking.bookingStatus,adminNotes,cancellationCharge,cancellationWaived,cancellationReason,confirmedAt:status==='confirmed'?(booking.confirmedAt||new Date().toISOString()):booking.confirmedAt,confirmationEmailSentAt,updatedAt:new Date().toISOString()}));
  return Response.json({ok:true});
}
