import {authorised} from '../../_shared/admin-auth.js';
import {normalisePhone} from '../../_shared/customers.js';
function clean(value,max=1000){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
function equipment(items){return (Array.isArray(items)?items:[]).slice(0,100).map(item=>({id:clean(item.id,60)||crypto.randomUUID(),type:clean(item.type,40),brand:clean(item.brand,60),model:clean(item.model,100),location:clean(item.location,80),ownership:clean(item.ownership,20),status:clean(item.status,20),notes:clean(item.notes,1000),upgradePriority:clean(item.upgradePriority,20),upgradeRecommendation:clean(item.upgradeRecommendation,1000)})).filter(item=>item.type)}
function attachments(items){let total=0;return (Array.isArray(items)?items:[]).slice(0,20).map(item=>{const data=String(item.data??'');total+=data.length;return{id:clean(item.id,60)||crypto.randomUUID(),name:clean(item.name,140),type:clean(item.type,100),size:Number(item.size)||0,uploadedAt:clean(item.uploadedAt,40)||new Date().toISOString(),data}}).filter(item=>item.name&&/^data:(image\/|application\/pdf|text\/plain|application\/msword|application\/vnd\.openxmlformats-officedocument\.wordprocessingml\.document)/i.test(item.data)&&item.size<=2097152&&total<=12582912)}
function record(body,env){return{name:clean(body.name,100),phone:clean(body.phone,40),phoneKey:normalisePhone(body.phone),email:clean(body.email,150),postcode:clean(body.postcode,20),address:clean(body.address,300),membership:clean(body.membership,30),customerNotes:clean(body.customerNotes,2500),equipment:equipment(body.equipment),attachments:attachments(body.attachments),territoryId:clean(body.territoryId||env.DEFAULT_TERRITORY_ID||'andover',60),operatorId:clean(body.operatorId||env.DEFAULT_OPERATOR_ID||'dan-stevens',80)}}
export async function onRequestGet({request,env}){if(!await authorised(request,env))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});const keys=await env.VIPOAP_DATA.list({prefix:'customer:'});const customers=(await Promise.all(keys.keys.map(async key=>({key:key.name,...await env.VIPOAP_DATA.get(key.name,'json')})))).filter(x=>x.name).sort((a,b)=>a.name.localeCompare(b.name));return Response.json({customers})}
export async function onRequestPost({request,env}){if(!await authorised(request,env))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});let body;try{body=await request.json()}catch{return Response.json({error:'Invalid customer record.'},{status:400})}const customer=record(body,env);if(!customer.name||!customer.phoneKey)return Response.json({error:'Enter the customer name and telephone number.'},{status:400});const key=`customer:${crypto.randomUUID()}`,now=new Date().toISOString();await env.VIPOAP_DATA.put(key,JSON.stringify({...customer,createdAt:now,updatedAt:now}));await env.VIPOAP_DATA.put(`customer-phone:${customer.phoneKey}`,key);return Response.json({ok:true,key})}
export async function onRequestPatch({request,env}){if(!await authorised(request,env))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});let body;try{body=await request.json()}catch{return Response.json({error:'Invalid customer record.'},{status:400})}const key=clean(body.key,100);if(!key.startsWith('customer:'))return Response.json({error:'Invalid customer key.'},{status:400});const existing=await env.VIPOAP_DATA.get(key,'json');if(!existing)return Response.json({error:'Customer not found.'},{status:404});const customer=record(body,env);if(!customer.name||!customer.phoneKey)return Response.json({error:'Enter the customer name and telephone number.'},{status:400});await env.VIPOAP_DATA.put(key,JSON.stringify({...existing,...customer,updatedAt:new Date().toISOString()}));await env.VIPOAP_DATA.put(`customer-phone:${customer.phoneKey}`,key);return Response.json({ok:true,key})}
