import {authorised} from '../../_shared/admin-auth.js';
async function records(kv,prefix){const keys=await kv.list({prefix});return (await Promise.all(keys.keys.map(async key=>({key:key.name,...await kv.get(key.name,'json')})))).filter(Boolean)}
export async function onRequestGet({request,env}){
  if(!await authorised(request,env))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});
  const [customers,bookings,callouts]=await Promise.all([records(env.VIPOAP_DATA,'customer:'),records(env.VIPOAP_DATA,'booking:'),records(env.VIPOAP_DATA,'callout:')]);
  const today=new Date().toISOString().slice(0,10),week=new Date(Date.now()+7*86400000).toISOString().slice(0,10),month=today.slice(0,7);
  const activeBookings=bookings.filter(x=>!['cancelled','declined'].includes(x.status));
  const followUps=callouts.filter(x=>x.followUpRequired&&!x.followUpCompleted).sort((a,b)=>(a.followUpDate||'9999').localeCompare(b.followUpDate||'9999'));
  const upgrades=customers.flatMap(customer=>(customer.equipment||[]).filter(item=>item.upgradePriority&&item.upgradePriority!=='None').map(item=>({customerId:customer.key,customerName:customer.name,phone:customer.phone,...item})))
  const activity=[...bookings.map(x=>({kind:'booking',date:x.date,time:x.time||'',customerId:x.customerId,customerName:x.name,reference:x.reference,status:x.status,summary:x.service,amount:Number(String(x.price||'').replace(/[^0-9.]/g,''))||0})),...callouts.map(x=>({kind:'call-out',date:x.date,time:'',customerId:x.customerId,customerName:x.customerName,reference:x.reference,status:x.status,summary:x.summary,amount:Number(x.amountCharged)||0}))].sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)).slice(0,40);
  const paid=callouts.filter(x=>x.paymentStatus==='paid'),unpaid=callouts.filter(x=>['unpaid','invoiced'].includes(x.paymentStatus));
  return Response.json({generatedAt:new Date().toISOString(),metrics:{customers:customers.length,members:customers.filter(x=>x.membership&&x.membership!=='none').length,today:activeBookings.filter(x=>x.date===today).length,nextSevenDays:activeBookings.filter(x=>x.date>=today&&x.date<=week).length,pendingBookings:bookings.filter(x=>(x.status||'pending')==='pending').length,openFollowUps:followUps.length,overdueFollowUps:followUps.filter(x=>x.followUpDate&&x.followUpDate<today).length,upgradeOpportunities:upgrades.length,monthRevenue:paid.filter(x=>x.date?.startsWith(month)).reduce((sum,x)=>sum+Number(x.amountCharged||0),0),unpaidTotal:unpaid.reduce((sum,x)=>sum+Number(x.amountCharged||0),0)},todayBookings:activeBookings.filter(x=>x.date===today).sort((a,b)=>a.time.localeCompare(b.time)),followUps,upgrades,activity});
}
