import {adminContext,canAccessTerritory} from '../../_shared/admin-auth.js';
import {hasPermission} from '../../_shared/permissions.js';
async function records(kv,prefix){const keys=await kv.list({prefix});return (await Promise.all(keys.keys.map(async key=>({key:key.name,...await kv.get(key.name,'json')})))).filter(Boolean)}
export async function onRequestGet({request,env}){
  const context=await adminContext(request,env);if(!hasPermission(context,'view_dashboard'))return Response.json({error:'Unauthorised'},{status:401});if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});
  const scoped=items=>items.filter(x=>canAccessTerritory(context,x.territoryId));
  const [customers,bookings,callouts,invoices,followupRecords]=await Promise.all([records(env.VIPOAP_DATA,'customer:'),records(env.VIPOAP_DATA,'booking:'),records(env.VIPOAP_DATA,'callout:'),records(env.VIPOAP_DATA,'invoice:'),records(env.VIPOAP_DATA,'followup:')]).then(groups=>groups.map(scoped));
  const today=new Date().toISOString().slice(0,10),week=new Date(Date.now()+7*86400000).toISOString().slice(0,10),month=today.slice(0,7);
  const activeBookings=bookings.filter(x=>!['cancelled','declined'].includes(x.status));
  const followUps=[...callouts.filter(x=>x.followUpRequired&&!x.followUpCompleted).map(x=>({...x,dueDate:x.followUpDate,notes:x.followUpNotes,relatedKey:x.key})),...followupRecords.filter(x=>x.status==='open').map(x=>({...x,followUpDate:x.dueDate,followUpNotes:x.notes}))].sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));
  const upgrades=customers.flatMap(customer=>(customer.equipment||[]).filter(item=>item.upgradePriority&&item.upgradePriority!=='None').map(item=>({customerId:customer.key,customerName:customer.name,phone:customer.phone,...item})))
  const activity=[...bookings.map(x=>({kind:'booking',date:x.date,time:x.time||'',customerId:x.customerId,customerName:x.name,reference:x.reference,status:x.status,summary:x.service,amount:Number(String(x.price||'').replace(/[^0-9.]/g,''))||0})),...callouts.map(x=>({kind:'call-out',date:x.date,time:'',customerId:x.customerId,customerName:x.customerName,reference:x.reference,status:x.status,summary:x.summary,amount:Number(x.amountCharged)||0}))].sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)).slice(0,40);
  const paid=callouts.filter(x=>x.paymentStatus==='paid'),unpaid=callouts.filter(x=>['unpaid','invoiced'].includes(x.paymentStatus));
  const members=customers.filter(x=>(x.membershipPlan||x.membership)&&!['none','cancelled'].includes(x.membershipPlan||x.membership)&&x.membershipStatus!=='cancelled'),nextMonth=new Date(Date.now()+30*86400000).toISOString().slice(0,10),renewals=members.filter(x=>x.membershipRenewalDate&&x.membershipRenewalDate<=nextMonth).sort((a,b)=>a.membershipRenewalDate.localeCompare(b.membershipRenewalDate));
  const invoiceRevenue=invoices.filter(x=>x.status==='paid'&&x.issueDate?.startsWith(month)).reduce((sum,x)=>sum+Number(x.total||0),0),invoiceOutstanding=invoices.filter(x=>['draft','sent'].includes(x.status)).reduce((sum,x)=>sum+Number(x.total||0),0);
  return Response.json({generatedAt:new Date().toISOString(),metrics:{customers:customers.length,members:members.length,monthlyMembershipRevenue:members.filter(x=>x.membershipStatus==='active').reduce((sum,x)=>sum+Number(x.membershipMonthlyPrice||0),0),today:activeBookings.filter(x=>x.date===today).length,nextSevenDays:activeBookings.filter(x=>x.date>=today&&x.date<=week).length,pendingBookings:bookings.filter(x=>(x.status||'pending')==='pending').length,openFollowUps:followUps.length,overdueFollowUps:followUps.filter(x=>x.dueDate&&x.dueDate<today).length,upgradeOpportunities:upgrades.length,monthRevenue:invoices.length?invoiceRevenue:paid.filter(x=>x.date?.startsWith(month)).reduce((sum,x)=>sum+Number(x.amountCharged||0),0),unpaidTotal:invoices.length?invoiceOutstanding:unpaid.reduce((sum,x)=>sum+Number(x.amountCharged||0),0)},todayBookings:activeBookings.filter(x=>x.date===today).sort((a,b)=>a.time.localeCompare(b.time)),followUps,renewals,upgrades,activity});
}
