import {authorised} from '../../_shared/admin-auth.js';
const csv=value=>{let text=String(value??'');if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`};
async function records(kv,prefix){const keys=await kv.list({prefix});return Promise.all(keys.keys.map(async key=>({key:key.name,...await kv.get(key.name,'json')})))}
export async function onRequestGet({request,env}){
  if(!await authorised(request,env,'export_data'))return Response.json({error:'Unauthorised'},{status:401});
  if(!env.VIPOAP_DATA)return Response.json({error:'VIPOAP_DATA binding is not configured.'},{status:500});
  const kind=new URL(request.url).searchParams.get('type')||'customers';let headings=[],rows=[];
  if(kind==='customers'){headings=['Customer ID','Name','Phone','Email','Postcode','Address','Membership','Billing cycle','Membership status','Zoho contact ID','Notes'];rows=(await records(env.VIPOAP_DATA,'customer:')).map(x=>[x.key,x.name,x.phone,x.email,x.postcode,x.address,x.membershipPlan||x.membership,x.membershipBillingCycle||'monthly',x.membershipStatus,x.zohoContactId,x.customerNotes])}
  else if(kind==='equipment'){headings=['Customer ID','Customer','Phone','Type','Brand','Model','Location','Ownership','Condition','Notes','Upgrade priority','Possible upgrade'];for(const customer of await records(env.VIPOAP_DATA,'customer:'))for(const item of customer.equipment||[])rows.push([customer.key,customer.name,customer.phone,item.type,item.brand,item.model,item.location,item.ownership,item.status,item.notes,item.upgradePriority,item.upgradeRecommendation])}
  else if(kind==='callouts'){headings=['Reference','Date','Customer','Phone','Postcode','Category','Minutes','Amount','Payment','Status','Problem and outcome','Work completed','Recommendations','Follow-up required','Follow-up date','Follow-up notes'];rows=(await records(env.VIPOAP_DATA,'callout:')).map(x=>[x.reference,x.date,x.customerName,x.phone,x.postcode,x.category,x.duration,x.amountCharged,x.paymentStatus,x.status,x.summary,x.actionsTaken,x.recommendations,x.followUpRequired?'Yes':'No',x.followUpDate,x.followUpNotes])}
  else if(kind==='invoices'){const customers=Object.fromEntries((await records(env.VIPOAP_DATA,'customer:')).map(x=>[x.key,x]));headings=['Invoice number','Issue date','Due date','Customer ID','Customer','Status','Subtotal','Total','Call-out key','Territory','Operator','Zoho sync status','Notes'];rows=(await records(env.VIPOAP_DATA,'invoice:')).map(x=>[x.number,x.issueDate,x.dueDate,x.customerId,customers[x.customerId]?.name||'',x.status,x.subtotal,x.total,x.calloutKey,x.territoryId,x.operatorId,x.zohoSyncStatus,x.notes])}
  else if(kind==='memberships'){headings=['Customer ID','Plan','Billing cycle','Status','Monthly price','Annual price','Start date','Renewal date','Included support available','Included support used','Zoho contact ID'];rows=(await records(env.VIPOAP_DATA,'customer:')).filter(x=>(x.membershipPlan||x.membership)!=='none').map(x=>[x.key,x.membershipPlan||x.membership,x.membershipBillingCycle||'monthly',x.membershipStatus,x.membershipMonthlyPrice,x.membershipAnnualPrice,x.membershipStartDate,x.membershipRenewalDate,x.includedVisitsAvailable,x.includedVisitsUsed,x.zohoContactId])}
  else if(kind==='payments'){headings=['Payment ID','Customer ID','Booking/Invoice reference','Type','Method','Status','Gross amount','Credit applied','Cash amount','Provider reference','Date','Territory','Operator'];const stored=await records(env.VIPOAP_DATA,'payment:');const calls=(await records(env.VIPOAP_DATA,'callout:')).filter(x=>x.paymentStatus);rows=[...stored.map(x=>[x.key,x.customerId,x.invoiceId||x.bookingId,x.type||'service',x.method,x.status,x.amount,x.creditApplied,x.cashAmount,x.providerReference,x.createdAt,x.territoryId,x.operatorId]),...calls.map(x=>[x.key,x.customerId,x.linkedBookingKey,'service',x.paymentMethod,x.paymentStatus,x.amountCharged,x.creditApplied||0,x.paymentMethod==='cash'?x.amountCharged:0,x.paymentReference,x.date,x.territoryId,x.operatorId])]}
  else if(kind==='credits'){headings=['Credit transaction ID','Customer ID','Amount','Source','Referral/Campaign reference','Booking/Payment reference','Status','Available date','Expiry date','Created date','Admin reason'];rows=(await records(env.VIPOAP_DATA,'credit:')).map(x=>[x.key,x.customerId,x.amount,x.source,x.referralId||x.campaignId,x.bookingId||x.paymentId,x.status,x.availableAt,x.expiresAt,x.createdAt,x.adminNote])}
  else if(kind==='settlements'){headings=['Settlement ID','Engineer ID','Period start','Period end','Status','Gross earnings','Cash collected','VIPOAP cash offset','Adjustments','Net payout','Payout reference','Paid date'];rows=(await records(env.VIPOAP_DATA,'settlement:')).map(x=>[x.key,x.engineerId||x.operatorId,x.periodStart,x.periodEnd,x.status,x.grossEarnings,x.cashCollected,x.vipoapCashOffset,x.adjustments,x.netPayout,x.payoutReference,x.paidAt])}
  else if(kind==='equipment-funds'){headings=['Fund ID','Customer ID','Engineer ID','Booking reference','Description','Approved amount','Actual amount','Status','Receipt reference','Created date','Updated date'];rows=(await records(env.VIPOAP_DATA,'equipment-fund:')).map(x=>[x.key,x.customerId,x.engineerId||x.operatorId,x.bookingId||x.calloutKey,x.description||x.item,x.approvedAmount,x.actualAmount,x.status,x.receiptReference,x.createdAt,x.updatedAt])}
  else if(kind==='refunds'){headings=['Refund ID','Customer ID','Original payment','Booking/Invoice reference','Type','Amount','Status','Provider reference','Reason','Created date','Completed date'];rows=(await records(env.VIPOAP_DATA,'refund:')).map(x=>[x.key,x.customerId,x.paymentId,x.bookingId||x.invoiceId,x.type,x.amount,x.status,x.providerReference,x.reason,x.createdAt,x.completedAt])}
  else return Response.json({error:'Choose customers, equipment, callouts, invoices, memberships, payments, credits, settlements, equipment-funds or refunds.'},{status:400});
  const output='\uFEFF'+[headings,...rows].map(row=>row.map(csv).join(',')).join('\r\n');
  return new Response(output,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="vipoap-${kind}-${new Date().toISOString().slice(0,10)}.csv"`,'cache-control':'no-store'}});
}
