import {adminContext} from '../../_shared/admin-auth.js';import {hasPermission} from '../../_shared/permissions.js';import {platformRules} from '../../_shared/platform-rules.js';
function clean(value,max=1000){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
const transitions={pending:['accepted','declined'],accepted:['en-route','cancelled'],['en-route']:['arrived','cancelled'],arrived:['in-progress','cancelled'],['in-progress']:['completed','partially-resolved','unresolved','safety-stopped'],['partially-resolved']:['follow-up-booked'],unresolved:['follow-up-booked']};
export async function onRequestPost({request,env}){
  const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});
  const body=await request.json(),bookingKey=clean(body.bookingKey,200),action=clean(body.action,40),booking=await env.VIPOAP_DATA.get(bookingKey,'json');if(!booking)return Response.json({error:'Booking not found.'},{status:404});
  const current=booking.jobStatus||'pending',now=new Date().toISOString();
  if(action==='approve-additional-time'){if(current!=='in-progress'||!['yes','verbal','written','app'].includes(clean(body.approvalMethod,20)))return Response.json({error:'Customer approval must be recorded during an active job.'},{status:409});const blocks=Math.max(1,Math.min(6,Math.floor(Number(body.blocks)||1))),rules=await platformRules(env),charge=blocks*rules.prices.homeAdditional30,entry={blocks,minutes:blocks*30,charge,approvalMethod:clean(body.approvalMethod,20),approvedAt:now};const updated={...booking,additionalTime:[...(booking.additionalTime||[]),entry],additionalAmount:Number(booking.additionalAmount||0)+charge,paymentStatus:booking.paymentMethod==='cash'?'cash-due':'additional-payment-due',updatedAt:now};await env.VIPOAP_DATA.put(bookingKey,JSON.stringify(updated));return Response.json({ok:true,booking:updated})}
  if(!transitions[current]?.includes(action))return Response.json({error:`Cannot move this job from ${current} to ${action}.`},{status:409});
  if(action==='accepted'&&booking.assignedEngineerId&&booking.assignedEngineerId!==context.operatorId)return Response.json({error:'This job has already been assigned.'},{status:409});
  const timestampField={accepted:'acceptedAt','en-route':'enRouteAt',arrived:'arrivedAt','in-progress':'startedAt',completed:'completedAt','partially-resolved':'completedAt',unresolved:'completedAt','safety-stopped':'stoppedAt'}[action],updated={...booking,jobStatus:action,assignedEngineerId:action==='accepted'?context.operatorId:booking.assignedEngineerId,updatedAt:now,...(timestampField?{[timestampField]:now}:{})};
  if(['completed','partially-resolved','unresolved'].includes(action)){updated.outcome=action;updated.serviceSummary=clean(body.serviceSummary,1500);updated.internalNotes=clean(body.internalNotes,2500);updated.status='completed';updated.bookingStatus=updated.paymentStatus==='additional-payment-due'?'awaiting-final-settlement':'completed'}
  await env.VIPOAP_DATA.put(bookingKey,JSON.stringify(updated));return Response.json({ok:true,booking:updated});
}
