import {adminContext} from '../../_shared/admin-auth.js';import {hasPermission} from '../../_shared/permissions.js';import {platformRules} from '../../_shared/platform-rules.js';import {createCheckout} from '../../_shared/payment-provider.js';
function clean(value,max=1000){return String(value??'').trim().replace(/[<>]/g,'').slice(0,max)}
const transitions={pending:['accepted','declined'],accepted:['en-route','cancelled'],['en-route']:['arrived','cancelled'],arrived:['in-progress','cancelled'],['in-progress']:['completed','partially-resolved','unresolved','safety-stopped'],['partially-resolved']:['follow-up-booked'],unresolved:['follow-up-booked']};
async function createFinalSettlement(env,booking,bookingKey,now){const paymentKey=`payment:additional:${booking.reference}`,existing=await env.VIPOAP_DATA.get(paymentKey,'json');if(existing?.checkoutUrl)return{payment:existing,created:false,emailed:Boolean(existing.emailSentAt)};const amount=Number(booking.additionalAmount||0);if(!(amount>0))throw new Error('No approved additional time charge was found.');const email=clean(booking.email||booking.bookerEmail,200);if(!email)throw new Error('A customer email address is required to collect the additional-time payment.');const checkout=await createCheckout(env,{amount:Math.round(amount*100),description:`VIPOAP approved additional time ${booking.reference}`,reference:`${booking.reference}-additional`,successUrl:'https://vipoap.co.uk/app/account?payment=additional-complete',cancelUrl:'https://vipoap.co.uk/app/account?payment=additional-pending',customer:{email},metadata:{bookingKey,type:'additional-time',bookingReference:booking.reference}},`additional-${booking.reference}`),payment={type:'additional-time',bookingKey,bookingReference:booking.reference,customerId:booking.customerId||'',amount,status:'pending',provider:'stripe',providerPaymentId:checkout.id,checkoutUrl:checkout.checkoutUrl,createdAt:now,updatedAt:now};let emailed=false;if(env.RESEND_API_KEY&&env.BOOKING_FROM_EMAIL){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':`${booking.reference}-additional-payment`},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:[email],subject:`Additional time payment for ${booking.reference}`,html:`<h2>Payment for your approved additional time</h2><p>Hello ${clean(booking.name,100)||'there'},</p><p>Your VIPOAP appointment is complete. The additional time you approved comes to <strong>£${amount.toFixed(2)}</strong>.</p><p><a href="${checkout.checkoutUrl}">Pay securely with Stripe</a></p><p>Your original appointment was paid separately. We will mark the job fully settled automatically once this payment is complete.</p>`})});emailed=response.ok;if(emailed)payment.emailSentAt=now}await env.VIPOAP_DATA.put(paymentKey,JSON.stringify(payment));return{payment,created:true,emailed}}
export async function onRequestPost({request,env}){
  const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Unauthorised'},{status:401});
  const body=await request.json(),bookingKey=clean(body.bookingKey,200),action=clean(body.action,40),booking=await env.VIPOAP_DATA.get(bookingKey,'json');if(!booking)return Response.json({error:'Booking not found.'},{status:404});
  const current=booking.jobStatus||'pending',now=new Date().toISOString();
  if(action==='request-additional-time'){if(current!=='in-progress')return Response.json({error:'Additional time can only be requested while the appointment is in progress.'},{status:409});const blocks=Math.max(1,Math.min(6,Math.floor(Number(body.blocks)||1))),rules=await platformRules(env),charge=blocks*rules.prices.homeAdditional30,token=crypto.randomUUID().replace(/-/g,''),channel=clean(booking.notificationChannel||'Email',20),approval={token,bookingKey,reference:booking.reference,customerName:booking.name,minutes:blocks*30,blocks,charge,channel,status:'pending',createdAt:now,expiresAt:new Date(Date.now()+3600000).toISOString()},approvalUrl=`https://vipoap.co.uk/additional-time.html?token=${token}`;await env.VIPOAP_DATA.put(`additional-time-approval:${token}`,JSON.stringify(approval),{expirationTtl:3600});let delivered=false;if(channel==='Email'&&env.RESEND_API_KEY&&env.BOOKING_FROM_EMAIL&&(booking.email||booking.bookerEmail)){const recipients=[booking.email,booking.bookerEmail].filter((email,index,list)=>email&&list.indexOf(email)===index),response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json','idempotency-key':`${booking.reference}-extra-${token}`},body:JSON.stringify({from:env.BOOKING_FROM_EMAIL,to:recipients,subject:`Approve additional time for ${booking.reference}`,html:`<h2>More time may help</h2><p>Your VIPOAP Engineer Partner has requested an additional ${blocks*30} minutes for £${charge.toFixed(2)}.</p><p>This is optional. Approve or decline securely:</p><p><a href="${approvalUrl}">Review the request</a></p><p>If approved, the additional time will be billed after the appointment.</p>`})});delivered=response.ok}await env.VIPOAP_DATA.put(bookingKey,JSON.stringify({...booking,pendingAdditionalTimeApproval:`additional-time-approval:${token}`,updatedAt:now}));return Response.json({ok:true,status:'awaiting-customer',channel,delivered,approvalUrl,minutes:blocks*30,charge})}
  if(action==='approve-additional-time'){if(current!=='in-progress'||!['yes','verbal','written','app'].includes(clean(body.approvalMethod,20)))return Response.json({error:'Customer approval must be recorded during an active job.'},{status:409});const blocks=Math.max(1,Math.min(6,Math.floor(Number(body.blocks)||1))),rules=await platformRules(env),charge=blocks*rules.prices.homeAdditional30,entry={blocks,minutes:blocks*30,charge,approvalMethod:clean(body.approvalMethod,20),approvedAt:now};const updated={...booking,additionalTime:[...(booking.additionalTime||[]),entry],additionalAmount:Number(booking.additionalAmount||0)+charge,paymentStatus:booking.paymentMethod==='cash'?'cash-due':'additional-payment-due',updatedAt:now};await env.VIPOAP_DATA.put(bookingKey,JSON.stringify(updated));return Response.json({ok:true,booking:updated})}
  if(!transitions[current]?.includes(action))return Response.json({error:`Cannot move this job from ${current} to ${action}.`},{status:409});
  if(action==='accepted'&&booking.assignedEngineerId&&booking.assignedEngineerId!==context.operatorId)return Response.json({error:'This job has already been assigned.'},{status:409});
  const timestampField={accepted:'acceptedAt','en-route':'enRouteAt',arrived:'arrivedAt','in-progress':'startedAt',completed:'completedAt','partially-resolved':'completedAt',unresolved:'completedAt','safety-stopped':'stoppedAt'}[action],updated={...booking,jobStatus:action,assignedEngineerId:action==='accepted'?context.operatorId:booking.assignedEngineerId,updatedAt:now,...(timestampField?{[timestampField]:now}:{})};
  let settlement=null,settlementError='';if(['completed','partially-resolved','unresolved'].includes(action)){updated.outcome=action;updated.serviceSummary=clean(body.serviceSummary,1500);updated.internalNotes=clean(body.internalNotes,2500);updated.status='completed';updated.bookingStatus=updated.paymentStatus==='additional-payment-due'?'awaiting-final-settlement':'completed';if(updated.paymentStatus==='additional-payment-due'){try{settlement=await createFinalSettlement(env,updated,bookingKey,now);updated.finalPaymentId=settlement.payment.providerPaymentId;updated.finalPaymentUrl=settlement.payment.checkoutUrl;updated.finalSettlementStatus='pending'}catch(error){settlementError=clean(error?.message||'Unable to create the additional-time payment link.');updated.finalSettlementStatus='setup-failed'}}}
  await env.VIPOAP_DATA.put(bookingKey,JSON.stringify(updated));return Response.json({ok:true,booking:updated,settlement:settlement?{checkoutUrl:settlement.payment.checkoutUrl,emailed:settlement.emailed,created:settlement.created}:null,...(settlementError?{warning:settlementError}:{})});
}
