import {adminContext} from '../../_shared/admin-auth.js';
import {hasPermission} from '../../_shared/permissions.js';
import {audit} from '../../_shared/audit.js';
const clean=(value,max=3000)=>String(value??'').trim().replace(/[<>]/g,'').slice(0,max),categories=['Wi-Fi','Devices','Printers','Smart home','Customer care','Safety','VIPOAP OS','Business operations'];
export const DEFAULT_ARTICLES=[
  ['wifi-first-checks','Wi-Fi','Wi-Fi is slow or drops out: first checks','A repeatable first-line diagnosis before changing equipment.','1. Confirm whether one device or every device is affected.\n2. Check the router lights and service-provider status without resetting anything.\n3. Test close to the router, then in the problem room.\n4. Record the position, construction obstacles and measured result.\n5. Restart only with permission and confirm phones, television and smart devices reconnect.'],
  ['mesh-placement','Wi-Fi','Planning a simple mesh Wi-Fi installation','Choose sensible node positions and leave the customer with a stable system.','Start with the coverage problem and property layout. Keep the main node wired to the router. Place additional nodes between the good signal and the weak area, not inside the dead zone. Update firmware, use one clear network name, test roaming and record node locations. Never promise a speed the broadband line cannot supply.'],
  ['printer-offline','Printers','Printer shows offline or will not print','Safe checks for queue, connection and driver problems.','Confirm the correct printer is selected and check for paper, ink and visible errors. Clear only failed jobs with permission. Confirm whether USB or Wi-Fi is expected. Restart the printer and computer, print a test page, then scan if that is part of the job. Avoid replacing drivers until simple checks are complete.'],
  ['new-phone-handover','Devices','New phone setup and customer handover','Move essentials without taking control of personal accounts.','Agree what is moving before starting. Let the customer enter passcodes and account credentials privately. Use the manufacturer transfer process, confirm contacts and important photos, enable updates and backup, adjust accessibility settings, then show the customer how to unlock, call, message and find help. Do not retain old-device data.'],
  ['scam-message','Safety','Customer presents a suspicious message','Pause, verify independently and protect the customer from pressure.','Do not click links, call numbers in the message or install software. Check the claimed organisation using a trusted statement, card or official website. If money or account access may be at risk, help the customer contact their bank through a trusted route. Record factual warning signs and follow the safeguarding process where needed.'],
  ['remote-session','Safety','Starting and ending a safe remote-support session','Customer-led access with a clear end point.','Confirm the planned appointment and explain the tool before connecting. Use the approved one-time session method. Ask the customer to enter passwords privately. Explain every action, stop if consent is unclear, close the session visibly and confirm there is no permanent unattended access. Record consent and outcome.'],
  ['visit-closeout','VIPOAP OS','Complete a job correctly in VIPOAP OS','Create a useful customer record, payment trail and follow-up.','Confirm the outcome with the customer. Record a plain-English service summary, factual internal notes, equipment changes and any approved additional time. Add a dated follow-up where further action is needed. Complete the Home Health Check when appropriate and never enter passwords, PINs or security answers.'],
  ['difficult-conversation','Customer care','When a customer is frustrated or embarrassed','Keep the conversation calm, respectful and useful.','Slow down and acknowledge the frustration without blaming the customer. Ask one question at a time, avoid jargon and offer a pause. Explain choices and costs before acting. Check understanding by asking the customer to show the key step back to you. Escalate complaints through VIPOAP OS rather than arguing.']
].map(([id,category,title,summary,content])=>({key:`builtin:${id}`,id,category,title,summary,content,status:'published',authorName:'VIPOAP Standards',pinned:true,replies:[],publishedAt:'2026-09-06T00:00:00.000Z',updatedAt:'2026-09-06T00:00:00.000Z'}));
async function all(kv){const page=await kv.list({prefix:'knowledge:'}),stored=await Promise.all(page.keys.map(async key=>({key:key.name,...await kv.get(key.name,'json')})));return[...DEFAULT_ARTICLES,...stored]}
function personalData(text){return /\b\d{5,}\b|@[a-z0-9.-]+\.[a-z]{2,}|\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i.test(text)}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'view_training'))return Response.json({error:'Engineer Partner access required.'},{status:403});const url=new URL(request.url),query=clean(url.searchParams.get('q'),100).toLowerCase(),category=clean(url.searchParams.get('category'),40),items=(await all(env.VIPOAP_DATA)).filter(item=>(item.status==='published'||item.authorId===context.operatorId||hasPermission(context,'manage_training'))&&(!category||item.category===category)&&(!query||`${item.title} ${item.summary} ${item.content}`.toLowerCase().includes(query))).sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))||String(b.publishedAt||b.updatedAt).localeCompare(String(a.publishedAt||a.updatedAt)));return Response.json({categories,canModerate:hasPermission(context,'manage_training'),articles:items})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'view_training'))return Response.json({error:'Engineer Partner access required.'},{status:403});const body=await request.json(),operator=context.operatorId?await env.VIPOAP_DATA.get(`operator:${context.operatorId}`,'json'):null,authorName=clean(operator?.name||'VIPOAP Engineer Partner',100);if(body.articleKey){const key=clean(body.articleKey,180),article=key.startsWith('knowledge:')?await env.VIPOAP_DATA.get(key,'json'):null,text=clean(body.reply,1500);if(!article||article.status!=='published'||!text)return Response.json({error:'Published community article and reply are required.'},{status:400});if(personalData(text))return Response.json({error:'Remove customer contact details, postcodes and other identifying information.'},{status:400});const now=new Date().toISOString(),reply={id:crypto.randomUUID(),authorId:context.operatorId,authorName,text,createdAt:now};await env.VIPOAP_DATA.put(key,JSON.stringify({...article,replies:[...(article.replies||[]),reply].slice(-100),updatedAt:now}));return Response.json({ok:true,key})}const title=clean(body.title,140),summary=clean(body.summary,300),content=clean(body.content,8000),category=clean(body.category,40);if(!title||!summary||content.length<40||!categories.includes(category))return Response.json({error:'Add a title, category, summary and useful article content.'},{status:400});if(personalData(`${title} ${summary} ${content}`))return Response.json({error:'Remove customer contact details, postcodes and other identifying information.'},{status:400});const id=crypto.randomUUID(),key=`knowledge:${id}`,now=new Date().toISOString(),record={id,title,category,summary,content,status:hasPermission(context,'manage_training')?'published':'pending-review',authorId:context.operatorId,authorName,replies:[],createdAt:now,updatedAt:now,publishedAt:hasPermission(context,'manage_training')?now:''};await env.VIPOAP_DATA.put(key,JSON.stringify(record));await audit(env,context,'submit','knowledge-article',key,{status:record.status});return Response.json({ok:true,key,status:record.status})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_training'))return Response.json({error:'Knowledge moderation access required.'},{status:403});const body=await request.json(),key=clean(body.key,180),article=key.startsWith('knowledge:')?await env.VIPOAP_DATA.get(key,'json'):null,status=clean(body.status,30);if(!article||!['published','rejected','archived'].includes(status))return Response.json({error:'Article and moderation decision are required.'},{status:400});const now=new Date().toISOString();await env.VIPOAP_DATA.put(key,JSON.stringify({...article,status,moderationNotes:clean(body.notes,800),moderatedBy:context.email,moderatedAt:now,publishedAt:status==='published'?(article.publishedAt||now):article.publishedAt,updatedAt:now}));await audit(env,context,'moderate','knowledge-article',key,{status});return Response.json({ok:true})}
