import {adminContext} from '../../_shared/admin-auth.js';
import {audit} from '../../_shared/audit.js';
import {hasPermission,roleFor} from '../../_shared/permissions.js';
const clean=(v,m=500)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,m),slug=v=>clean(v,80).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
function record(body){const configuredServiceTypes=[...new Set((Array.isArray(body.configuredServiceTypes)?body.configuredServiceTypes:Array.isArray(body.serviceTypes)?body.serviceTypes:['home','remote']).filter(value=>['home','remote'].includes(value)))],homeSuspended=body.homeSuspended===true,remoteSuspended=body.remoteSuspended===true,serviceTypes=configuredServiceTypes.filter(service=>!body[`${service}Suspended`]);return{id:slug(body.id||body.name),name:clean(body.name,100),email:clean(body.email,150).toLowerCase(),phone:clean(body.phone,40),role:slug(body.role||'operator'),status:clean(body.status||'invited',20),territoryIds:(Array.isArray(body.territoryIds)?body.territoryIds:[]).slice(0,30).map(x=>slug(x)).filter(Boolean),serviceTypes,configuredServiceTypes,homeSuspended,remoteSuspended,startDate:clean(body.startDate,10),trainingStatus:clean(body.trainingStatus||'not-started',30),dbsStatus:clean(body.dbsStatus||'not-recorded',30),dbsCheckedAt:clean(body.dbsCheckedAt,10),dbsRenewalDate:clean(body.dbsRenewalDate,10),agreementStatus:clean(body.agreementStatus||'not-issued',30),insuranceStatus:clean(body.insuranceStatus||'not-recorded',30),insuranceProvider:clean(body.insuranceProvider,100),insurancePolicyNumber:clean(body.insurancePolicyNumber,100),insuranceExpiryDate:clean(body.insuranceExpiryDate,10),notes:clean(body.notes,1500)}}
async function validRole(env,id){return Boolean(await roleFor(env,id))}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!context)return Response.json({error:'Unauthorised'},{status:401});const keys=await env.VIPOAP_DATA.list({prefix:'operator:'}),operators=(await Promise.all(keys.keys.map(async key=>({key:key.name,...await env.VIPOAP_DATA.get(key.name,'json')})))).filter(x=>x.id).map(operator=>({...operator,serviceTypes:Array.isArray(operator.serviceTypes)?operator.serviceTypes:['home','remote']}));if(!operators.length)operators.push({key:'operator:dan-stevens',id:'dan-stevens',name:'Dan Stevens',email:'admin@vipoap.co.uk',role:'owner',status:'active',territoryIds:['andover'],serviceTypes:['home','remote'],trainingStatus:'complete',dbsStatus:'not-recorded'});const visible=context.permissions?.includes('*')||hasPermission(context,'manage_operators')||hasPermission(context,'view_franchise')?operators:operators.filter(x=>x.id===context.operatorId);return Response.json({operators:visible})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_operators'))return Response.json({error:'Operator management permission required.'},{status:403});const operator=record(await request.json());if(!operator.id||!operator.name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(operator.email)||!await validRole(env,operator.role)||!operator.territoryIds.length||!operator.serviceTypes.length)return Response.json({error:'Complete the operator, email, valid role, territories and services.'},{status:400});const key=`operator:${operator.id}`;if(await env.VIPOAP_DATA.get(key))return Response.json({error:'That operator already exists.'},{status:409});const now=new Date().toISOString();await env.VIPOAP_DATA.put(key,JSON.stringify({...operator,createdAt:now,updatedAt:now}));await audit(env,context,'create','operator',key,{name:operator.name,role:operator.role});return Response.json({ok:true,key})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_operators'))return Response.json({error:'Operator management permission required.'},{status:403});const body=await request.json(),key=clean(body.key,120),existing=key.startsWith('operator:')?await env.VIPOAP_DATA.get(key,'json'):null;if(!existing)return Response.json({error:'Operator not found.'},{status:404});const operator=record({...existing,...body,id:existing.id});if(!operator.name||!await validRole(env,operator.role)||!operator.territoryIds.length||!operator.serviceTypes.length)return Response.json({error:'Complete the operator, valid role, territories and services.'},{status:400});await env.VIPOAP_DATA.put(key,JSON.stringify({...existing,...operator,updatedAt:new Date().toISOString()}));await audit(env,context,'update','operator',key,{name:operator.name,role:operator.role,status:operator.status,serviceTypes:operator.serviceTypes,homeSuspended:operator.homeSuspended,remoteSuspended:operator.remoteSuspended});return Response.json({ok:true,key})}

