import {adminContext} from '../../_shared/admin-auth.js';
import {audit} from '../../_shared/audit.js';
import {BUILT_IN_ROLES,PERMISSIONS,hasPermission} from '../../_shared/permissions.js';
const clean=(v,m=500)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,m),slug=v=>clean(v,60).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
async function custom(env){const keys=await env.VIPOAP_DATA.list({prefix:'role:'});return(await Promise.all(keys.keys.map(k=>env.VIPOAP_DATA.get(k.name,'json')))).filter(Boolean)}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'view_franchise')&&!hasPermission(context,'manage_operators')&&!hasPermission(context,'manage_roles'))return Response.json({error:'Role visibility permission required.'},{status:403});return Response.json({roles:[...Object.values(BUILT_IN_ROLES),...await custom(env)],permissions:PERMISSIONS})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_roles'))return Response.json({error:'Role management permission required.'},{status:403});const body=await request.json(),id=slug(body.id||body.name),permissions=[...new Set((Array.isArray(body.permissions)?body.permissions:[]).filter(x=>PERMISSIONS.includes(x)))],role={id,name:clean(body.name,80),description:clean(body.description,500),permissions,system:false};if(!id||!role.name||!permissions.length||BUILT_IN_ROLES[id])return Response.json({error:'Enter a unique role name and at least one permission.'},{status:400});if(await env.VIPOAP_DATA.get(`role:${id}`))return Response.json({error:'That role already exists.'},{status:409});await env.VIPOAP_DATA.put(`role:${id}`,JSON.stringify({...role,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));await audit(env,context,'create','role',`role:${id}`,{name:role.name});return Response.json({ok:true,id})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_roles'))return Response.json({error:'Role management permission required.'},{status:403});const body=await request.json(),id=slug(body.id),existing=id?await env.VIPOAP_DATA.get(`role:${id}`,'json'):null;if(!existing||existing.system||BUILT_IN_ROLES[id])return Response.json({error:'Custom role not found.'},{status:404});const permissions=[...new Set((Array.isArray(body.permissions)?body.permissions:[]).filter(x=>PERMISSIONS.includes(x)))],role={...existing,name:clean(body.name,80),description:clean(body.description,500),permissions,updatedAt:new Date().toISOString()};if(!role.name||!permissions.length)return Response.json({error:'Enter a role name and at least one permission.'},{status:400});await env.VIPOAP_DATA.put(`role:${id}`,JSON.stringify(role));await audit(env,context,'update','role',`role:${id}`,{name:role.name});return Response.json({ok:true,id})}

