import {adminContext,canAccessTerritory} from '../../_shared/admin-auth.js';
import {hasPermission} from '../../_shared/permissions.js';
import {audit} from '../../_shared/audit.js';
const clean=(value,max=1200)=>String(value??'').trim().replace(/[<>]/g,'').slice(0,max),priorities=['low','normal','high','urgent'],statuses=['new','scheduled','active','waiting-customer','escalated','follow-up','resolved','closed'];
async function records(kv,prefix){const page=await kv.list({prefix});return(await Promise.all(page.keys.map(async item=>({key:item.name,...await kv.get(item.name,'json')})))).filter(Boolean)}
const ticketStatus=item=>{const value=String(item.jobStatus||item.bookingStatus||item.status||'new').toLowerCase();if(['completed','complete','resolved'].includes(value))return'resolved';if(['confirmed','accepted','en-route','arrived'].includes(value))return'scheduled';if(value==='in-progress')return'active';if(['follow-up','follow-up-booked','information'].includes(value))return'follow-up';if(['cancelled','declined','void'].includes(value))return'closed';if(value==='looking')return'active';return'new'};
const assigned=item=>item.operatorId||item.assignedEngineerId||item.engineerId||'';
const nameFor=(operators,id)=>operators.find(item=>item.id===id)?.name||'';
async function build(env,context){
  const [bookings,helpRequests,callouts,followups,manual,overlays,operators]=await Promise.all([records(env.VIPOAP_DATA,'booking:'),records(env.VIPOAP_DATA,'help-request:'),records(env.VIPOAP_DATA,'callout:'),records(env.VIPOAP_DATA,'followup:'),records(env.VIPOAP_DATA,'ticket:'),records(env.VIPOAP_DATA,'ticket-state:'),records(env.VIPOAP_DATA,'operator:')]);
  const overlay=new Map(overlays.map(item=>[item.sourceKey,item])),bookingKeys=new Set(bookings.map(item=>item.key)),central=hasPermission(context,'manage_operations');
  const decorate=base=>{const state=overlay.get(base.sourceKey)||{},engineerId=state.assignedEngineerId||base.assignedEngineerId||'';return{...base,...state,id:base.sourceKey,sourceKey:base.sourceKey,assignedEngineerId:engineerId,assignedEngineerName:nameFor(operators,engineerId),priority:state.priority||base.priority||'normal',status:state.status||base.status,activity:[...(base.activity||[]),...(state.activity||[])]}};
  let tickets=[
    ...bookings.map(item=>decorate({sourceKey:item.key,sourceType:'booking',reference:item.reference||'',title:item.service||item.category||'Customer booking',customerId:item.customerId||'',customerName:item.name||item.customerName||'Customer',contact:item.phone||item.email||'',postcode:item.postcode||'',date:item.date||'',time:item.time||'',duration:Number(item.duration)||0,status:ticketStatus(item),jobStatus:item.jobStatus||'pending',paymentStatus:item.paymentStatus||'',summary:item.details||'',assignedEngineerId:assigned(item),territoryId:item.territoryId||'andover',customerRequestStatus:item.customerRequestStatus||'',activity:item.additionalTime?.map(entry=>({type:'extension',at:entry.approvedAt||'',text:`${entry.minutes} additional minutes approved`}))||[]})),
    ...helpRequests.map(item=>decorate({sourceKey:item.key,sourceType:'help-request',reference:item.reference||'',title:item.category==='membership'?'Membership request':item.category==='appointment'?'Appointment change request':item.category||'Customer help request',customerId:item.customerId||'',customerName:item.name||'Customer',contact:item.phone||item.email||'',postcode:item.postcode||'',date:String(item.createdAt||'').slice(0,10),time:'',duration:0,status:ticketStatus(item),jobStatus:'',paymentStatus:'',summary:item.description||item.messages?.[0]?.text||'',assignedEngineerId:assigned(item),territoryId:item.territoryId||'andover',activity:(item.messages||[]).map(message=>({type:'message',at:message.createdAt,text:`${message.author}: ${message.text}`}))})),
    ...callouts.filter(item=>!item.linkedBookingKey||!bookingKeys.has(item.linkedBookingKey)).map(item=>decorate({sourceKey:item.key,sourceType:'callout',reference:item.reference||'',title:item.category||'Logged job',customerId:item.customerId||'',customerName:item.customerName||'Customer',contact:item.phone||'',postcode:item.postcode||'',date:item.date||'',time:'',duration:Number(item.duration)||0,status:ticketStatus(item),jobStatus:item.status==='completed'?'completed':'in-progress',paymentStatus:item.paymentStatus||'',summary:item.summary||'',assignedEngineerId:assigned(item),territoryId:item.territoryId||'andover',activity:[]})),
    ...followups.map(item=>decorate({sourceKey:item.key,sourceType:'follow-up',reference:item.reference||'',title:'Follow-up or repeat call',customerId:item.customerId||'',customerName:item.customerName||'Customer',contact:item.phone||'',postcode:item.postcode||'',date:item.dueDate||'',time:'',duration:0,status:ticketStatus(item),jobStatus:'',paymentStatus:'',summary:item.notes||'',assignedEngineerId:assigned(item),territoryId:item.territoryId||'andover',priority:item.dueDate&&item.dueDate<new Date().toISOString().slice(0,10)?'high':'normal',activity:[]})),
    ...manual.map(item=>decorate({sourceKey:item.key,sourceType:item.sourceType||'manual',reference:item.reference||'',title:item.title||'Manual job',customerId:item.customerId||'',customerName:item.customerName||'Customer',contact:item.contact||'',postcode:item.postcode||'',date:item.date||'',time:item.time||'',duration:Number(item.duration)||0,status:item.status||'new',jobStatus:item.jobStatus||'',paymentStatus:item.paymentStatus||'',summary:item.summary||'',assignedEngineerId:assigned(item),territoryId:item.territoryId||'andover',priority:item.priority||'normal',parentTicketId:item.parentTicketId||'',activity:item.activity||[]}))
  ];
  tickets=tickets.filter(item=>canAccessTerritory(context,item.territoryId||'andover')&&(central||item.assignedEngineerId===context.operatorId)&&!(context.role==='operator'&&item.sourceType==='help-request'&&!item.assignedEngineerId));
  tickets.sort((a,b)=>({urgent:0,high:1,normal:2,low:3}[a.priority]-{urgent:0,high:1,normal:2,low:3}[b.priority])||`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`));
  return{tickets,operators:central?operators.filter(item=>(item.territoryIds||[]).some(id=>canAccessTerritory(context,id))).map(item=>({id:item.id,name:item.name,status:item.status})):operators.filter(item=>item.id===context.operatorId).map(item=>({id:item.id,name:item.name,status:item.status})),central};
}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Ticket access required.'},{status:403});const data=await build(env,context),counts=statuses.reduce((result,status)=>({...result,[status]:data.tickets.filter(item=>item.status===status).length}),{});return Response.json({...data,counts,total:data.tickets.length})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Ticket access required.'},{status:403});let body;try{body=await request.json()}catch{return Response.json({error:'Please check the ticket.'},{status:400})}const title=clean(body.title,160),customerName=clean(body.customerName,120),summary=clean(body.summary),priority=priorities.includes(body.priority)?body.priority:'normal',territoryId=clean(body.territoryId||context.territoryIds?.[0]||'andover',60),assignedEngineerId=context.role==='operator'?context.operatorId:clean(body.assignedEngineerId,80);if(!title||!customerName||!summary||!canAccessTerritory(context,territoryId))return Response.json({error:'Add the customer, job title and a short description.'},{status:400});const now=new Date().toISOString(),reference=`TKT-${now.slice(5,10).replace('-','')}-${crypto.randomUUID().slice(0,4).toUpperCase()}`,key=`ticket:${crypto.randomUUID()}`,ticket={reference,title,customerId:clean(body.customerId,120),customerName,contact:clean(body.contact,150),postcode:clean(body.postcode,20),date:clean(body.date,10)||now.slice(0,10),time:clean(body.time,5),duration:Math.max(0,Math.min(480,Number(body.duration)||0)),priority,status:'new',sourceType:clean(body.sourceType||'manual',30),parentTicketId:clean(body.parentTicketId,250),assignedEngineerId,territoryId,summary,activity:[{type:'created',at:now,text:'Ticket created',by:context.email}],createdAt:now,updatedAt:now};await env.VIPOAP_DATA.put(key,JSON.stringify(ticket));await audit(env,context,'create','ticket',key,{reference,priority,assignedEngineerId});return Response.json({ok:true,key,reference,ticket},{status:201})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_calls'))return Response.json({error:'Ticket access required.'},{status:403});let body;try{body=await request.json()}catch{return Response.json({error:'Please check the update.'},{status:400})}const sourceKey=clean(body.sourceKey,260),current=(await build(env,context)).tickets.find(item=>item.sourceKey===sourceKey);if(!current)return Response.json({error:'Ticket not found.'},{status:404});const action=clean(body.action,30),now=new Date().toISOString(),existing=await env.VIPOAP_DATA.get(`ticket-state:${sourceKey}`,'json')||{sourceKey,activity:[]};let changes={};if(action==='escalate')changes={status:'escalated',priority:'urgent',escalationReason:clean(body.note)||'Engineer requested help'};else if(action==='note'){if(!clean(body.note))return Response.json({error:'Add a note.'},{status:400});changes={};}else if(action==='update')changes={status:statuses.includes(body.status)?body.status:current.status,priority:priorities.includes(body.priority)?body.priority:current.priority,assignedEngineerId:hasPermission(context,'manage_operations')?clean(body.assignedEngineerId,80):current.assignedEngineerId};else return Response.json({error:'Choose update, note or escalate.'},{status:400});const text=action==='escalate'?`Escalated: ${changes.escalationReason}`:action==='note'?clean(body.note):`Ticket updated to ${changes.status}`,activity=[...(existing.activity||[]),{type:action,at:now,text,by:context.email}],next={...existing,...changes,sourceKey,activity,updatedAt:now};await env.VIPOAP_DATA.put(`ticket-state:${sourceKey}`,JSON.stringify(next));await audit(env,context,action,'ticket',sourceKey,{status:next.status,priority:next.priority});return Response.json({ok:true,ticket:{...current,...next}})}
