import {adminContext,canAccessTerritory} from '../../_shared/admin-auth.js';
import {audit} from '../../_shared/audit.js';
import {hasPermission} from '../../_shared/permissions.js';
const clean=(v,m=1500)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,m),slug=v=>clean(v,80).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
export const DEFAULT_COURSES=[
  ['brand-promise','VIPOAP brand and customer promise','Brand','Consistent identity, tone, pricing clarity and aftercare.'],
  ['customer-care','Patient customer communication','Customer care','Plain language, consent, accessibility and involving trusted family.'],
  ['safeguarding','Safeguarding and vulnerable customers','Safety','Recognising concerns, boundaries and escalation.'],
  ['data-protection','Data protection and secure records','Compliance','Privacy, secure devices, records, files and incidents.'],
  ['cyber-safety','Scams, passwords and online safety','Technical','Fraud warning signs, secure account help and safe boundaries.'],
  ['home-visits','Safe home visits and lone working','Safety','Arrival, identification, risk assessment and escalation.'],
  ['vipoap-os','Using VIPOAP OS','Operations','Customers, bookings, calls, equipment, files, costs and follow-ups.'],
  ['wifi','Wi-Fi and mesh support','Technical','Diagnosis, router placement, mesh setup and handover.'],
  ['devices','Phones, tablets and computers','Technical','Setup, accessibility, updates, backups and troubleshooting.'],
  ['printers-tv','Printers, smart TVs and connected devices','Technical','Setup, connectivity, accounts and customer handover.'],
  ['pricing-membership','Pricing, invoices and memberships','Commercial','No-surprise pricing, membership entitlements and payment records.'],
  ['complaints','Complaints and service recovery','Standards','Listening, recording, escalation, remedies and learning.'],
  ['franchise-standards','Territory and franchise standards','Franchise','Territory rules, reporting, brand control and quality reviews.']
].map(([id,title,category,summary])=>({id,title,category,summary,required:true,lessons:[`Understand ${title.toLowerCase()}`,`Apply the VIPOAP standard`, 'Complete a practical knowledge check']}));
async function courses(env){const keys=await env.VIPOAP_DATA.list({prefix:'training-course:'}),stored=(await Promise.all(keys.keys.map(x=>env.VIPOAP_DATA.get(x.name,'json')))).filter(Boolean);return stored.length?stored:DEFAULT_COURSES}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!context||!hasPermission(context,'view_training'))return Response.json({error:'Training access required.'},{status:403});const url=new URL(request.url),operatorId=clean(url.searchParams.get('operatorId')||context.operatorId,80),operator=await env.VIPOAP_DATA.get(`operator:${operatorId}`,'json');if(operator&&!operator.territoryIds.some(x=>canAccessTerritory(context,x))&&!hasPermission(context,'manage_training'))return Response.json({error:'Operator access denied.'},{status:403});const allCourses=await courses(env),keys=await env.VIPOAP_DATA.list({prefix:`training-progress:${operatorId}:`}),progress=(await Promise.all(keys.keys.map(x=>env.VIPOAP_DATA.get(x.name,'json')))).filter(Boolean);return Response.json({courses:allCourses,progress,operatorId})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_training'))return Response.json({error:'Training management permission required.'},{status:403});const body=await request.json(),id=slug(body.id||body.title),course={id,title:clean(body.title,120),category:clean(body.category,60),summary:clean(body.summary,600),required:Boolean(body.required),lessons:(Array.isArray(body.lessons)?body.lessons:[]).slice(0,20).map(x=>clean(x,200)).filter(Boolean)};if(!id||!course.title||!course.lessons.length)return Response.json({error:'Enter a course title and lessons.'},{status:400});await env.VIPOAP_DATA.put(`training-course:${id}`,JSON.stringify({...course,updatedAt:new Date().toISOString()}));await audit(env,context,'save','training-course',`training-course:${id}`,{title:course.title});return Response.json({ok:true,id})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!context||!hasPermission(context,'view_training'))return Response.json({error:'Training access required.'},{status:403});const body=await request.json(),operatorId=slug(body.operatorId||context.operatorId),courseId=slug(body.courseId),operator=await env.VIPOAP_DATA.get(`operator:${operatorId}`,'json');if(operatorId!==context.operatorId&&!hasPermission(context,'manage_training'))return Response.json({error:'Training management permission required.'},{status:403});if(!operator||!courseId)return Response.json({error:'Operator and course are required.'},{status:400});const status=clean(body.status,30);if(!['not-started','in-progress','complete','expired'].includes(status))return Response.json({error:'Choose a valid training status.'},{status:400});const key=`training-progress:${operatorId}:${courseId}`,existing=await env.VIPOAP_DATA.get(key,'json')||{},now=new Date().toISOString(),record={...existing,operatorId,courseId,status,score:Math.max(0,Math.min(100,Number(body.score)||0)),notes:clean(body.notes,1000),evidence:clean(body.evidence,500),completedAt:status==='complete'?(existing.completedAt||now):'',reviewDue:clean(body.reviewDue,10),updatedAt:now,updatedBy:context.email};await env.VIPOAP_DATA.put(key,JSON.stringify(record));await audit(env,context,'update','training-progress',key,{status});return Response.json({ok:true,key})}

