import {adminContext,canAccessTerritory} from '../../_shared/admin-auth.js';
import {audit} from '../../_shared/audit.js';
import {hasPermission} from '../../_shared/permissions.js';
const clean=(v,m=1500)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,m),slug=v=>clean(v,80).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
export const DEFAULT_COURSES=[
  ['brand-promise','VIPOAP brand and customer promise','Brand','Consistent identity, tone, pricing clarity and aftercare.'],
  ['customer-care','Patient customer communication','Customer care','Plain language, consent, accessibility and involving trusted family.'],
  ['safeguarding','Safeguarding and vulnerable customers','Safety','Recognising concerns, boundaries and escalation.'],
  ['data-protection','Data protection and secure records','Compliance','Privacy, secure devices, records, files and incidents.'],
  ['cyber-safety','Scams, passwords and online safety','Technical','Fraud warning signs, secure account help and safe boundaries.'],
  ['home-visits','Safe home visits and lone working','Safety','Arrival, identification, risk assessment and escalation.'],
  ['vipoap-os','Using VIPOAP OS','Operations','Customers, bookings, calls, equipment, files, costs and follow-ups.'],
  ['wifi','Wi-Fi and mesh support','Technical','Diagnosis, router placement, mesh setup and handover.'],
  ['devices','Phones, tablets and computers','Technical','Setup, accessibility, updates, backups and troubleshooting.'],
  ['printers-tv','Printers, smart TVs and connected devices','Technical','Setup, connectivity, accounts and customer handover.'],
  ['pricing-membership','Pricing, invoices and memberships','Commercial','No-surprise pricing, membership entitlements and payment records.'],
  ['complaints','Complaints and service recovery','Standards','Listening, recording, escalation, remedies and learning.'],
  ['franchise-standards','Territory and franchise standards','Franchise','Territory rules, reporting, brand control and quality reviews.']
].map(([id,title,category,summary])=>({id,title,category,summary,required:true,passingScore:80,lessons:[`Understand ${title.toLowerCase()}`,`Apply the VIPOAP standard`, 'Complete a practical knowledge check'],questions:[{id:'standard',prompt:`Which approach best reflects the VIPOAP standard for ${title.toLowerCase()}?`,options:['Work patiently, explain clearly, obtain consent and record the outcome','Make changes quickly without explaining them','Ask the customer to share passwords for later use'],correctIndex:0}]}));
async function courses(env){const keys=await env.VIPOAP_DATA.list({prefix:'training-course:'}),stored=(await Promise.all(keys.keys.map(x=>env.VIPOAP_DATA.get(x.name,'json')))).filter(Boolean);return stored.length?stored:DEFAULT_COURSES}
export async function onRequestGet({request,env}){const context=await adminContext(request,env);if(!context||!hasPermission(context,'view_training'))return Response.json({error:'Training access required.'},{status:403});const url=new URL(request.url),operatorId=clean(url.searchParams.get('operatorId')||context.operatorId,80),operator=await env.VIPOAP_DATA.get(`operator:${operatorId}`,'json');if(operator&&!operator.territoryIds.some(x=>canAccessTerritory(context,x))&&!hasPermission(context,'manage_training'))return Response.json({error:'Operator access denied.'},{status:403});const allCourses=(await courses(env)).map(course=>({...course,questions:(course.questions||[]).map(({correctIndex,...question})=>question)})),keys=await env.VIPOAP_DATA.list({prefix:`training-progress:${operatorId}:`}),progress=(await Promise.all(keys.keys.map(x=>env.VIPOAP_DATA.get(x.name,'json')))).filter(Boolean);return Response.json({courses:allCourses,progress,operatorId,canTakeAssessment:operatorId===context.operatorId})}
export async function onRequestPost({request,env}){const context=await adminContext(request,env);if(!hasPermission(context,'manage_training'))return Response.json({error:'Training management permission required.'},{status:403});const body=await request.json(),id=slug(body.id||body.title),options=(Array.isArray(body.options)?body.options:[]).slice(0,6).map(x=>clean(x,200)).filter(Boolean),question={id:'knowledge-check',prompt:clean(body.question,300),options,correctIndex:Math.max(0,Math.min(options.length-1,Number(body.correctIndex)||0))},course={id,title:clean(body.title,120),category:clean(body.category,60),summary:clean(body.summary,600),required:Boolean(body.required),passingScore:80,lessons:(Array.isArray(body.lessons)?body.lessons:[]).slice(0,20).map(x=>clean(x,200)).filter(Boolean),questions:[question]};if(!id||!course.title||!course.lessons.length||!question.prompt||options.length<2)return Response.json({error:'Enter a course title, lessons and a knowledge check with at least two answers.'},{status:400});await env.VIPOAP_DATA.put(`training-course:${id}`,JSON.stringify({...course,updatedAt:new Date().toISOString()}));await audit(env,context,'save','training-course',`training-course:${id}`,{title:course.title});return Response.json({ok:true,id})}
export async function onRequestPatch({request,env}){const context=await adminContext(request,env);if(!context||!hasPermission(context,'view_training'))return Response.json({error:'Training access required.'},{status:403});const body=await request.json(),operatorId=slug(body.operatorId||context.operatorId),courseId=slug(body.courseId),operator=await env.VIPOAP_DATA.get(`operator:${operatorId}`,'json');if(operatorId!==context.operatorId)return Response.json({error:'Only the assigned engineer can take this assessment.'},{status:403});if(!operator||!courseId)return Response.json({error:'Operator and course are required.'},{status:400});if('status' in body||'score' in body)return Response.json({error:'Training status and scores are set automatically from assessment results.'},{status:400});const course=(await courses(env)).find(item=>item.id===courseId),answers=Array.isArray(body.answers)?body.answers.map(Number):[];if(!course||!course.questions?.length||answers.length!==course.questions.length)return Response.json({error:'Answer every knowledge-check question.'},{status:400});const correct=course.questions.reduce((total,question,index)=>total+(answers[index]===question.correctIndex?1:0),0),score=Math.round(correct/course.questions.length*100),passingScore=Number(course.passingScore)||80,status=score>=passingScore?'complete':'in-progress',key=`training-progress:${operatorId}:${courseId}`,existing=await env.VIPOAP_DATA.get(key,'json')||{},now=new Date().toISOString(),attempt={attemptedAt:now,score,passed:status==='complete'},record={...existing,operatorId,courseId,status,score,attempts:[...(existing.attempts||[]),attempt].slice(-10),completedAt:status==='complete'?(existing.completedAt||now):'',updatedAt:now,updatedBy:context.email};await env.VIPOAP_DATA.put(key,JSON.stringify(record));await audit(env,context,'assess','training-progress',key,{status,score});return Response.json({ok:true,key,status,score,passingScore})}

